"""Enumerate genuine blow-up forests over L_infty and solve the Keller boundary
   ledger.  A forest is generated by a sequence of blow-ups; the parametrisation
   is by the tree together with the non-negative integers c_C = Z.C, from which
   a_i, D, m_C, N are all determined:
        a_i = c_i + sum{ a_j : p_j lies on Etilde_i },      D = c_L + sum_{I_0} a_i
        m_i = sum{ m_C : C ∋ p_i } - a_i,                   m_L = D,   N = sum m_C c_C .
   Adjacency (hence which pairs may carry a satellite point) is tracked exactly.
"""
import itertools, math, sys
sys.path.insert(0,'/tmp/nvm')

def gen_forests(r):
    """yield lists par[0..r-1]; par[i] is a tuple of parents ('L' or index<i).
       Adjacency is maintained; a satellite point needs two adjacent components."""
    def rec(i, par, adj):
        if i == r:
            yield list(par); return
        comps = ['L'] + list(range(i))
        for c1 in comps:
            # free point on c1
            nadj = {k: set(v) for k, v in adj.items()}
            nadj[i] = {c1}; nadj[c1].add(i)
            yield from rec(i+1, par+[(c1,)], nadj)
        for c1, c2 in itertools.combinations(comps, 2):
            if c2 not in adj[c1]: continue
            nadj = {k: set(v) for k, v in adj.items()}
            nadj[c1].discard(c2); nadj[c2].discard(c1)
            nadj[i] = {c1, c2}; nadj[c1].add(i); nadj[c2].add(i)
            yield from rec(i+1, par+[(c1, c2)], nadj)
    yield from rec(0, [], {'L': set()})

def evaluate(par, c):
    """c = dict {'L':cL, 0:c0, ...}. returns a, D, m, N or None if inconsistent."""
    r = len(par)
    children = {k: [] for k in ['L']+list(range(r))}
    for i, p in enumerate(par):
        for q in p: children[q].append(i)
    a = [None]*r
    for i in range(r-1, -1, -1):
        a[i] = c[i] + sum(a[j] for j in children[i])
        if a[i] <= 0: return None
    D = c['L'] + sum(a[i] for i in children['L'])
    m = {'L': D}
    for i in range(r):
        m[i] = sum(m[q] for q in par[i]) - a[i]
        if m[i] < 0: return None
    N = D*D - sum(v*v for v in a)
    return a, D, m, N

def ledger(par, c, Nt):
    ev = evaluate(par, c)
    if ev is None: return None
    a, D, m, N = ev
    if N != Nt or D <= Nt: return None
    keys = ['L']+list(range(len(par)))
    if sum(m[k]*c[k] for k in keys) != N: return None
    dic = [k for k in keys if m[k] == 0 and c[k] > 0]
    onto = [k for k in keys if m[k] > 0 and c[k] > 0]
    if not dic or not onto: return None
    kap = sum(c[k] for k in onto); Lam = sum(c[k] for k in dic)
    T = sum(a[i] for i in range(len(par)) if len(par[i]) == 2)
    if kap + Lam + T != D: return None
    A = sum(a)
    out = []
    for n in range(1, Lam+1):
        if any(c[k] % n for k in dic): continue
        S = sum(c[k]//n for k in dic)
        for aa in range(math.ceil(N/2), N-1):
            W = N-aa
            if W < 2*S: continue
            if A == 3*D - 2*N - kap + n*(W-S):
                out.append((n, S, W, aa))
    if not out: return None
    return dict(D=D, N=N, kap=kap, Lam=Lam, T=T, A=A, a=a, sols=out, par=par, c=dict(c))

def scan(Nt, r, cmax):
    best = {}
    keys_tmpl = None
    for par in gen_forests(r):
        keys = ['L']+list(range(r))
        for vals in itertools.product(range(cmax+1), repeat=r+1):
            c = dict(zip(keys, vals))
            if sum(vals) == 0: continue
            res = ledger(par, c, Nt)
            if res:
                for sol in res['sols']:
                    k = (sol[0], sol[1], sol[2])
                    if k not in best or res['D'] > best[k]['D']:
                        best[k] = res
    return best

if __name__ == "__main__":
    Nt, r, cmax = int(sys.argv[1]), int(sys.argv[2]), int(sys.argv[3])
    b = scan(Nt, r, cmax)
    print("N=%d  r=%d  cmax=%d :  %d (n,S,W) classes" % (Nt, r, cmax, len(b)))
    for k in sorted(b):
        v = b[k]
        print("   (n,S,W)=%-12s D=%-3d kap=%-2d Lam=%-3d T=%-3d A=%-4d a=%s"
              % (str(k), v['D'], v['kap'], v['Lam'], v['T'], v['A'], v['a']))
