#!/usr/bin/env python3
"""Resumed exact finite-chart recursion on the TRIPLE02 node-1 closed successor.

Continues the frozen r5 recursion contract on

    I_node2 = ( branch_factor, root_chart_delta, Delta_node1 ),

with global node numbering beginning at 2 and inherited rank upper bound 6.
Every Singular stage script is generated by the hash-pinned frozen r5 builders,
with two repaired stage templates:

  * saturation: adds per-generator reverse-containment witnesses (bounded 64)
    on the proper-open branch and gates the 257-step pure-delta power search to
    the empty-open branch only (the search stays mandatory there);
  * chart: adds the full right-transform recording, exact operation-count
    gates, the endpoint plus-one/plus-two shift plants, and an ACTIVE standard
    basis artifact for cross-stage byte comparison.

The settled node-1 proper open D(Delta_node1) is never re-entered: node
numbering starts at 2, every node ideal contains Delta_node1, and each node's
scanned delta literal is checked against the Delta_node1 hash.

R2 custody: the driver requires the full job binding environment (job tag,
schema-checked nonce, lease, source-archive hash, Singular binary hash, live
worker/supervisor identities) and passes it to every stage runner; each stage
result must bind exactly this job and hash its own identity record, and the
driver banks the result-record hash so the summary transitively binds every
stage.  The archived node-1 standard basis is three identical appended copies
(Singular write() appends and reduce/rank/saturation each wrote it), so the
witness replay compares its single copy against the exact repeating unit.

Stages run through run_singular_stage.py inside the supervisor's containment
(never a nested session).  A stage timeout or an exhausted reverse-containment
search ends the run as a bounded no-verdict derived from the exact driver
state; any other irregularity is an adapter failure.  Exactly one summary
classification is written.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import re
import subprocess
import sys


FROZEN_R5_SHA256 = "d679a4d7fb4bf2619fbb3ff47ea6f386ba1c75fdc477276cabf3bec8a2b2cd90"
TRANSCRIPT_GATE_SHA256 = (
    "0e0efd5ada59039a373a731038f2f88a3794b376b208879c2459bff97d0e7316")
DELTA_NODE1_SHA256 = (
    "84b4c2c4c0bfe5aa7414c35813cc1cf63d7d5416358a394b8e8bdc35820f1d02")
GENERATOR_SHA256 = (
    "2b9d29b706ce5d7e58e2dc5a28799782f5610c5ccb7b71987ebd694fd8b83206",
    "fecd1d43f3f55e1c65bec858303b7688c0db83dbe9c3a60f51f70130a4149336",
    DELTA_NODE1_SHA256,
)
RING_DECLARATION = "ring ambient=0,(q0,q2,c4,c6),dp;"
NONCE_RE = re.compile(r"^[a-z0-9]{8,32}$")
# The archived R3 node-1 directory ran exactly reduce, rank_size_6, and
# saturation; each stage's node_header appended one copy of the standard
# basis, so the archived NODE_001_STANDARD_BASIS.txt is exactly three
# identical concatenated copies of the single-stage write.
ARCHIVED_NODE1_SB_APPEND_COUNT = 3

CLASS_DEAD = "EXACT_ENDPOINT_DEAD_ON_TRIPLE02_NODE1_CLOSED_SUCCESSOR_FINITE_COVER"
CLASS_SURVIVOR = ("RING_LEVEL_ENDPOINT_SURVIVOR_ON_TRIPLE02_NODE1_"
                  "CLOSED_SUCCESSOR_CHART_PENDING_NILPOTENCE_RADICAL")
CLASS_NO_VERDICT = "NO_VERDICT_OPEN_REMAINDER_ON_TRIPLE02_NODE1_CLOSED_SUCCESSOR"
CLASS_REVERSE = ("REVERSE_CONTAINMENT_SEARCH_EXHAUSTED_NO_VERDICT_ON_"
                 "TRIPLE02_NODE1_CLOSED_SUCCESSOR")
CLASS_ADAPTER = "ADAPTER_FAILURE_NO_VERDICT"

WITNESS_REPLAY_MARKERS = (
    "NODE_INDEX=1",
    "NODE_GENERATOR_COUNT=2",
    "NODE_EMPTY=0",
    "NODE_REDUCER_FIXTURES_PASS=1",
    "NF_RATIONAL_UNIT_PIVOT_COUNT=95",
    "NF_PIVOT_INVARIANT_FAILURES=0",
    "NODE_RESIDUAL_REDUCTION_COMPLETE=1",
    "WITNESS_MINOR_ROWS=1,2,4,7,9,11",
    "WITNESS_MINOR_COLS=1,2,3,5,6,7",
    "WITNESS_DELTA_NF_NONZERO=1",
    "WITNESS_DELTA_EQUALS_ARCHIVED=1",
    "WITNESS_DELTA_NF_STABLE=1",
    "CLOSED_SUCCESSOR_GENERATOR_COUNT=3",
    "CLOSED_SUCCESSOR_CONTAINS_DELTA=1",
    "NODE1_OPEN_SATURATION_ENTERED=0",
    "NODE1_PURE_DELTA_POWER_SEARCH_ENTERED=0",
    "NODE1_PROPER_OPEN_CHART_ENTERED=0",
    "SETTLED_OPEN_ROUTE_NOT_REENTERED=1",
    "WITNESS_REPLAY_COMPLETE=1",
)

STAGE_RESULT_BINDING_KEYS = (
    "argv", "cap_seconds", "expected_pgid", "expected_sid", "identity_sha256",
    "job_nonce", "job_tag", "lease_sha256", "returncode", "script_sha256",
    "singular_sha256", "source_archive_sha256", "stage_label", "stderr_sha256",
    "stdout_sha256", "supervisor_starttime", "timed_out", "worker_starttime",
)


class StageTimeout(Exception):
    def __init__(self, node: object, stage: str):
        super().__init__(f"{node}:{stage}")
        self.node = node
        self.stage = stage


class ReverseExhausted(Exception):
    def __init__(self, node: int):
        super().__init__(str(node))
        self.node = node


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def load_pinned(name: str, path: Path, expected_sha: str,
                with_parent_path: bool = False):
    if sha256(path) != expected_sha:
        raise SystemExit(f"PINNED_MODULE_SHA_DRIFT:{name}")
    if with_parent_path:
        sys.path.insert(0, str(path.parent))
    try:
        spec = importlib.util.spec_from_file_location(name, path)
        if spec is None or spec.loader is None:
            raise SystemExit(f"PINNED_MODULE_IMPORT_FAILURE:{name}")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module
    finally:
        if with_parent_path:
            sys.path.pop(0)


def identical_copies(data: bytes) -> tuple[bytes, int]:
    """Return (unit, count) with data == unit * count and count maximal."""
    if not data:
        raise RuntimeError("EMPTY_APPENDED_ARTIFACT")
    length = len(data)
    for count in range(length, 0, -1):
        if length % count:
            continue
        unit = data[:length // count]
        if unit * count == data:
            return unit, count
    raise RuntimeError("UNREACHABLE_APPENDED_ARTIFACT_DECOMPOSITION")


def require_archived_append_copies(produced: bytes, archived: bytes,
                                   count: int, label: str) -> None:
    """The archived file must be exactly `count` appended copies of produced."""
    if count < 1 or not produced or produced * count != archived:
        raise RuntimeError(f"ARCHIVED_APPEND_COPY_DISAGREEMENT:{label}:{count}")


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if text.count(old) != 1:
        raise RuntimeError(f"STAGE_TEMPLATE_ANCHOR_CENSUS:{label}:{text.count(old)}")
    return text.replace(old, new, 1)


def build_repaired_saturation_script(r5, remaining: list[str],
                                     generators: list[str], node: int,
                                     scanned_delta: str) -> str:
    script = r5.build_saturation_script(remaining, generators, node,
                                        scanned_delta)
    reverse_block = "\n".join([
        f'string REVERSE_ATTEMPT_FILE="NODE_{node:03d}_REVERSE_CONTAINMENT_ATTEMPTS.tsv"; string REVERSE_WITNESS_FILE="NODE_{node:03d}_REVERSE_CONTAINMENT_WITNESSES.tsv";',
        'write(REVERSE_ATTEMPT_FILE,"basis_generator|exponent|normal_form"); write(REVERSE_WITNESS_FILE,"basis_generator|found|exponent|normal_form");',
        "int reverse_basis_index; int reverse_exponent; int reverse_found; int reverse_found_exponent; int reverse_found_count=0; int reverse_membership_reduction_count=0; poly REVERSE_POWER; poly REVERSE_NF;",
        'if(OPEN_UNIT_NF!=0){ for(reverse_basis_index=1;reverse_basis_index<=size(OPEN_SB);reverse_basis_index=reverse_basis_index+1){ REVERSE_POWER=1; REVERSE_NF=1; reverse_found=0; reverse_found_exponent=-1; for(reverse_exponent=0;reverse_exponent<=64;reverse_exponent=reverse_exponent+1){ if(reverse_found==0){ REVERSE_NF=reduce(REVERSE_POWER*OPEN_SB[reverse_basis_index],NODE_SB); reverse_membership_reduction_count=reverse_membership_reduction_count+1; write(REVERSE_ATTEMPT_FILE,string(reverse_basis_index)+"|"+string(reverse_exponent)+"|"+string(REVERSE_NF)); if(REVERSE_NF==0){ reverse_found=1; reverse_found_exponent=reverse_exponent; reverse_found_count=reverse_found_count+1; } else { REVERSE_POWER=reduce(REVERSE_POWER*DELTA_NODE_NF,NODE_SB); } } } write(REVERSE_WITNESS_FILE,string(reverse_basis_index)+"|"+string(reverse_found)+"|"+string(reverse_found_exponent)+"|"+string(REVERSE_NF)); } }',
        'print("REVERSE_CONTAINMENT_ENTERED="+string(OPEN_UNIT_NF!=0));',
        'print("REVERSE_CONTAINMENT_BASIS_GENERATOR_COUNT="+string(size(OPEN_SB)));',
        'print("REVERSE_CONTAINMENT_WITNESS_FOUND_COUNT="+string(reverse_found_count));',
        'print("REVERSE_CONTAINMENT_MEMBERSHIP_REDUCTION_COUNT="+string(reverse_membership_reduction_count));',
        'print("REVERSE_CONTAINMENT_SEARCH_BOUND=64");',
        'if(OPEN_UNIT_NF!=0 && reverse_found_count!=size(OPEN_SB)){ print("REVERSE_CONTAINMENT_WITNESS_SEARCH_EXHAUSTED_NO_VERDICT=1"); quit; }',
    ])
    power_declaration = ("poly EMPTY_CERT_POWER=1; poly EMPTY_CERT_NF=1; "
                         "int empty_cert_found=0; int empty_cert_exponent=-1; int ek;")
    script = replace_once(script, power_declaration,
                          reverse_block + "\n" + power_declaration,
                          "reverse-containment-block")
    power_loop = ("for(ek=0;ek<=256;ek=ek+1){ if(empty_cert_found==0){ "
                  "EMPTY_CERT_NF=reduce(EMPTY_CERT_POWER,NODE_SB); "
                  "if(EMPTY_CERT_NF==0){ empty_cert_found=1; empty_cert_exponent=ek; } "
                  "else { EMPTY_CERT_POWER=reduce(EMPTY_CERT_POWER*DELTA_NODE_NF,NODE_SB); } } }")
    gated_loop = ("if(OPEN_UNIT_NF==0){ " + power_loop + " }\n"
                  'print("EMPTY_BRANCH_POWER_SEARCH_ENTERED="+string(OPEN_UNIT_NF==0));')
    script = replace_once(script, power_loop, gated_loop,
                          "gated-empty-power-search")
    return script


def validate_saturation_script(script: str, node: int, generator_count: int,
                               scanned_delta: str) -> None:
    if sha256_text(scanned_delta) == DELTA_NODE1_SHA256:
        raise RuntimeError("SATURATION_DELTA_IS_SETTLED_NODE1_DELTA")
    required = (
        f"NODE_INDEX={node}",
        f"NODE_GENERATOR_COUNT={generator_count}",
        "SATURATION_OBJECT_TYPE=",
        "SATURATION_OBJECT_SIZE=",
        "SATURATION_SLOT1_TYPE=",
        "SATURATION_NODE_INCLUSION_FAILURES=",
        "SATURATION_STABILITY_FAILURES=",
        "REVERSE_CONTAINMENT_ENTERED=",
        "REVERSE_CONTAINMENT_BASIS_GENERATOR_COUNT=",
        "REVERSE_CONTAINMENT_WITNESS_FOUND_COUNT=",
        "REVERSE_CONTAINMENT_MEMBERSHIP_REDUCTION_COUNT=",
        "REVERSE_CONTAINMENT_SEARCH_BOUND=64",
        "REVERSE_CONTAINMENT_WITNESS_SEARCH_EXHAUSTED_NO_VERDICT=1",
        "EMPTY_BRANCH_POWER_SEARCH_ENTERED=",
        "EMPTY_OPEN_POWER_MEMBERSHIP_CERTIFICATE=",
        "SATURATION_CERTIFICATE_COMPLETE=1",
        "OPEN_SATURATION_AND_CLOSED_SUCCESSOR_COMPLETE=1",
    )
    missing = [token for token in required if script.count(token) != 1]
    if missing:
        raise RuntimeError("SATURATION_SCRIPT_TOKEN_CENSUS:" + ",".join(missing))
    if script.count("if(OPEN_UNIT_NF==0){ for(ek=0;ek<=256;ek=ek+1){") != 1:
        raise RuntimeError("SATURATION_POWER_SEARCH_NOT_GATED")
    if script.count(RING_DECLARATION) != 1:
        raise RuntimeError("SATURATION_RING_DECLARATION_CENSUS")


def build_repaired_chart_script(r5, remaining: list[str], generators: list[str],
                                node: int, label: str, assignment: str,
                                residual: list[list[str]], rank: int,
                                rows: tuple[int, ...], cols: tuple[int, ...],
                                scanned_delta: str) -> str:
    free = 10 - rank
    identity_count = 11 * free
    kernel_entries = 105 * free
    full_count = 106 * free
    endpoint_count = free * (free + 1) // 2
    script = r5.build_chart_script(remaining, generators, node, label,
                                   assignment, residual, rank, rows, cols,
                                   scanned_delta)
    script = replace_once(
        script,
        "ideal ACTIVE_SAT_IDEAL=OPEN_SAT_RESULT[1]; ideal ACTIVE_SB=std(ACTIVE_SAT_IDEAL); poly ACTIVE_UNIT_NF=reduce(1,ACTIVE_SB);",
        "ideal ACTIVE_SAT_IDEAL=OPEN_SAT_RESULT[1]; ideal ACTIVE_SB=std(ACTIVE_SAT_IDEAL); poly ACTIVE_UNIT_NF=reduce(1,ACTIVE_SB);\n"
        f'write("NODE_{node:03d}_CHART_ACTIVE_STANDARD_BASIS.txt",string(ACTIVE_SB));',
        "chart-active-sb-artifact")
    script = replace_once(
        script,
        f"matrix Y[10][{free}];",
        f'matrix Y[10][{free}]; print("ADJUGATE_KERNEL_VECTOR_COUNT="+string(ncols(Y))); if(ncols(Y)!={free}){{ print("FATAL_ADJUGATE_KERNEL_VECTOR_CENSUS"); quit; }}',
        "kernel-vector-count")
    script = replace_once(
        script,
        "int base_change_reductions=0;",
        "int base_change_reductions=0; int residual_base_change_entry_count=0; int transform_entry_count=0; int transform_recorded_entry_count=0;",
        "base-change-counters")
    script = replace_once(
        script,
        "for(i=1;i<=11;i=i+1){ for(j=1;j<=10;j=j+1){ R[i,j]=reduce(R[i,j],ACTIVE_SB); base_change_reductions=base_change_reductions+1; } }",
        "for(i=1;i<=11;i=i+1){ for(j=1;j<=10;j=j+1){ R[i,j]=reduce(R[i,j],ACTIVE_SB); base_change_reductions=base_change_reductions+1; residual_base_change_entry_count=residual_base_change_entry_count+1; } }",
        "residual-base-change-count")
    script = replace_once(
        script,
        "for(i=1;i<=105;i=i+1){ for(j=1;j<=105;j=j+1){ C[i,j]=reduce(C[i,j],ACTIVE_SB); base_change_reductions=base_change_reductions+1; } }",
        "for(i=1;i<=105;i=i+1){ for(j=1;j<=105;j=j+1){ C[i,j]=reduce(C[i,j],ACTIVE_SB); base_change_reductions=base_change_reductions+1; transform_entry_count=transform_entry_count+1; } }\n"
        f'string CTFILE="NODE_{node:03d}_BASE_CHANGED_RIGHT_TRANSFORM.tsv"; write(CTFILE,"row|col|normal_form"); for(i=1;i<=105;i=i+1){{ for(j=1;j<=105;j=j+1){{ write(CTFILE,string(i)+"|"+string(j)+"|"+string(C[i,j])); transform_recorded_entry_count=transform_recorded_entry_count+1; }} }}',
        "transform-base-change-count")
    script = replace_once(
        script,
        'print("CHART_BASE_CHANGE_REDUCTION_COUNT="+string(base_change_reductions));\nif(base_change_reductions!=11135){ print("FATAL_CHART_BASE_CHANGE_CENSUS"); quit; }\nprint("NODE_TRANSFORM_BASE_CHANGED_TO_ACTIVE_SB=1");',
        'print("CHART_BASE_CHANGE_REDUCTION_COUNT="+string(base_change_reductions)); print("RESIDUAL_BASE_CHANGE_ENTRY_COUNT="+string(residual_base_change_entry_count)); print("RIGHT_TRANSFORM_ENTRY_COUNT="+string(transform_entry_count)); print("RIGHT_TRANSFORM_RECORDED_ENTRY_COUNT="+string(transform_recorded_entry_count));\n'
        'if(base_change_reductions!=11135 || residual_base_change_entry_count!=110 || transform_entry_count!=11025 || transform_recorded_entry_count!=11025){ print("FATAL_CHART_BASE_CHANGE_CENSUS"); quit; }\n'
        'print("FULL_RIGHT_TRANSFORM_RECONSTRUCTED=1"); print("NODE_TRANSFORM_BASE_CHANGED_TO_ACTIVE_SB=1");',
        "base-change-gates")
    script = replace_once(
        script,
        f"matrix K[105][{free}];\nfor(i=1;i<=105;i=i+1){{ for(j=1;j<=ncols(Y);j=j+1){{ CHECK=0; for(k=1;k<=10;k=k+1){{ CHECK=reduce(CHECK+C[i,95+k]*Y[k,j],ACTIVE_SB); }} K[i,j]=CHECK; }} }}",
        f"matrix K[105][{free}]; int kernel_entry_count=0;\nfor(i=1;i<=105;i=i+1){{ for(j=1;j<=ncols(Y);j=j+1){{ CHECK=0; for(k=1;k<=10;k=k+1){{ CHECK=reduce(CHECK+C[i,95+k]*Y[k,j],ACTIVE_SB); }} K[i,j]=CHECK; kernel_entry_count=kernel_entry_count+1; }} }}\n"
        f'print("LIFTED_KERNEL_ENTRY_COUNT="+string(kernel_entry_count)); if(kernel_entry_count!={kernel_entries}){{ print("FATAL_LIFTED_KERNEL_ENTRY_CENSUS"); quit; }}',
        "kernel-entry-count")
    script = replace_once(
        script,
        'print("FULL_106_ROW_KERNEL_REPLAY_COUNT="+string(full_count)); print("FULL_106_ROW_KERNEL_REPLAY_FAILURES="+string(full_failures)); if(full_failures!=0){ print("FATAL_FULL_KERNEL_REPLAY"); quit; }',
        f'print("FULL_106_ROW_KERNEL_REPLAY_COUNT="+string(full_count)); print("FULL_106_ROW_KERNEL_REPLAY_FAILURES="+string(full_failures)); if(full_count!={full_count} || full_failures!=0){{ print("FATAL_FULL_KERNEL_REPLAY"); quit; }}',
        "full-row-count")
    script = replace_once(
        script,
        "poly ENDPOINT_PLANT_BASE_RAW=K[14,1]*K[72,1]+K[1,1]*K[97,1]; poly ENDPOINT_PLANT_BASE_NF=reduce(ENDPOINT_PLANT_BASE_RAW,ACTIVE_SB); poly ENDPOINT_PLUS_ONE_PLANT_NF=reduce(ENDPOINT_PLANT_BASE_RAW+1,ACTIVE_SB); poly ENDPOINT_PLANT_AFFINE_FAILURE=reduce(ENDPOINT_PLUS_ONE_PLANT_NF-ENDPOINT_PLANT_BASE_NF-1,ACTIVE_SB);",
        "poly ENDPOINT_PLANT_BASE_RAW=K[14,1]*K[72,1]+K[1,1]*K[97,1]; poly ENDPOINT_PLANT_BASE_NF=reduce(ENDPOINT_PLANT_BASE_RAW,ACTIVE_SB); poly ENDPOINT_PLUS_ONE_PLANT_NF=reduce(ENDPOINT_PLANT_BASE_RAW+1,ACTIVE_SB); poly ENDPOINT_PLUS_TWO_PLANT_NF=reduce(ENDPOINT_PLANT_BASE_RAW+2,ACTIVE_SB); poly ENDPOINT_PLUS_ONE_AFFINE_FAILURE=reduce(ENDPOINT_PLUS_ONE_PLANT_NF-ENDPOINT_PLANT_BASE_NF-1,ACTIVE_SB); poly ENDPOINT_PLUS_TWO_AFFINE_FAILURE=reduce(ENDPOINT_PLUS_TWO_PLANT_NF-ENDPOINT_PLANT_BASE_NF-2,ACTIVE_SB);",
        "endpoint-two-shift-definition")
    script = replace_once(
        script,
        f'write("NODE_{node:03d}_ENDPOINT_PLUS_ONE_PLANT.txt","endpoint_nf|"+string(ENDPOINT_PLANT_BASE_NF)+"|plus_one_nf|"+string(ENDPOINT_PLUS_ONE_PLANT_NF)+"|affine_failure|"+string(ENDPOINT_PLANT_AFFINE_FAILURE));',
        f'write("NODE_{node:03d}_ENDPOINT_TWO_SHIFT_PLANT.txt","endpoint_nf|"+string(ENDPOINT_PLANT_BASE_NF)+"|plus_one_nf|"+string(ENDPOINT_PLUS_ONE_PLANT_NF)+"|plus_two_nf|"+string(ENDPOINT_PLUS_TWO_PLANT_NF)+"|plus_one_affine_failure|"+string(ENDPOINT_PLUS_ONE_AFFINE_FAILURE)+"|plus_two_affine_failure|"+string(ENDPOINT_PLUS_TWO_AFFINE_FAILURE));',
        "endpoint-two-shift-artifact")
    script = replace_once(
        script,
        'print("ENDPOINT_PLUS_ONE_PLANT_NF_NONZERO="+string(ENDPOINT_PLUS_ONE_PLANT_NF!=0)); print("ENDPOINT_PLUS_ONE_PLANT_AFFINE_REPLAY="+string(ENDPOINT_PLANT_AFFINE_FAILURE==0));',
        'print("ENDPOINT_PLUS_ONE_PLANT_NF_NONZERO="+string(ENDPOINT_PLUS_ONE_PLANT_NF!=0)); print("ENDPOINT_PLUS_ONE_PLANT_AFFINE_REPLAY="+string(ENDPOINT_PLUS_ONE_AFFINE_FAILURE==0)); print("ENDPOINT_PLUS_TWO_PLANT_NF_NONZERO="+string(ENDPOINT_PLUS_TWO_PLANT_NF!=0)); print("ENDPOINT_PLUS_TWO_PLANT_AFFINE_REPLAY="+string(ENDPOINT_PLUS_TWO_AFFINE_FAILURE==0)); print("ENDPOINT_TWO_SHIFT_AT_LEAST_ONE_NONZERO="+string(ENDPOINT_PLUS_ONE_PLANT_NF!=0 || ENDPOINT_PLUS_TWO_PLANT_NF!=0));',
        "endpoint-two-shift-markers")
    script = replace_once(
        script,
        'if(ENDPOINT_PLUS_ONE_PLANT_NF==0 || ENDPOINT_PLANT_AFFINE_FAILURE!=0){ print("FATAL_ENDPOINT_PLUS_ONE_PLANT"); quit; }',
        'if(ENDPOINT_PLUS_ONE_AFFINE_FAILURE!=0 || ENDPOINT_PLUS_TWO_AFFINE_FAILURE!=0 || (ENDPOINT_PLUS_ONE_PLANT_NF==0 && ENDPOINT_PLUS_TWO_PLANT_NF==0)){ print("FATAL_ENDPOINT_TWO_SHIFT_PLANT"); quit; }',
        "endpoint-two-shift-gate")
    script = replace_once(
        script,
        'print("ENDPOINT_QUADRATIC=x14*x72+x1*x97"); print("ENDPOINT_DELTA2_DENOMINATOR_CLEARED=1"); print("ENDPOINT_COEFFICIENT_COUNT="+string(endpoint_count)); print("ENDPOINT_COEFFICIENT_NF_NONZERO_COUNT="+string(endpoint_nonzero));',
        f'print("ENDPOINT_QUADRATIC=x14*x72+x1*x97"); print("ENDPOINT_DELTA2_DENOMINATOR_CLEARED=1"); print("ENDPOINT_COEFFICIENT_COUNT="+string(endpoint_count)); print("ENDPOINT_COEFFICIENT_NF_NONZERO_COUNT="+string(endpoint_nonzero)); if(endpoint_count!={endpoint_count}){{ print("FATAL_ENDPOINT_COEFFICIENT_CENSUS"); quit; }}',
        "endpoint-count-gate")
    return script


def validate_chart_script(script: str, node: int, generator_count: int,
                          rank: int, scanned_delta: str) -> None:
    if sha256_text(scanned_delta) == DELTA_NODE1_SHA256:
        raise RuntimeError("CHART_DELTA_IS_SETTLED_NODE1_DELTA")
    free = 10 - rank
    required = (
        f"NODE_INDEX={node}",
        f"NODE_GENERATOR_COUNT={generator_count}",
        "CHART_PIVOT_REDUCER=NODE_SB",
        "FULL_RIGHT_TRANSFORM_RECONSTRUCTED=1",
        "NODE_TRANSFORM_BASE_CHANGED_TO_ACTIVE_SB=1",
        "RESIDUAL_BASE_CHANGE_ENTRY_COUNT=",
        "RIGHT_TRANSFORM_ENTRY_COUNT=",
        "RIGHT_TRANSFORM_RECORDED_ENTRY_COUNT=",
        "ADJUGATE_KERNEL_VECTOR_COUNT=",
        "LIFTED_KERNEL_ENTRY_COUNT=",
        "ENDPOINT_PLUS_TWO_PLANT_NF_NONZERO=",
        "ENDPOINT_TWO_SHIFT_AT_LEAST_ONE_NONZERO=",
        f"NODE_{node:03d}_CHART_ACTIVE_STANDARD_BASIS.txt",
        "base_change_reductions!=11135",
        "transform_entry_count!=11025",
        "transform_recorded_entry_count!=11025",
        f"kernel_entry_count!={105 * free}",
        f"full_count!={106 * free}",
        f"endpoint_count!={free * (free + 1) // 2}",
        f"ncols(Y)!={free}",
        "K[14,i]*K[72,j]+K[14,j]*K[72,i]+K[1,i]*K[97,j]+K[1,j]*K[97,i]",
        "CHART_CLASSIFICATION=ENDPOINT_DEAD_ONLY_ON_D_DELTA",
        "CHART_CLASSIFICATION=RING_LEVEL_SURVIVOR_ON_CHART_PENDING_NILPOTENCE_RADICAL",
        "RECURSIVE_ENDPOINT_CHART_COMPLETE=1",
    )
    missing = [token for token in required if script.count(token) != 1]
    if missing:
        raise RuntimeError("CHART_SCRIPT_TOKEN_CENSUS:" + ",".join(missing))
    transform_marker = "NODE_TRANSFORM_BASE_CHANGED_TO_ACTIVE_SB=1"
    if "while(step" in script.split(transform_marker, 1)[1]:
        raise RuntimeError("POST_BASE_CHANGE_REPIVOT_PRESENT")
    if script.count(RING_DECLARATION) != 1:
        raise RuntimeError("CHART_RING_DECLARATION_CENSUS")


def require_count_markers(path: Path, markers: tuple[str, ...]) -> list[str]:
    lines = path.read_text(errors="strict").splitlines()
    if any(line.startswith("FATAL_") for line in lines):
        raise RuntimeError(f"FATAL_MARKER_IN_STAGE_STDOUT:{path.name}")
    bad = [marker for marker in markers if lines.count(marker) != 1]
    if bad:
        raise RuntimeError(f"STAGE_MARKER_CENSUS:{path.name}:{','.join(bad)}")
    return lines


class JobBinding:
    """The exact one-job binding, read fail-closed from the environment."""

    REQUIRED = ("JOB_TAG", "JOB_NONCE", "JOB_CONTAINMENT_PGID",
                "JOB_CONTAINMENT_SID", "LEASE_FILE", "SOURCE_ARCHIVE_PATH",
                "EXPECTED_SOURCE_ARCHIVE_SHA256", "EXPECTED_SINGULAR_SHA256",
                "SUPERVISOR_PID", "SUPERVISOR_STARTTIME", "WORKER_PID",
                "WORKER_STARTTIME")

    def __init__(self) -> None:
        values = {name: os.environ.get(name) for name in self.REQUIRED}
        if any(not value for value in values.values()):
            missing = sorted(name for name, value in values.items()
                             if not value)
            raise SystemExit("MISSING_CONTAINMENT_ENVIRONMENT:"
                             + ",".join(missing))
        self.job_tag = values["JOB_TAG"]
        self.job_nonce = values["JOB_NONCE"]
        if not NONCE_RE.fullmatch(self.job_nonce):
            raise SystemExit("BAD_JOB_NONCE_SCHEMA")
        if not self.job_tag.endswith("_" + self.job_nonce):
            raise SystemExit("JOB_TAG_NONCE_DISAGREEMENT")
        self.pgid = values["JOB_CONTAINMENT_PGID"]
        self.sid = values["JOB_CONTAINMENT_SID"]
        self.lease_file = Path(values["LEASE_FILE"])
        if not self.lease_file.is_file():
            raise SystemExit("LEASE_FILE_MISSING")
        self.lease_sha256 = sha256(self.lease_file)
        self.source_archive = Path(values["SOURCE_ARCHIVE_PATH"])
        self.source_archive_sha256 = values["EXPECTED_SOURCE_ARCHIVE_SHA256"]
        self.singular_sha256 = values["EXPECTED_SINGULAR_SHA256"]
        for digest in (self.source_archive_sha256, self.singular_sha256):
            if not re.fullmatch(r"[0-9a-f]{64}", digest):
                raise SystemExit("BAD_BINDING_DIGEST_SCHEMA")
        self.supervisor_pid = values["SUPERVISOR_PID"]
        self.supervisor_starttime = values["SUPERVISOR_STARTTIME"]
        self.worker_pid = values["WORKER_PID"]
        self.worker_starttime = values["WORKER_STARTTIME"]

    def summary_block(self) -> dict[str, object]:
        return {
            "job_nonce": self.job_nonce,
            "job_tag": self.job_tag,
            "lease_sha256": self.lease_sha256,
            "singular_sha256": self.singular_sha256,
            "source_archive_sha256": self.source_archive_sha256,
            "supervisor": {"pid": int(self.supervisor_pid),
                           "starttime": int(self.supervisor_starttime)},
            "worker": {"pid": int(self.worker_pid),
                       "starttime": int(self.worker_starttime)},
        }


class Recursor:
    def __init__(self, args, r5, gate):
        self.args = args
        self.r5 = r5
        self.gate = gate
        self.case_dir = args.case_dir.resolve()
        self.output = args.output.resolve()
        self.prepared = args.prepared.resolve()
        self.build = args.build.resolve()
        self.binding = JobBinding()
        self.stage_records: list[dict[str, object]] = []

    def run_stage(self, label: str, script: Path, cwd: Path, cap: int,
                  node: object) -> Path:
        binding = self.binding
        stdout = cwd / f"{label}.stdout.txt"
        stderr = cwd / f"{label}.stderr.txt"
        result = cwd / f"{label}.result.json"
        identity = cwd / f"{label}.identity.json"
        command = [
            sys.executable, str(self.case_dir / "run_singular_stage.py"),
            "--singular", str(self.args.singular),
            "--script", str(script), "--cwd", str(cwd),
            "--stdout", str(stdout), "--stderr", str(stderr),
            "--result", str(result), "--identity", str(identity),
            "--cap-seconds", str(cap),
            "--expected-pgid", str(binding.pgid),
            "--expected-sid", str(binding.sid),
            "--job-tag", binding.job_tag,
            "--job-nonce", binding.job_nonce,
            "--stage-label", label,
            "--lease", str(binding.lease_file),
            "--source-archive", str(binding.source_archive),
            "--source-archive-sha256", binding.source_archive_sha256,
            "--singular-sha256", binding.singular_sha256,
            "--supervisor-pid", str(binding.supervisor_pid),
            "--supervisor-starttime", str(binding.supervisor_starttime),
            "--worker-pid", str(binding.worker_pid),
            "--worker-starttime", str(binding.worker_starttime),
        ]
        completed = subprocess.run(command, check=False,
                                   capture_output=True, text=True)
        (cwd / f"{label}.runner.stdout.txt").write_text(completed.stdout)
        (cwd / f"{label}.runner.stderr.txt").write_text(completed.stderr)
        if not result.is_file():
            raise RuntimeError(f"STAGE_RESULT_MISSING:{label}")
        payload = json.loads(result.read_text())
        if sorted(payload) != sorted(
                STAGE_RESULT_BINDING_KEYS + ("elapsed_seconds",)):
            raise RuntimeError(f"STAGE_RESULT_KEY_CENSUS:{label}")
        expected_binding = {
            "cap_seconds": cap,
            "expected_pgid": int(binding.pgid),
            "expected_sid": int(binding.sid),
            "job_nonce": binding.job_nonce,
            "job_tag": binding.job_tag,
            "lease_sha256": binding.lease_sha256,
            "singular_sha256": binding.singular_sha256,
            "source_archive_sha256": binding.source_archive_sha256,
            "stage_label": label,
            "supervisor_starttime": int(binding.supervisor_starttime),
            "worker_starttime": int(binding.worker_starttime),
        }
        for key, expected in expected_binding.items():
            if payload.get(key) != expected:
                raise RuntimeError(f"STAGE_RESULT_BINDING_DRIFT:{label}:{key}")
        if not identity.is_file():
            raise RuntimeError(f"STAGE_IDENTITY_MISSING:{label}")
        if payload.get("identity_sha256") != sha256(identity):
            raise RuntimeError(f"STAGE_IDENTITY_HASH_DISAGREEMENT:{label}")
        record = {
            "node": node,
            "stage": label,
            "returncode": payload.get("returncode"),
            "timed_out": payload.get("timed_out"),
            "script_sha256": payload.get("script_sha256"),
            "stdout_sha256": payload.get("stdout_sha256"),
            "stderr_sha256": payload.get("stderr_sha256"),
            "identity_sha256": payload.get("identity_sha256"),
            "result_sha256": sha256(result),
        }
        self.stage_records.append(record)
        if payload.get("timed_out") is True:
            raise StageTimeout(node, label)
        if completed.returncode != 0 or payload.get("returncode") != 0:
            raise RuntimeError(
                f"STAGE_RETURN_CODE:{label}:{completed.returncode}:"
                f"{payload.get('returncode')}")
        if payload.get("script_sha256") != sha256(script):
            raise RuntimeError(f"STAGE_SCRIPT_HASH_DISAGREEMENT:{label}")
        self.gate.assert_clean_transcript(stdout, stderr)
        return stdout

    def write_summary(self, classification: str, nodes: list[dict[str, object]],
                      generators: list[str], rank_bound: int,
                      no_verdict_reason: str | None = None) -> None:
        summary = {
            "classification": classification,
            "component": "triple02",
            "closed_successor_of_node": 1,
            "start_node": 2,
            "nodes": nodes,
            "open_remainder_generators": generators,
            "open_remainder_generator_sha256": [
                sha256_text(value) for value in generators],
            "open_remainder_rank_upper_bound": rank_bound,
            "endpoint": "x14*x72+x1*x97",
            "scope": ("EXACT_AMBIENT_QUOTIENT_NF_FINITE_CHART_RECURSION_"
                      "ON_TRIPLE02_NODE1_CLOSED_SUCCESSOR_ONLY"),
            "settled_open_route": "NEVER_REENTERED",
            "settled_open_verdict": "EXACT_ENDPOINT_DEAD_ON_NODE1_PROPER_OPEN_ONLY",
            "delta_node1_sha256": DELTA_NODE1_SHA256,
            "no_radical_nilpotence_or_geometric_inference": True,
            "whole_component_or_jc2_inference": False,
            "job_binding": self.binding.summary_block(),
            "stage_records": self.stage_records,
        }
        if no_verdict_reason is not None:
            summary["no_verdict_reason"] = no_verdict_reason
        (self.output / "SUMMARY.json").write_text(
            json.dumps(summary, indent=2, sort_keys=True) + "\n")
        (self.output / "VERDICT.txt").write_text(classification + "\n")

    def replay_witness(self, remaining, generators, label, assignment,
                       delta) -> None:
        witness_dir = self.output / "witness_replay"
        witness_dir.mkdir()
        expected_script = (self.build / "TRIPLE02_NODE1_WITNESS_REPLAY.sing")
        build_manifest = json.loads(
            (self.build / "BUILD_MANIFEST.json").read_text())
        if sha256(expected_script) != build_manifest[
                "generated_witness_replay_sha256"]:
            raise RuntimeError("WITNESS_REPLAY_SCRIPT_HASH_DRIFT")
        script = witness_dir / "witness_replay.sing"
        script.write_text(expected_script.read_text())
        if sha256(script) != build_manifest["generated_witness_replay_sha256"]:
            raise RuntimeError("WITNESS_REPLAY_SCRIPT_COPY_DRIFT")
        stdout = self.run_stage("witness_replay", script, witness_dir,
                                self.args.fast_cap, "witness")
        lines = require_count_markers(stdout, WITNESS_REPLAY_MARKERS)
        if sum(line in lines for line in
               ("CLOSED_SUCCESSOR_EMPTY=0", "CLOSED_SUCCESSOR_EMPTY=1")) != 1:
            raise RuntimeError("CLOSED_SUCCESSOR_EMPTY_MARKER_CENSUS")
        produced_sb = (witness_dir / "NODE_001_STANDARD_BASIS.txt").read_bytes()
        archived_sb = (self.prepared
                       / "r3/output/node_001/NODE_001_STANDARD_BASIS.txt"
                       ).read_bytes()
        require_archived_append_copies(
            produced_sb, archived_sb, ARCHIVED_NODE1_SB_APPEND_COUNT,
            "NODE_001_STANDARD_BASIS")
        for produced, archived in (
                ("NODE_001_REDUCE_PIVOTS.tsv",
                 "r3/output/node_001/NODE_001_REDUCE_PIVOTS.tsv"),
                ("NODE_001_REDUCE_RESIDUAL.tsv",
                 "r3/output/node_001/NODE_001_REDUCE_RESIDUAL.tsv")):
            if (witness_dir / produced).read_bytes() != (
                    self.prepared / archived).read_bytes():
                raise RuntimeError(f"WITNESS_REPLAY_BYTE_DISAGREEMENT:{produced}")

    def run(self) -> int:
        r5 = self.r5
        self.output.mkdir(parents=True, exist_ok=False)
        resume_input = json.loads(
            (self.build / "RESUME_NODE_INPUT.json").read_text())
        generators = [r5.clean_poly(value)
                      for value in resume_input["generators"]]
        if (resume_input.get("node") != 2
                or resume_input.get("inherited_rank_upper_bound") != 6
                or resume_input.get("closed_successor_of_node") != 1
                or len(generators) != 3
                or tuple(sha256_text(value) for value in generators)
                != GENERATOR_SHA256
                or tuple(resume_input.get("generator_sha256", []))
                != GENERATOR_SHA256):
            raise SystemExit("RESUME_NODE_INPUT_DRIFT")
        base = self.prepared / "r3/work/base"
        label, zeros, factor, remaining, assignment, counts = r5.source_inputs(
            base, "triple02")
        if (label != "TRIPLE02" or remaining != ["q0", "q2", "c4", "c6"]
                or r5.clean_poly(factor) != generators[0]):
            raise SystemExit("RESUME_SOURCE_RECONSTRUCTION_DRIFT")
        rank_provenance = r5.verify_rank_bound(base, "triple02", 6)
        if rank_provenance != resume_input.get("inherited_rank_provenance"):
            raise SystemExit("RESUME_RANK_PROVENANCE_DRIFT")
        delta_node1 = generators[2]
        node2_expected = (self.build / "NODE_002_REDUCE_EXPECTED.sing")
        if r5.build_reduce_script(remaining, generators, 2, label,
                                  assignment) != node2_expected.read_text():
            raise SystemExit("NODE2_REDUCE_DETERMINISM_DRIFT")
        rank_bound = 6
        nodes: list[dict[str, object]] = []
        try:
            self.replay_witness(remaining, generators[:2], label, assignment,
                                delta_node1)
            final_node = self.args.start_node + self.args.max_nodes - 1
            for node_index in range(self.args.start_node, final_node + 1):
                node = self.output / f"node_{node_index:03d}"
                node.mkdir()
                (node / "NODE_INPUT.json").write_text(json.dumps({
                    "node": node_index,
                    "generators": generators,
                    "generator_sha256": [sha256_text(g) for g in generators],
                    "inherited_rank_upper_bound": rank_bound,
                    "closed_successor_of_node": node_index - 1,
                }, indent=2, sort_keys=True) + "\n")
                reduce_script = node / "reduce.sing"
                reduce_text = r5.build_reduce_script(
                    remaining, generators, node_index, label, assignment)
                if node_index == 2 and reduce_text != node2_expected.read_text():
                    raise RuntimeError("NODE2_REDUCE_REGENERATION_DRIFT")
                reduce_script.write_text(reduce_text)
                reduce_stdout = self.run_stage(
                    "reduce", reduce_script, node, self.args.slow_cap,
                    node_index)
                reduce_lines = reduce_stdout.read_text(
                    errors="strict").splitlines()
                if "EXACT_EMPTY_NODE=1" in reduce_lines:
                    nodes.append({"node": node_index,
                                  "classification": "EXACT_EMPTY_NODE",
                                  "rank_upper_bound_in": rank_bound})
                    self.write_summary(CLASS_DEAD, nodes, generators,
                                       rank_bound)
                    return 0
                require_count_markers(reduce_stdout, (
                    f"NODE_INDEX={node_index}",
                    f"NODE_GENERATOR_COUNT={len(generators)}",
                    "NODE_EMPTY=0",
                    "NODE_REDUCER_FIXTURES_PASS=1",
                    "NF_RATIONAL_UNIT_PIVOT_COUNT=95",
                    "NF_PIVOT_INVARIANT_FAILURES=0",
                    "NODE_RESIDUAL_REDUCTION_COMPLETE=1",
                    "NODE_REDUCE_COMPLETE=1",
                ))
                residual = r5.read_residual(
                    node / f"NODE_{node_index:03d}_REDUCE_RESIDUAL.tsv")
                rank = -1
                witness_path: Path | None = None
                size_results = []
                for size in range(rank_bound, -1, -1):
                    rank_script = node / f"rank_size_{size}.sing"
                    census_path = node / f"rank_size_{size}.support.json"
                    rank_script.write_text(r5.build_rank_size_script(
                        remaining, generators, node_index, residual, size,
                        census_path))
                    stdout = self.run_stage(
                        f"rank_size_{size}", rank_script, node,
                        self.args.slow_cap, node_index)
                    lines = require_count_markers(stdout, (
                        f"RANK_SIZE={size}",
                        "SUPPORT_REPLAY_FAILURES=0",
                        "RANK_SIZE_CENSUS_COMPLETE=1",
                    ))
                    found = "RANK_SIZE_WITNESS_FOUND=1" in lines
                    size_results.append({
                        "size": size, "witness_found": found,
                        "support": json.loads(census_path.read_text())})
                    if found:
                        rank = size
                        witness_path = (
                            node / f"NODE_{node_index:03d}_SIZE_{size}_WITNESS.tsv")
                        break
                    if "EVERY_MATCHABLE_MINOR_AT_SIZE_NF_ZERO=1" not in lines:
                        raise RuntimeError(
                            f"MISSING_ZERO_SIZE_CERTIFICATE:{size}")
                if rank < 0 or witness_path is None:
                    raise RuntimeError("NO_RANK_WITNESS")
                rows, cols, scanned_delta = r5.read_witness(witness_path, rank)
                if sha256_text(scanned_delta) == DELTA_NODE1_SHA256:
                    raise RuntimeError("NODE_DELTA_IS_SETTLED_NODE1_DELTA")
                if scanned_delta in generators:
                    raise RuntimeError("NODE_DELTA_COLLIDES_WITH_GENERATOR")
                saturation_script = node / "saturation.sing"
                saturation_text = build_repaired_saturation_script(
                    r5, remaining, generators, node_index, scanned_delta)
                validate_saturation_script(
                    saturation_text, node_index, len(generators), scanned_delta)
                saturation_script.write_text(saturation_text)
                saturation_stdout = self.run_stage(
                    "saturation", saturation_script, node,
                    self.args.slow_cap, node_index)
                saturation_lines = saturation_stdout.read_text(
                    errors="strict").splitlines()
                if ("REVERSE_CONTAINMENT_WITNESS_SEARCH_EXHAUSTED_NO_VERDICT=1"
                        in saturation_lines):
                    raise ReverseExhausted(node_index)
                require_count_markers(saturation_stdout, (
                    "NODE_REDUCER_FIXTURES_PASS=1",
                    "SATURATION_OBJECT_TYPE=list",
                    "SATURATION_OBJECT_SIZE=1",
                    "SATURATION_SLOT1_TYPE=ideal",
                    "SATURATION_NODE_INCLUSION_FAILURES=0",
                    "SATURATION_STABILITY_FAILURES=0",
                    "REVERSE_CONTAINMENT_SEARCH_BOUND=64",
                    "SATURATION_CERTIFICATE_COMPLETE=1",
                    "OPEN_SATURATION_AND_CLOSED_SUCCESSOR_COMPLETE=1",
                ))
                if sum(line in saturation_lines for line in
                       ("OPEN_CHART_EMPTY=0", "OPEN_CHART_EMPTY=1")) != 1:
                    raise RuntimeError("OPEN_CHART_EMPTY_MARKER_CENSUS")
                if sum(line in saturation_lines for line in
                       ("NEXT_REMAINDER_EMPTY=0",
                        "NEXT_REMAINDER_EMPTY=1")) != 1:
                    raise RuntimeError("NEXT_REMAINDER_EMPTY_MARKER_CENSUS")
                open_empty = "OPEN_CHART_EMPTY=1" in saturation_lines
                next_empty = "NEXT_REMAINDER_EMPTY=1" in saturation_lines
                if open_empty:
                    require_count_markers(saturation_stdout, (
                        "EMPTY_OPEN_POWER_MEMBERSHIP_CERTIFICATE=1",
                        "PROPER_OPEN_IDEAL_CERTIFICATE=0",
                        "EMPTY_BRANCH_POWER_SEARCH_ENTERED=1",
                        "REVERSE_CONTAINMENT_ENTERED=0",
                    ))
                else:
                    require_count_markers(saturation_stdout, (
                        "EMPTY_OPEN_POWER_MEMBERSHIP_CERTIFICATE=0",
                        "PROPER_OPEN_IDEAL_CERTIFICATE=1",
                        "EMPTY_BRANCH_POWER_SEARCH_ENTERED=0",
                        "REVERSE_CONTAINMENT_ENTERED=1",
                    ))
                empty_open_certificate = r5.validate_empty_open_certificate(
                    node / (f"NODE_{node_index:03d}_EMPTY_OPEN_POWER_"
                            "CERTIFICATE.txt"),
                    open_empty)
                node_result = {
                    "node": node_index,
                    "rank": rank,
                    "rank_upper_bound_in": rank_bound,
                    "rank_size_results": size_results,
                    "delta": scanned_delta,
                    "delta_sha256": sha256_text(scanned_delta),
                    "delta_is_settled_node1_delta": False,
                    "open_chart_empty_by_saturation": open_empty,
                    "empty_open_power_certificate": empty_open_certificate,
                    "next_remainder_empty": next_empty,
                }
                if open_empty:
                    node_result.update({"endpoint_nonzero": False,
                                        "endpoint_dead": False})
                    nodes.append(node_result)
                    (node / "NODE_RESULT.json").write_text(
                        json.dumps(node_result, indent=2, sort_keys=True) + "\n")
                    if next_empty:
                        self.write_summary(CLASS_DEAD, nodes,
                                           generators + [scanned_delta], rank)
                        return 0
                    generators = generators + [scanned_delta]
                    rank_bound = rank
                    continue
                chart_script = node / "chart.sing"
                chart_text = build_repaired_chart_script(
                    r5, remaining, generators, node_index, label, assignment,
                    residual, rank, rows, cols, scanned_delta)
                validate_chart_script(chart_text, node_index, len(generators),
                                      rank, scanned_delta)
                chart_script.write_text(chart_text)
                chart_stdout = self.run_stage(
                    "chart", chart_script, node, self.args.slow_cap,
                    node_index)
                free = 10 - rank
                chart_lines = require_count_markers(chart_stdout, (
                    "NODE_REDUCER_FIXTURES_PASS=1",
                    "CHART_SATURATION_OBJECT_TYPE=list",
                    "CHART_SATURATION_OBJECT_SIZE=1",
                    "CHART_SATURATION_SLOT1_TYPE=ideal",
                    "CHART_SATURATION_NODE_INCLUSION_FAILURES=0",
                    "CHART_SATURATION_STABILITY_FAILURES=0",
                    "CHART_OPEN_PROPER_IDEAL_CERTIFICATE=1",
                    "OPEN_CHART_SATURATION_PROPER=1",
                    "CHART_PIVOT_REDUCER=NODE_SB",
                    "CHART_BASE_CHANGE_REDUCTION_COUNT=11135",
                    "RESIDUAL_BASE_CHANGE_ENTRY_COUNT=110",
                    "RIGHT_TRANSFORM_ENTRY_COUNT=11025",
                    "RIGHT_TRANSFORM_RECORDED_ENTRY_COUNT=11025",
                    "FULL_RIGHT_TRANSFORM_RECONSTRUCTED=1",
                    "NODE_TRANSFORM_BASE_CHANGED_TO_ACTIVE_SB=1",
                    "NF_RATIONAL_UNIT_PIVOT_COUNT=95",
                    "NF_PIVOT_INVARIANT_FAILURES=0",
                    f"ADJUGATE_KERNEL_VECTOR_COUNT={free}",
                    "CHART_DELTA_NF_NONZERO=1",
                    "SCANNED_DELTA_REPLAY_EQUAL=1",
                    f"COMPLETE_BORDERED_IDENTITY_COUNT={11 * free}",
                    "BORDERED_IDENTITY_FAILURES=0",
                    "BORDERED_NONZERO_PLANT_NF_NONZERO=1",
                    "BORDERED_NONZERO_PLANT_EQUALS_DELTA=1",
                    f"FULL_106_ROW_KERNEL_REPLAY_COUNT={106 * free}",
                    "FULL_106_ROW_KERNEL_REPLAY_FAILURES=0",
                    f"LIFTED_KERNEL_ENTRY_COUNT={105 * free}",
                    "ENDPOINT_PLUS_ONE_PLANT_AFFINE_REPLAY=1",
                    "ENDPOINT_PLUS_TWO_PLANT_AFFINE_REPLAY=1",
                    "ENDPOINT_TWO_SHIFT_AT_LEAST_ONE_NONZERO=1",
                    "ENDPOINT_QUADRATIC=x14*x72+x1*x97",
                    "ENDPOINT_DELTA2_DENOMINATOR_CLEARED=1",
                    f"ENDPOINT_COEFFICIENT_COUNT={free * (free + 1) // 2}",
                    "NO_FACTOR_GCD_CONTENT_RADICAL_NORMALIZATION=1",
                    "RECURSIVE_ENDPOINT_CHART_COMPLETE=1",
                ))
                chart_active = node / (
                    f"NODE_{node_index:03d}_CHART_ACTIVE_STANDARD_BASIS.txt")
                saturation_open = node / (
                    f"NODE_{node_index:03d}_OPEN_SAT_STANDARD_BASIS.txt")
                if chart_active.read_bytes() != saturation_open.read_bytes():
                    raise RuntimeError("CHART_SATURATION_ACTIVE_SB_DISAGREEMENT")
                dead_marker = "CHART_CLASSIFICATION=ENDPOINT_DEAD_ONLY_ON_D_DELTA"
                survivor_marker = ("CHART_CLASSIFICATION=RING_LEVEL_SURVIVOR_"
                                   "ON_CHART_PENDING_NILPOTENCE_RADICAL")
                if (chart_lines.count(dead_marker)
                        + chart_lines.count(survivor_marker)) != 1:
                    raise RuntimeError("ENDPOINT_CLASSIFICATION_MARKER_CENSUS")
                endpoint_dead = dead_marker in chart_lines
                endpoint_nonzero = survivor_marker in chart_lines
                delta_path = node / f"NODE_{node_index:03d}_CHART_DELTA.txt"
                saturated_delta = r5.clean_poly(delta_path.read_text())
                node_result.update({
                    "saturated_delta_normal_form": saturated_delta,
                    "saturated_delta_file_sha256": sha256(delta_path),
                    "endpoint_nonzero": endpoint_nonzero,
                    "endpoint_dead": endpoint_dead,
                })
                nodes.append(node_result)
                (node / "NODE_RESULT.json").write_text(
                    json.dumps(node_result, indent=2, sort_keys=True) + "\n")
                if endpoint_nonzero:
                    self.write_summary(CLASS_SURVIVOR, nodes, generators, rank)
                    return 0
                if not endpoint_dead:
                    raise RuntimeError("ENDPOINT_CLASSIFICATION_MISSING")
                if next_empty:
                    self.write_summary(CLASS_DEAD, nodes,
                                       generators + [scanned_delta], rank)
                    return 0
                generators = generators + [scanned_delta]
                rank_bound = rank
            self.write_summary(
                CLASS_NO_VERDICT, nodes, generators, rank_bound,
                no_verdict_reason=f"MAX_NODES_EXHAUSTED:{final_node}")
            return 0
        except StageTimeout as timeout:
            self.write_summary(
                CLASS_NO_VERDICT, nodes, generators, rank_bound,
                no_verdict_reason=(
                    f"STAGE_TIMEOUT:{timeout.node}:{timeout.stage}"))
            return 0
        except ReverseExhausted as exhausted:
            self.write_summary(
                CLASS_REVERSE, nodes, generators, rank_bound,
                no_verdict_reason=(
                    f"REVERSE_CONTAINMENT_EXHAUSTED:{exhausted.node}"))
            return 0
        except Exception as exc:
            (self.output / "ADAPTER_FAILURE.txt").write_text(
                f"{type(exc).__name__}:{exc}\n")
            self.write_summary(CLASS_ADAPTER, nodes, generators, rank_bound,
                               no_verdict_reason="ADAPTER_EXCEPTION")
            return 2


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--prepared", required=True, type=Path)
    parser.add_argument("--build", required=True, type=Path)
    parser.add_argument("--frozen-r5-source", required=True, type=Path)
    parser.add_argument("--case-dir", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--singular", required=True, type=Path)
    parser.add_argument("--start-node", type=int, default=2)
    parser.add_argument("--max-nodes", type=int, default=6)
    parser.add_argument("--fast-cap", type=int, default=900)
    parser.add_argument("--slow-cap", type=int, default=3600)
    args = parser.parse_args()
    if args.start_node != 2:
        raise SystemExit("START_NODE_MUST_BE_2")
    if not 1 <= args.max_nodes <= 12:
        raise SystemExit("MAX_NODES_OUT_OF_PREREGISTERED_RANGE")
    if args.fast_cap <= 0 or args.slow_cap <= 0:
        raise SystemExit("NONPOSITIVE_STAGE_CAP")
    r5 = load_pinned("frozen_r5_recursor",
                     args.frozen_r5_source.resolve(), FROZEN_R5_SHA256,
                     with_parent_path=True)
    gate = load_pinned(
        "frozen_transcript_gate",
        args.frozen_r5_source.resolve().parent / "transcript_gate.py",
        TRANSCRIPT_GATE_SHA256)
    recursor = Recursor(args, r5, gate)
    return recursor.run()


if __name__ == "__main__":
    raise SystemExit(main())
