#!/usr/bin/env python3
"""Validate and tabulate the sharpened D <= 200 NONRES census.

The Moh rows are regenerated from the charged frozen ``moh_skeleton_full.py``.
The membership of the upstream POLY/ODE + sharpened-Xu-screen cohort is read
from ``box/xufloor-20260903/results.json``; that JSON is *not* a charged input
to the current lane, so the driver prints its digest and keeps this provenance
boundary explicit.  Every selected JSON row is checked byte-for-byte at the
integer-tuple level against a row regenerated by the frozen Moh enumerator.

No CAS and no parallelism are used.  The script writes only the bounded
summary/TSV/manifest artifacts in ``box/h1nonres-20260903``.
"""

from __future__ import annotations

import collections
import hashlib
import importlib.util
import json
from fractions import Fraction
from math import gcd
from pathlib import Path


CHARGED_MOH = Path("/tmp/jc2-lane.7wKvYN/inputs/moh_skeleton_full.py")
SCREEN_RESULTS = Path("box/xufloor-20260903/results.json")
OUTDIR = Path("box/h1nonres-20260903")
CHARGED_MOH_SHA256 = "d20bf0841a1ba2b229d423bb948e6c4474a4f5a83f55148071cae39cb6c506c2"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def load_moh():
    spec = importlib.util.spec_from_file_location("charged_moh_skeleton_full", CHARGED_MOH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {CHARGED_MOH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def row_key(record: dict) -> tuple:
    values = tuple(sorted((int(index), int(value)) for index, value in record["V"].items()))
    return record["n"], record["m"], tuple(record["M"]), values


def group_key(record: dict) -> tuple:
    return record["n"], record["m"], tuple(record["M"]), record["V_s"]


def strict_orders(us: int, vs: int) -> tuple[Fraction, ...]:
    """Reduced a/b with 1 < a/b < vs/us and 1 <= b <= us."""
    values = set()
    for denominator in range(1, us + 1):
        for numerator in range(denominator + 1, vs * denominator // us + 1):
            if numerator * us >= vs * denominator:
                continue
            if gcd(numerator, denominator) == 1:
                values.add(Fraction(numerator, denominator))
    return tuple(sorted(values))


def fstr(value: Fraction) -> str:
    return str(value.numerator) if value.denominator == 1 else f"{value.numerator}/{value.denominator}"


def sequence_text(values) -> str:
    return ",".join(map(str, values)) or "-"


def write_tsv(name: str, header: tuple[str, ...], rows) -> Path:
    path = OUTDIR / name
    material = ["\t".join(header)]
    material.extend("\t".join(map(str, row)) for row in rows)
    path.write_text("\n".join(material) + "\n")
    return path


def nonres(us: int, vs: int) -> tuple[bool, bool, tuple[int, ...]]:
    ds = us + vs
    common = gcd(us, vs)
    resonant = tuple(j for j in range(1, vs + 1) if us * j % ds == 0)
    direct = not resonant
    inequality = us > (common - 1) * vs
    return direct, inequality, resonant


def main() -> None:
    moh_digest = sha256(CHARGED_MOH)
    assert moh_digest == CHARGED_MOH_SHA256, moh_digest
    print(f"charged_moh_sha256={moh_digest}")
    print(f"screen_results_sha256={sha256(SCREEN_RESULTS)}")

    mf = load_moh()
    regenerated = {}
    for degree in range(48, 201):
        for m, Ms, V in mf.census(degree, Kmin=16, full=True):
            key = degree, m, tuple(Ms), tuple(sorted(V.items()))
            assert key not in regenerated
            regenerated[key] = mf.Skel(degree, m, list(Ms), V)

    raw_us_rows = []
    raw_us_groups = {}
    for key, skel in regenerated.items():
        us = skel.d[skel.s] - skel.V[skel.s]
        vs = skel.V[skel.s]
        if us < 2:
            continue
        status = nonres(us, vs)[0]
        raw_us_rows.append(status)
        raw_us_groups[(key[0], key[1], key[2], vs)] = status

    source = json.loads(SCREEN_RESULTS.read_text())
    poly_ode_us_rows = [record for record in source["rows"] if record["phase"] == "us_gt_1"]
    poly_ode_us_groups = {}
    for record in poly_ode_us_rows:
        key = group_key(record)
        status = nonres(record["u_s"], record["V_s"])[0]
        if key in poly_ode_us_groups:
            assert poly_ode_us_groups[key] == status
        poly_ode_us_groups[key] = status
    selected = [
        record
        for record in poly_ode_us_rows
        if record["xu_ok_candidate"]
    ]
    selected_keys = [row_key(record) for record in selected]
    assert len(selected_keys) == len(set(selected_keys))
    for record, key in zip(selected, selected_keys):
        assert key in regenerated, key
        skel = regenerated[key]
        expected_group = group_key(record)
        assert record["row_key"] == str(key)
        assert record["group_key"] == str(expected_group)
        assert skel.s == record["s"]
        assert skel.V[skel.s] == record["V_s"]
        assert skel.d[skel.s] - skel.V[skel.s] == record["u_s"]
        assert skel.windows_ok() and skel.full_ok()

    groups = collections.defaultdict(list)
    for record in selected:
        groups[group_key(record)].append(record)

    info = {}
    for key, records in groups.items():
        us = records[0]["u_s"]
        vs = records[0]["V_s"]
        assert all(record["u_s"] == us and record["V_s"] == vs for record in records)
        direct, inequality, resonant = nonres(us, vs)
        assert direct == inequality
        info[key] = {
            "us": us,
            "vs": vs,
            "ds": us + vs,
            "g": gcd(us, vs),
            "nonres": direct,
            "resonant": resonant,
            "orders": strict_orders(us, vs),
            "rows": len(records),
            "s": records[0]["s"],
        }

    assert len(regenerated) == 23720
    assert (len(raw_us_rows), sum(raw_us_rows)) == (6117, 4389)
    assert (len(raw_us_groups), sum(raw_us_groups.values())) == (4012, 2896)
    assert len(source["rows"]) == 1420
    assert len(poly_ode_us_rows) == 310
    assert (len(poly_ode_us_groups), sum(poly_ode_us_groups.values())) == (177, 129)
    assert len(selected) == 296
    assert len(groups) == 166
    assert sum(len(data["orders"]) for data in info.values()) == 274
    assert collections.Counter(data["us"] for data in info.values()) == {2: 136, 3: 23, 4: 5, 5: 2}
    assert collections.Counter(data["nonres"] for data in info.values()) == {True: 124, False: 42}
    assert sum(data["rows"] for data in info.values() if data["nonres"]) == 204
    assert sum(data["rows"] for data in info.values() if not data["nonres"]) == 92
    assert sum(len(data["orders"]) for data in info.values() if data["nonres"]) == 192
    assert sum(len(data["orders"]) for data in info.values() if not data["nonres"]) == 82

    print("raw_frozen_rows=23720")
    print("raw_frozen_us_ge_2_rows=6117")
    print("raw_frozen_us_ge_2_rows_nonres_true_false=4389,1728")
    print("raw_frozen_us_ge_2_groups=4012")
    print("raw_frozen_us_ge_2_groups_nonres_true_false=2896,1116")
    print("upstream_poly_ode_rows=1420")
    print("upstream_us_ge_2_rows=310")
    print("upstream_us_ge_2_groups=177")
    print("upstream_us_ge_2_groups_nonres_true_false=129,48")
    print("sharpened_rows=296")
    print("sharpened_groups=166")
    print("strict_order_pairs=274")
    print("nonres_groups_true_false=124,42")
    print("nonres_rows_true_false=204,92")
    print("nonres_pairs_true_false=192,82")
    print("groups_with_without_strict_orders=%d,%d" % (
        sum(bool(data["orders"]) for data in info.values()),
        sum(not data["orders"] for data in info.values()),
    ))

    print("\nBY_D")
    print("D|groups_T|groups_F|rows_T|rows_F|pairs_T|pairs_F")
    for degree in sorted({key[0] for key in groups}):
        keys = [key for key in groups if key[0] == degree]
        counts = []
        for status in (True, False):
            counts.extend((
                sum(info[key]["nonres"] == status for key in keys),
                sum(info[key]["rows"] for key in keys if info[key]["nonres"] == status),
                sum(len(info[key]["orders"]) for key in keys if info[key]["nonres"] == status),
            ))
        # counts is T groups/rows/pairs followed by F groups/rows/pairs.
        print(f"{degree}|{counts[0]}|{counts[3]}|{counts[1]}|{counts[4]}|{counts[2]}|{counts[5]}")

    print("\nBY_CELL")
    print("u_s|v_s|d_s|g|NONRES|groups|rows|pairs|strict_orders")
    cells = collections.defaultdict(list)
    for key, data in info.items():
        cells[(data["us"], data["vs"], data["nonres"])].append(key)
    for (us, vs, status), keys in sorted(cells.items()):
        orders = strict_orders(us, vs)
        print(
            f"{us}|{vs}|{us+vs}|{gcd(us,vs)}|{status}|{len(keys)}|"
            f"{sum(info[key]['rows'] for key in keys)}|"
            f"{sum(len(info[key]['orders']) for key in keys)}|"
            f"{','.join(map(fstr,orders)) or '-'}"
        )

    print("\nALL_GROUPS")
    print("D|m|M_2..M_s|s|d_s|u_s|v_s|g|NONRES|resonant_j|rows|pair_count|orders")
    for key in sorted(groups):
        data = info[key]
        print(
            f"{key[0]}|{key[1]}|{','.join(map(str,key[2]))}|{data['s']}|{data['ds']}|"
            f"{data['us']}|{data['vs']}|{data['g']}|{data['nonres']}|"
            f"{','.join(map(str,data['resonant'])) or '-'}|{data['rows']}|"
            f"{len(data['orders'])}|{','.join(map(fstr,data['orders'])) or '-'}"
        )

    def group_row(key):
        data = info[key]
        return (
            key[0], key[1], sequence_text(key[2]), data["s"], data["ds"], data["us"],
            data["vs"], data["g"], data["nonres"], sequence_text(data["resonant"]),
            data["rows"], len(data["orders"]), sequence_text(map(fstr, data["orders"])),
        )

    group_header = (
        "D", "m", "M_2..M_s", "s", "d_s", "u_s", "v_s", "g", "NONRES",
        "resonant_j", "row_count", "pair_count", "strict_orders",
    )
    all_groups_path = write_tsv(
        "all-groups.tsv", group_header, (group_row(key) for key in sorted(groups))
    )
    false_keys = sorted(key for key in groups if not info[key]["nonres"])
    false_groups_path = write_tsv(
        "false-groups.tsv", group_header, (group_row(key) for key in false_keys)
    )

    false_row_header = (
        "D", "m", "M_2..M_s", "s", "d_s", "u_s", "v_s", "g", "resonant_j",
        "V", "row_key", "Im_min_candidate", "IM_max", "principal_minor_floor_candidate",
    )
    false_records = sorted(
        (record for record in selected if not info[group_key(record)]["nonres"]),
        key=row_key,
    )
    false_rows_path = write_tsv(
        "false-rows.tsv",
        false_row_header,
        (
            (
                record["n"], record["m"], sequence_text(record["M"]), record["s"],
                info[group_key(record)]["ds"], record["u_s"], record["V_s"],
                info[group_key(record)]["g"], sequence_text(info[group_key(record)]["resonant"]),
                sequence_text(f"{index}:{value}" for index, value in sorted(
                    (int(index), int(value)) for index, value in record["V"].items()
                )),
                record["row_key"], record["Im_min_candidate"], record["IM_max"],
                record["principal_minor_floor_candidate"],
            )
            for record in false_records
        ),
    )

    pair_header = (
        "D", "m", "M_2..M_s", "d_s", "u_s", "v_s", "delta", "delta_denominator", "NONRES",
    )
    pairs_path = write_tsv(
        "order-pairs.tsv",
        pair_header,
        (
            (
                key[0], key[1], sequence_text(key[2]), data["ds"], data["us"], data["vs"],
                fstr(order), order.denominator, data["nonres"],
            )
            for key in sorted(groups)
            for data in (info[key],)
            for order in data["orders"]
        ),
    )

    by_degree = []
    for degree in sorted({key[0] for key in groups}):
        keys = [key for key in groups if key[0] == degree]
        by_degree.append({
            "D": degree,
            "groups_true": sum(info[key]["nonres"] for key in keys),
            "groups_false": sum(not info[key]["nonres"] for key in keys),
            "rows_true": sum(info[key]["rows"] for key in keys if info[key]["nonres"]),
            "rows_false": sum(info[key]["rows"] for key in keys if not info[key]["nonres"]),
            "pairs_true": sum(len(info[key]["orders"]) for key in keys if info[key]["nonres"]),
            "pairs_false": sum(len(info[key]["orders"]) for key in keys if not info[key]["nonres"]),
        })
    by_cell = []
    for (us, vs, status), keys in sorted(cells.items()):
        by_cell.append({
            "u_s": us,
            "v_s": vs,
            "d_s": us + vs,
            "g": gcd(us, vs),
            "NONRES": status,
            "groups": len(keys),
            "rows": sum(info[key]["rows"] for key in keys),
            "pairs": sum(len(info[key]["orders"]) for key in keys),
            "strict_orders": [fstr(order) for order in strict_orders(us, vs)],
        })
    first_false = false_keys[0]
    first_data = info[first_false]
    summary = {
        "provenance": {
            "charged_moh": {
                "path": str(CHARGED_MOH),
                "sha256": moh_digest,
                "charged": True,
            },
            "screen_snapshot": {
                "path": str(SCREEN_RESULTS),
                "sha256": sha256(SCREEN_RESULTS),
                "bytes": SCREEN_RESULTS.stat().st_size,
                "charged": False,
                "custody_warning": "Cohort membership is imported from this auxiliary workspace snapshot.",
            },
        },
        "generation": {
            "raw": "census(D,Kmin=16,full=True) for D=48..200",
            "cohort": "record.phase == 'us_gt_1' and record.xu_ok_candidate",
            "group_key": "(D,m,(M_2,...,M_s),V_s)",
            "u_s": "d_s-V_s (do not use Skel.u, which is a different integration quantity)",
            "order_pairs": "reduced delta=a/b with 1<delta<V_s/u_s and 1<=b<=u_s",
        },
        "counts": {
            "raw_full_rows": len(regenerated),
            "raw_u_s_ge_2_rows": {
                "total": len(raw_us_rows), "NONRES_true": sum(raw_us_rows),
                "NONRES_false": len(raw_us_rows) - sum(raw_us_rows),
            },
            "raw_u_s_ge_2_groups": {
                "total": len(raw_us_groups), "NONRES_true": sum(raw_us_groups.values()),
                "NONRES_false": len(raw_us_groups) - sum(raw_us_groups.values()),
            },
            "poly_ode_rows": len(source["rows"]),
            "poly_ode_u_s_ge_2_rows": len(poly_ode_us_rows),
            "poly_ode_u_s_ge_2_groups": {
                "total": len(poly_ode_us_groups),
                "NONRES_true": sum(poly_ode_us_groups.values()),
                "NONRES_false": len(poly_ode_us_groups) - sum(poly_ode_us_groups.values()),
            },
            "sharpened_rows": {
                "total": len(selected), "NONRES_true": 204, "NONRES_false": 92,
            },
            "sharpened_groups": {
                "total": len(groups), "NONRES_true": 124, "NONRES_false": 42,
            },
            "strict_order_pairs": {
                "total": 274, "NONRES_true": 192, "NONRES_false": 82,
                "coverage_fraction": "96/137", "coverage_percent": "70.0729927007",
            },
            "groups_with_strict_order_pairs": 91,
            "groups_without_strict_order_pairs": 75,
            "u_s_group_distribution": {str(us): count for us, count in sorted(
                collections.Counter(data["us"] for data in info.values()).items()
            )},
            "u_s_pair_distribution": {str(us): sum(
                len(data["orders"]) for data in info.values() if data["us"] == us
            ) for us in sorted({data["us"] for data in info.values()})},
        },
        "nonres_equivalence": (
            "d_s does not divide u_s*j for every 1<=j<=v_s iff d_s/g>v_s "
            "iff u_s>(g-1)*v_s, where d_s=u_s+v_s and g=gcd(u_s,v_s)"
        ),
        "by_degree": by_degree,
        "by_cell": by_cell,
        "smallest_false_group": {
            "D": first_false[0], "m": first_false[1], "M": list(first_false[2]),
            "s": first_data["s"], "d_s": first_data["ds"], "u_s": first_data["us"],
            "v_s": first_data["vs"], "g": first_data["g"],
            "resonant_j": list(first_data["resonant"]), "row_count": first_data["rows"],
            "strict_orders": [fstr(order) for order in first_data["orders"]],
        },
        "guardrails": [
            "The bound den(delta)<=u_s is a charged OPEN assumption, so 274 is a conditional finite screen, not a sourced exhaustive split census.",
            "NONRES is only arithmetic pivot nonvanishing; it is not a unit-ideal certificate or proof that the ladder row is sourced-necessary.",
            "For FALSE groups no uniform replacement row is supplied by the charged inputs; a branch-specific affine pole/interior or incidence row would require a separate source and construction.",
        ],
    }
    summary_path = OUTDIR / "summary.json"
    summary_path.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")

    artifacts = [
        Path(__file__), summary_path, all_groups_path, false_groups_path, false_rows_path, pairs_path,
    ]
    manifest_path = OUTDIR / "artifacts.sha256"
    manifest_path.write_text("".join(
        f"{sha256(path)}  {path}\n" for path in artifacts
    ))
    print("\nARTIFACTS")
    for path in artifacts + [manifest_path]:
        print(f"{path}|bytes={path.stat().st_size}|sha256={sha256(path)}")


if __name__ == "__main__":
    main()
