#!/usr/bin/env python3
"""Moh p.208 (16,12;13,3;X) order-chart saturation control.

Moh prints the chart but not its final elimination.  To avoid relying on the
apparent repeated-c5 typo in alpha_3, this driver gives the A and B terms
independent coefficients, hence tests a (slightly) larger chart.  Emptiness of
this larger c!=0 component is a valid positive control.
"""

import argparse
import sympy as sp


x, y = sp.symbols("x y")


def jac(f, g):
    return sp.diff(f, x) * sp.diff(g, y) - sp.diff(f, y) * sp.diff(g, x)


def build():
    b1, b2, b3, b4 = bs = sp.symbols("b1:5")
    z = y - x
    B = sp.expand(y * z + b1 * y + b2)
    A = sp.expand(y * B + b3)
    h = sp.expand(y * A + b4)
    u = sp.symbols("u1:15")
    (u1, u2, u3, u4, u5, u6, u7,
     u8, u9, u10, u11, u12, u13, u14) = u
    c = sp.Symbol("c")

    alpha = {
        1: u1,
        2: u2 * A + u3,
        3: u6 * A + u7 * B + u8,
        4: u12 * A + u13 * B + u14 * z,
    }
    beta = {2: u4 * A + u5, 3: u9 * A + u10 * B + u11}
    q_terms = [(sp.Integer(1), 3)] + [(beta[i], 3 - i) for i in (2, 3)]
    p_terms = [(sp.Integer(1), 4)] + [(alpha[i], 4 - i) for i in (1, 2, 3, 4)]

    by_power = {}
    for aa, r in q_terms:
        for bb, s in p_terms:
            v = jac(aa, bb)
            if v:
                by_power[r + s] = by_power.get(r + s, 0) + v
            v = s * bb * jac(aa, h) + r * aa * jac(h, bb)
            if v:
                by_power[r + s - 1] = by_power.get(r + s - 1, 0) + v

    k = 0
    while k <= max(by_power):
        quotient, remainder = sp.div(sp.expand(by_power.get(k, 0)), h, y)
        by_power[k] = sp.expand(remainder)
        if quotient != 0:
            by_power[k + 1] = by_power.get(k + 1, 0) + quotient
        k += 1

    equations = []
    for hp in sorted(by_power):
        r = by_power[hp] - (c * x if hp == 0 else 0)
        equations.extend(co for _, co in sp.Poly(sp.expand(r), x, y).terms() if co != 0)
    return list(bs) + list(u), c, equations, h


def singular(expr):
    return str(sp.expand(expr)).replace("**", "^")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--emit-singular", action="store_true")
    args = parser.parse_args()
    params, c, equations, h = build()
    if not args.emit_singular:
        print("Moh (16,12) enlarged p.208 chart")
        print("  h =", h)
        print("  parameters=%d plus c=1 -> unknowns=%d" % (len(params), len(params) + 1))
        print("  equations=%d; equation text bytes=%d" %
              (len(equations), sum(len(str(e)) for e in equations)))
        return

    T = sp.Symbol("T")
    variables = params + [c, T]
    print("// generated by moh1612_control.py --emit-singular")
    print("ring R=0,(%s),dp;" % ",".join(map(str, variables)))
    print("option(redSB);")
    print('print("MOH1612_START equations=%d unknowns=%d plus_T=1");' %
          (len(equations), len(params) + 1))
    print("ideal I=%s;" % ",\n".join([singular(e) for e in equations] + ["T*c-1"]))
    print("ideal G=std(I);")
    print('print("MOH1612_DONE basis_size=");')
    print("size(G);")
    print('if (reduce(1,G)==0) { print("MOH1612_SATURATED_EMPTY"); }'
          ' else { print("MOH1612_NONTRIVIAL"); }')
    print("G;")
    print("quit;")


if __name__ == "__main__":
    main()
