#!/usr/bin/env python3
"""Corrected-face OUTPUT-COORDINATE DIAGNOSTIC, never a full-source kill.

h3, K2, radii and outer exponents are evaluated from source_data.SOURCE.
All minor maps are regenerated by exact coefficient comparison.  The old
K2 output-coordinate chart is retained here only for historical gate-point
controls: this module does NOT impose the inverse C2/C3 source-floor rows.
The default delta2 chart carries minor_a2.  --gate-a2-zero is an explicitly
restricted control that reproduces the frozen gate's diagnostic slice.
"""
from __future__ import annotations
import argparse
from functools import lru_cache
import importlib.util
import json
from math import comb
from pathlib import Path
import subprocess
import sys
import sympy as sp

HERE=Path(__file__).resolve().parent
sys.path.insert(0,str(HERE))
from source_data import SOURCE as D, jsonable
import minor_maps as minor
spec=importlib.util.spec_from_file_location('diagnostic_frozen_sparse',HERE/'frozen'/'band_engine.py')
b=importlib.util.module_from_spec(spec);sys.modules[spec.name]=b;spec.loader.exec_module(b)
for _name in dir(b):
    if not _name.startswith('__') and _name not in globals():
        globals()[_name]=getattr(b,_name)
GATE_A2_ZERO=False


def h3_template():
    degree=D['h3_degree']; wt,wz=D['D2_weight']; floor=D['h3_floor']
    h=dict(D['h3_top']); variables=[]
    below=[]; equal=[]; above=[]
    for r in range(1,degree+1):
        for q in range(degree-r+1):
            weight=wt*r+wz*q
            (below if weight<floor else equal if weight==floor else above).append((r,q))
        retained=[q for q in range(degree-r+1) if wt*r+wz*q>floor]
        if not retained: continue
        vmin=min(retained)
        for q in retained:
            variable=sp.Symbol(f'Hc_{r}_{q}'); variables.append(variable)
            for j in range(q-vmin+1):
                key=(r,vmin+j)
                h[key]=h.get(key,0)+variable*comb(q-vmin,j)
    assert equal==D['h3_equality_slots']
    ell=sp.Symbol('E82')  # historical equality-coordinate name only
    for key,value in D['h3_equality'].items():
        h[key]=sp.expand(value.subs({sp.Symbol('beta'):1,sp.Symbol('ell'):ell}))
    variables += sorted(set().union(*(sp.sympify(v).free_symbols for v in h.values()))-set(variables),key=str)
    assert len(below)+len(equal)+len(above)==degree*(degree+1)//2
    return {key:sp.expand(v) for key,v in h.items()},variables


@lru_cache(maxsize=None)
def h3_branch_map(branch):
    h,variables=h3_template()
    mapping,free,meta=minor.derive_minor_map(branch,h,variables)
    if GATE_A2_ZERO and branch=='delta2':
        mapping={v:sp.expand(rhs.subs(sp.Symbol('minor_a2'),0)) for v,rhs in mapping.items()}
        free=[v for v in free if str(v)!='minor_a2']
        meta={**meta,'restricted_gate_control':'minor_a2=0'}
    return mapping,free,meta


def local_rows(item,branch,max_power,exact_only=True):
    rows=minor.local_rows(item,branch,max_power,exact_only)
    if GATE_A2_ZERO and branch=='delta2':
        rows={key:sp.expand(value.subs(sp.Symbol('minor_a2'),0)) for key,value in rows.items()}
    return rows


def build_major_h2(branch,max_t):
    h,hvars=h3_template()
    hmap,hfree,centre=h3_branch_map(branch)
    h={key:b.substitute_map(value,hmap) for key,value in h.items()}
    face,_proof=minor.derive_minor_face(branch)
    pole=minor.minor_order(branch)['normalized_power']
    hrows=local_rows(h,branch,pole)
    target={(pole,int(q[0])):value for q,value in sp.Poly(face,sp.Symbol('zeta')).terms()}
    assert all(sp.expand(hrows.get(key,0)-target.get(key,0))==0 for key in set(hrows)|set(target))
    cube=b.tz_mul(b.tz_mul(h,h,max_t),h,max_t)
    degree=D['k2_degree']; wt,wz=D['D2_weight']; floor=D['k2_floor']
    # C2 has degree_y<h3_degree, so C2*h3 has degree_y<=2*h3_degree-1.
    output_qcap=2*D['h3_degree']-1
    dvars={(r,q):sp.Symbol(f'K2c_{r}_{q}')
           for r in range(1,degree+1) for q in range(degree-r+1)
           if wt*r+wz*q>floor and q<=output_qcap}
    def raw(r,q): return dvars.get((r,q),cube.get((r,q),sp.Integer(0)))
    rows=[]
    cover,centre_power,generic_power=D['D1_substitution']
    assert centre_power==cover*wz//wt
    for W in range(floor+1,(D['k2_D1_floor']-1)//(cover//wt)+1):
        positions=[(r,q) for r in range(1,degree+1) for q in range(degree-r+1) if wt*r+wz*q==W]
        for k in range(D['k2_D1_floor']-(cover//wt)*W):
            rows.append((f'h2_D1_W{W}_k{k}',sp.expand(sum(comb(q,k)*raw(r,q) for r,q in positions if q>=k))))
    # Historical rational pivot CHOICE, not a face or support assertion.
    # Keeping it makes the gate's all-other-coordinates-zero point comparable.
    pivot_sites=[(11,16),(15,13),(19,10),(23,7),(27,4),(10,17),(14,14)]
    work=list(rows); mapping={}; pivots=[]
    for site in pivot_sites:
        variable=dvars[site]
        choice=None
        for index,(label,row) in enumerate(work):
            row=b.substitute_map(row,mapping); coefficient=sp.diff(row,variable)
            if coefficient.is_Rational and coefficient!=0:
                choice=index,label,row,coefficient;break
        assert choice is not None
        index,label,row,coefficient=choice
        rhs=sp.cancel(-(row-coefficient*variable)/coefficient)
        mapping[variable]=rhs;pivots.append((label,str(variable),str(coefficient)))
        del work[index];work=[(lab,sp.expand(rr.subs(variable,rhs))) for lab,rr in work]
    mapping=b.resolve_map(mapping)
    assert all(b.substitute_map(row,mapping)==0 for _,row in rows)
    k2={}
    # Top is the derived cubic power of the derived h3 top.
    top3=b.tz_mul(b.tz_mul(D['h3_top'],D['h3_top'],0),D['h3_top'],0)
    k2.update(top3)
    equality={key:sp.expand(value.subs(sp.Symbol('beta'),1)) for key,value in D['k2_equality'].items()}
    for r in range(1,max_t+1):
        for q in range(degree-r+1):
            value=equality.get((r,q),raw(r,q) if wt*r+wz*q>floor else sp.Integer(0))
            value=b.substitute_map(sp.expand(value),mapping)
            if value!=0:k2[r,q]=value
    inner=set(hfree)|(set(dvars.values())-set(mapping))
    return k2,inner,{'h3_control':{'verified':True,'target':str(face),'local_power':pole},
        'centre':centre,'h3_free':[str(v) for v in hfree],
        'major_output_coordinate_count_before_D1':len(dvars),'major_h2_D1_pivots':pivots,
        'major_output_free_count':len(dvars)-len(mapping),'inner_dimension_including_centres':len(inner),
        'scope':'DIAGNOSTIC ONLY: inverse C2/C3 source-floor obligations omitted'}


# All shared sparse arithmetic references use these reconstructed functions.
b.h3_template=h3_template;b.h3_branch_map=h3_branch_map;b.local_rows=local_rows
b.build_major_h2=build_major_h2;b.OUTER_SPECS=D['outer_specs']
OUTER_SPECS=D['outer_specs']

def verify_inputs():
    result=subprocess.run(['sha256sum','-c',str(HERE/'inputs.sha256')],capture_output=True,text=True,check=True)
    return {'all_hashes_match':True,'manifest':str(HERE/'inputs.sha256'),'transcript':result.stdout}

b.verify_inputs=verify_inputs
b.reproduce_charged_endpoint=lambda:{'scope':'historical controls executed separately; no inherited endpoint is asserted here'}

def run(branch,stage,emit_singular=None):
    result=b.run(branch,stage,emit_singular)
    result['type']='DERIVED-FACE DIAGNOSTIC OUTPUT CHART; NOT A SOURCE BRANCH VERDICT'
    result['scope']='C2/C3 source-floor inverse-map equations omitted; cannot prove a branch kill'
    result['verdict']='DIAGNOSTIC-UNIT' if result['verdict']=='DEAD' else 'DIAGNOSTIC-NONUNIT'
    result['gate_a2_zero_restriction']=GATE_A2_ZERO
    result['driver_sha256']=b.sha256(Path(__file__))
    result['source_arithmetic']=jsonable(D)
    return result

if __name__=='__main__':
    parser=argparse.ArgumentParser()
    parser.add_argument('--branch',choices=['delta2','delta52'],required=True)
    parser.add_argument('--stage',type=int,required=True)
    parser.add_argument('--emit-singular',type=Path)
    parser.add_argument('--gate-a2-zero',action='store_true')
    args=parser.parse_args()
    GATE_A2_ZERO=args.gate_a2_zero
    print(json.dumps(run(args.branch,args.stage,args.emit_singular),indent=2,sort_keys=True))
