#!/usr/bin/env python3
"""Exact check of the (2,3) H-adic Jacobian identity.

Ring/typing: characteristic-zero differential polynomial ring generated by
h, beta, G1, G0 over Q, with commuting derivations d/dx,d/dy.  SymPy's
undefined functions realize that typing.  We use
    J(u,v) = u_x*v_y - u_y*v_x.

No quotient-ring independence of powers of h is asserted here.  This file
only checks the polynomial differential identity before any H-adic carrying.
"""
import sympy as sp

x, y = sp.symbols("x y")
h = sp.Function("h")(x, y)
beta = sp.Function("beta")(x, y)
G1 = sp.Function("G1")(x, y)
G0 = sp.Function("G0")(x, y)


def jac(u, v):
    return sp.diff(u, x) * sp.diff(v, y) - sp.diff(u, y) * sp.diff(v, x)


f = h**2 + 2 * beta
g = h**3 + G1 * h + G0
actual = sp.expand(jac(f, g))

correct = (
    h**2 * (2 * jac(h, G1) + 6 * jac(beta, h))
    + h * (2 * jac(h, G0) + 2 * jac(beta, G1))
    + 2 * G1 * jac(beta, h)
    + 2 * jac(beta, G0)
)

# Formula quoted in the charged prompt/m2-descent text.
charged = (
    2 * h**2 * jac(h, G1)
    + h * (2 * jac(h, G0) + 6 * jac(beta, h))
    + 2 * G1 * jac(beta, h)
    + 2 * jac(beta, G0)
)

assert sp.simplify(actual - correct) == 0
charged_error = sp.factor(actual - charged)
expected_error = sp.factor(
    6 * (h**2 - h) * jac(beta, h) + 2 * h * jac(beta, G1)
)
assert sp.simplify(charged_error - expected_error) == 0

print("RING: Q differential-polynomial ring in h,beta,G1,G0; J=ux*vy-uy*vx")
print("CORRECT_IDENTITY_VERIFIED: True")
print("  J(h^2+2 beta, h^3+G1 h+G0) =")
print("  h^2*(2J(h,G1)+6J(beta,h))")
print("    + h*(2J(h,G0)+2J(beta,G1))")
print("    + 2G1*J(beta,h)+2J(beta,G0)")
print("CHARGED_IDENTITY_VERIFIED: False")
print("  actual-minus-charged = 6(h^2-h)J(beta,h)+2hJ(beta,G1)")

# Concrete polynomial witness to keep the failure independent of formal
# differential-polynomial simplification.
witness = {h: y, beta: x/sp.Integer(2), G1: 3*x/sp.Integer(2), G0: 0}
w_actual = sp.expand(actual.subs(witness).doit())
w_charged = sp.expand(charged.subs(witness).doit())
assert w_actual == 3*x/sp.Integer(2)
assert w_charged == -3*y**2+3*y+3*x/sp.Integer(2)
print("CONCRETE_WITNESS h=y,beta=x/2,G1=3x/2,G0=0:")
print("  actual=3*x/2; charged=-3*y^2+3*y+3*x/2")

# Important Moh specialization.  The h^2 terms cancel when G1=3 beta.
special = sp.expand(correct.subs(G1, 3 * beta).doit())
special_expected = (
    2 * h * jac(h, G0)
    + 6 * beta * jac(beta, h)
    + 2 * jac(beta, G0)
)
assert sp.simplify(special - special_expected) == 0
print("MOH_SPECIALIZATION_G1_EQ_3BETA:")
print("  J = 2h*J(h,G0)+6beta*J(beta,h)+2J(beta,G0)")
