#!/usr/bin/env python3
"""Reconstruct the D=108 delta=3 saturated-T8 survivor as actual polynomials
and decide its geometric meaning by direct computation.

Point (rekill lane, witness-saturated-T8.json): all free coordinates 0 except
jet1 = jet2 = c = 1, K2c_3_26 = -8, K2c_4_25 = 20; pivots resolved.
All 60 joint pivots are on B1c coordinates from Jacobian rows (ledger), and
J(K2^3, K2^2) == 0, so every Jacobian row lies in the ideal generated by the
outer coordinates: with all outer free coordinates 0 the pivoted outer
coordinates are 0 too.  Hence at the point KA2 = KA3 = KB1 = KB2 = 0.
"""
import json, sys, time
from collections import defaultdict
from math import comb
from pathlib import Path
import sympy as sp
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from d108_common import build, qstar_reduce, local_rows, symbol, substitute_map, z_to_w
sys.path.insert(0, "/home/ubuntu/jc2/box/d108-rekill-20260905/work")
from rekill_engine import (SRC, tz_mul, tz_add, jacobian_band, raw_minor_support, outer_state)

t0 = time.monotonic()
obj = build()
k2, k2free, h3free, h3, subs0 = obj["k2"], obj["k2free"], obj["h3free"], obj["h3"], obj["subs0"]
c, jet1, jet2, pi = symbol("c"), symbol("jet1"), symbol("jet2"), symbol("pi")
T = 8
# ---- Delta-system at T=8 (outer = 0): F = K2^3, G = K2^2 pole rows only; J rows vanish identically
KG = tz_mul(k2, k2, T); KF = tz_mul(KG, k2, T)
g_loc, f_loc = local_rows(KG, T, False), local_rows(KF, T, False)
rows = []
for name, table in (("F", f_loc), ("G", g_loc)):
    for n in range(1, T + 1):
        for k in raw_minor_support(name, False).get(n, ()):
            rows.append((f"{name}_local{n}_coord{k}", table.get((n, k), sp.Integer(0))))
eligible = set(k2free) | set(h3free)
residual, subs, pivots, zeros = qstar_reduce(rows, eligible)
print("Delta-system T=8: rows", len(rows), "pivots", [str(p.variable) for p in pivots],
      "residual", {l: str(sp.factor(v)) for l, v in residual})
# ---- the rekill point
point = {v: sp.Integer(0) for v in eligible}
point[jet1] = point[jet2] = point[c] = sp.Integer(1)
point[symbol("K2c_3_26")] = sp.Integer(-8); point[symbol("K2c_4_25")] = sp.Integer(20)
full = dict(point)
for var, rhs in subs.items(): full[var] = sp.expand(sp.together(rhs).subs(point))
for var, rhs in subs0.items(): full[var] = sp.expand(sp.together(rhs).subs(full))
assert all(sp.expand(v.subs(full)) == 0 for _l, v in residual), "residual not zero at point"
assert all(sp.expand(v.subs(full)) == 0 for _l, v in rows), "raw Delta rows not zero at point"
num = lambda tz: {k: sp.Rational(sp.expand(v.subs(full))) for k, v in tz.items() if sp.expand(v.subs(full)) != 0}
K2n, K3n = num(k2), num(h3)
hc_at_point = {str(k): str(v) for k, v in full.items() if str(k).startswith("Hc_")}
k2c_at_point = {str(k): str(v) for k, v in full.items() if str(k).startswith("K2c_") and v != 0}
print("Hc at point:", hc_at_point)
print("nonzero K2c at point:", k2c_at_point)

# ---- 1. cross-check against the rekill lane's full saturated row set (outer = 0)
KGn = tz_mul(K2n, K2n, T); KFn = tz_mul(KGn, K2n, T)
gl, fl = local_rows(KGn, T, False), local_rows(KFn, T, False)
nz = []
cnt = {"F": 0, "G": 0, "J": 0}
for name, table in (("F", fl), ("G", gl)):
    for n in range(1, T + 1):
        for k in raw_minor_support(name, False).get(n, ()):
            cnt[name] += 1
            if table.get((n, k), 0) != 0: nz.append((f"{name}_local{n}_coord{k}", str(table[(n, k)])))
for tp in range(1, T + 1):
    J = jacobian_band(KFn, KGn, tp)
    for k in range(179 - tp):
        cnt["J"] += 1
        if J.get(k, 0) != 0: nz.append((f"J_t{tp}_d{178-tp}_k{k}", str(J[k])))
print("saturated-T8 rows at the point (outer=0):", cnt, "nonzero:", nz)

# ---- 2. polynomials in (x,y)
x, y = sp.symbols("x y")
def to_xy(tz, deg):
    # K(t,z) = t^deg * P(1/t, (1+z)/t)  =>  P(x,y) = x^deg * K(1/x, y/x - 1)
    expr = sum(v * sp.Integer(1)**0 * (1/x)**r * (y/x - 1)**q for (r, q), v in tz.items())
    return sp.Poly(sp.expand(x**deg * expr), x, y, domain="QQ")
h3p = to_xy(K3n, 9); h2p = to_xy(K2n, 36)
assert h3p.total_degree() == 9 and h2p.total_degree() == 36
print("h3 =", h3p.as_expr())
print("h3 factorization over Q:", sp.factor_list(h3p.as_expr()))
print("h2: terms", len(h2p.terms()), "factorization over Q (irreducible factors, degrees):",
      [(sp.Poly(f, x, y).total_degree(), m) for f, m in sp.factor_list(h2p.as_expr())[1]])
# tower: h3-adic expansion of h2 (h3 monic in y of degree 9)
def h3adic(P, Hp):
    quots, rems = P, []
    while quots.degree(y) >= Hp.degree(y):
        q, r = sp.div(quots, Hp, y)
        rems.append(sp.Poly(r, x, y, domain="QQ")); quots = sp.Poly(q, x, y, domain="QQ")
    rems.append(quots)
    return rems   # h2 = sum rems[i] * h3^i
rems = h3adic(h2p, h3p)
print("h3-adic expansion of h2: coefficients of h3^i, i=0..:",
      [(i, r.total_degree() if not r.is_zero else None) for i, r in enumerate(rems)])
C4, C3, C2, C1, C0 = rems[0], rems[1], rems[2], rems[3], rems[4]
print("tower check: h3^4 coefficient =", C0.as_expr(), "; h3^3 coefficient C1 =", C1.as_expr())
# ---- 3. F = h2^3, G = h2^2 and their Jacobian
Fp = h2p**3; Gp = h2p**2
Jp = Fp.diff(x) * Gp.diff(y) - Fp.diff(y) * Gp.diff(x)
print("deg F, deg G =", Fp.total_degree(), Gp.total_degree(), "; J(F,G) identically zero:", Jp.is_zero)
J0 = (Fp.coeff_monomial(x) * Gp.coeff_monomial(y) - Fp.coeff_monomial(y) * Gp.coeff_monomial(x))
print("degree-0 Jacobian row J_0 = f10*g01 - f01*g10 =", J0, " (Keller needs 1)")
print("F^2 - G^3 == 0:", (Fp**2 - Gp**3).is_zero)
# ---- 4. minor-place expansions
K2s = local_rows(K2n, 40, False)
a = defaultdict(dict)
for (n, k), v in K2s.items(): a[n][k] = v
ordK2 = min(a)
print("K2(sigma): ord_t =", ordK2, "; a_p for p<=", ordK2 + 2, ":",
      {p: sp.expand(sum(v * pi**k for k, v in a[p].items())) for p in sorted(a) if p <= ordK2 + 2})
print("=> G(sigma) = t^-72 K2(sigma)^2 first nonzero pole row at G local power", 2 * ordK2,
      "(stage", 2 * ordK2 - 4, "); F at local", 3 * ordK2)
K3s = local_rows(K3n, 12, False)
b = defaultdict(dict)
for (n, k), v in K3s.items(): b[n][k] = v
print("K3(sigma) =", {p: sp.expand(sum(v * pi**k for k, v in b[p].items())) for p in sorted(b)})
# ---- 5. D2 faces: t = s^4, z = pi*s^5
def face(tz, W):
    return sp.expand(sum(v * pi**q for (r, q), v in tz.items() if 4 * r + 5 * q == W))
def lowest(tz):
    return min(4 * r + 5 * q for (r, q), v in tz.items() if r >= 1 or True)
k3face = face(K3n, 35); k2face = face(K2n, 140)
print("K3 D2 face (weight 35):", sp.factor(k3face), "| lower weights present:",
      sorted({4*r+5*q for (r,q) in K3n if 4*r+5*q < 35}))
print("K2 D2 face (weight 140):", sp.factor(k2face), "| lower weights present:",
      sorted({4*r+5*q for (r,q) in K2n if 4*r+5*q < 140}))
# ---- 6. outer blocks: homogeneity of the outer preblock/D1 pivots
outer, outer_free, meta = outer_state(SRC, 7)
inhom = []
for blk, coords in outer.items():
    for pos, val in coords.items():
        e = sp.expand(val)
        if e != 0 and (e.as_poly(*sorted(e.free_symbols, key=str)).coeff_monomial(1) != 0
                       or any(not str(s).startswith(("A2c", "A3c", "B1c", "B2c")) for s in e.free_symbols)):
            inhom.append((blk, pos, str(e)[:80]))
print("outer resolved coordinates that are inhomogeneous or involve non-outer symbols:", inhom)
const_slots = {blk: (max(r for r, q in coords) , (max(r for r, q in coords), 0) in coords)
               for blk, coords in outer.items()}
print("constant-term slots (r_max, present as free coordinate):", const_slots,
      "; free constant terms:", {b: str(outer[b].get((r, 0))) for b, (r, _) in const_slots.items()})
rec = {"point_free_nonzero": {"jet1": 1, "jet2": 1, "c": 1, "K2c_3_26": -8, "K2c_4_25": 20},
       "Hc_at_point": hc_at_point, "K2c_nonzero_at_point": k2c_at_point,
       "Delta_T8_residual": {l: str(sp.factor(v)) for l, v in residual},
       "saturated_T8_row_counts_outer_zero": cnt, "saturated_T8_nonzero_rows": nz,
       "h3": str(h3p.as_expr()), "h3_factors": str(sp.factor_list(h3p.as_expr())),
       "h2_factor_degrees": [(sp.Poly(f, x, y).total_degree(), m) for f, m in sp.factor_list(h2p.as_expr())[1]],
       "tower": {"h3^4_coeff": str(C0.as_expr()), "C1_h3^3_coeff": str(C1.as_expr()),
                 "deg_C2": C2.total_degree() if not C2.is_zero else None,
                 "deg_C3": C3.total_degree() if not C3.is_zero else None,
                 "deg_C4": C4.total_degree() if not C4.is_zero else None},
       "F_is_h2_cubed": True, "G_is_h2_squared": True,
       "J_identically_zero": bool(Jp.is_zero), "J0_row_value": str(J0), "F2_minus_G3_zero": bool((Fp**2-Gp**3).is_zero),
       "ord_t_K2_sigma": ordK2, "a_p": {str(p): str(sp.expand(sum(v * pi**k for k, v in a[p].items()))) for p in sorted(a) if p <= ordK2 + 2},
       "first_failing_G_pole_row_local_power": 2 * ordK2, "first_failing_stage": 2 * ordK2 - 4,
       "K3_sigma": {str(p): str(sp.expand(sum(v * pi**k for k, v in b[p].items()))) for p in sorted(b)},
       "K3_D2_face": str(sp.factor(k3face)), "K2_D2_face": str(sp.factor(k2face)),
       "outer_inhomogeneous": inhom, "outer_constant_slots": {b: list(v) for b, v in const_slots.items()},
       "wall_seconds": round(time.monotonic() - t0, 1)}
(HERE / "point_structure.json").write_text(json.dumps(rec, indent=1, default=str) + "\n")
print("done", rec["wall_seconds"], "s")
