#!/usr/bin/env python3
"""Certified exact-Q prefix of the delta=5/2 effective-T2 bridge.

The normalized series is KT2=s^396*T2.  Through s^100 none of the four
Tschirnhausen columns can occur, so this script extracts the exact
coefficient ideal of KG^3-KF^2 in that prefix, performs only QQ* affine
pivots, and emits the remaining ideal for Singular.  The prefix is a
necessary condition for the complete bridge; its quotient dimension is an
upper bound, never the dimension of the uncomputed complete bridge.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import os
from pathlib import Path
import resource
import sys
import time

for _name in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS", "NUMEXPR_NUM_THREADS"):
    os.environ.setdefault(_name, "1")

import sympy as sp


HERE = Path(__file__).resolve().parent
BRIDGE_PATH = HERE / "bridge_engine.py"
CAP = 100
PRIMES = (32003, 104729, 1299709)


def bridge_variables() -> set[sp.Symbol]:
    names = {"T2_a1", "T2_a0", "T2_b1", "T2_b0"}
    for i in range(2, 10):
        for m in range((2 * i) // 3 + 1):
            if (i, m) != (9, 6):
                names.add(f"T3_a{i}_m{m}")
    assert len(names) == 38
    return set(map(sp.Symbol, names))


def load_bridge():
    spec = importlib.util.spec_from_file_location("g9966_bridge_prefix_support", BRIDGE_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot import {BRIDGE_PATH}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def digest_rows(rows: list[tuple[str, sp.Expr]]) -> str:
    h = hashlib.sha256()
    for label, expression in rows:
        h.update(f"{label}\t{sp.srepr(sp.expand(expression))}\n".encode())
    return h.hexdigest()


def expression_text(expression: sp.Expr) -> str:
    return str(sp.expand(expression)).replace("**", "^")


def write_singular(residual: list[tuple[str, sp.Expr]], remaining: set[sp.Symbol]) -> dict:
    active = set().union(*(row.free_symbols for _label, row in residual)) if residual else set()
    c = sp.Symbol("c")
    active.add(c)
    active_order = sorted(active, key=str)
    inactive = sorted(remaining - active, key=str)
    wrapper = sp.Symbol("Zc")
    ring_order = active_order + [wrapper]
    entries = [expression_text(row) for _label, row in residual] + ["Zc*c-1"]
    comments = "\n".join(
        f"// row[{index}] {label}" for index, (label, _row) in enumerate(residual, 1)
    )
    template = """// {field_label} residual of the necessary T2 prefix s<=100.
// Generated by t2_prefix_qstar.py; omitted free variables are counted below.
// inactive_free_count={inactive_count}
ring R={characteristic},({ring_order}),dp;
{comments}
ideal I={entries};
option(redSB);
ideal G=std(I);
print(\"BEGIN_UNIT\"); print(reduce(1,G)); print(\"END_UNIT\");
print(\"BEGIN_ACTIVE_DIM\"); print(dim(G)); print(\"END_ACTIVE_DIM\");
print(\"BEGIN_BASIS\"); print(G); print(\"END_BASIS\");
ideal Czero=c,Zc*c-1;
ideal Cone=c-1,Zc*c-1;
print(\"BEGIN_CONTROLS\");
print(reduce(1,std(Czero))); // must be 0: excluded c=0 locus
print(reduce(1,std(Cone)));  // must be 1: retained c=1 point
print(\"END_CONTROLS\");
quit;
"""
    outputs = []
    fields = [(0, "Q")] + [(prime, f"p{prime}") for prime in PRIMES]
    for characteristic, suffix in fields:
        script = template.format(
            field_label="Exact-Q" if characteristic == 0 else f"GF({characteristic})",
            inactive_count=len(inactive),
            characteristic=characteristic,
            ring_order=','.join(map(str, ring_order)),
            comments=comments,
            entries=','.join(entries),
        )
        output = HERE / f"t2-prefix-s100-residual-{suffix}.sing"
        output.write_text(script, encoding="utf-8")
        outputs.append({
            "field": "Q" if characteristic == 0 else f"GF({characteristic})",
            "path": str(output.relative_to(HERE.parents[1])),
            "sha256": hashlib.sha256(output.read_bytes()).hexdigest(),
        })
    return {
        "scripts": outputs,
        "active_variables": list(map(str, active_order)),
        "active_count": len(active_order),
        "inactive_free_variables": list(map(str, inactive)),
        "inactive_free_count": len(inactive),
        "dimension_formula_if_nonunit": f"{len(inactive)} + active_dimension",
    }


def main() -> None:
    started = time.perf_counter()
    bridge = load_bridge()
    custody = bridge.verify_frozen()
    band = bridge.load_charged_module()
    _stage, free_names, joint_map, k2, outer, endpoint = bridge.load_endpoint(band)
    stats = bridge.ArithmeticStats()
    blocks = bridge.block_series(band, k2, outer, CAP, joint_map, stats)
    monic, F, G, _EF, _EG = bridge.monic_t2_and_FG(blocks, CAP, stats)

    def minimum(series):
        return min((n for n, _k in series), default=None)

    f_min, g_min = minimum(F), minimum(G)
    assert f_min is not None and g_min is not None
    first_columns = {
        "T2_a1": 66 + f_min + g_min,
        "T2_a0": 264 + g_min,
        "T2_b1": 198 + f_min,
        "T2_b0": 396,
    }
    assert all(value > CAP for value in first_columns.values())
    rows = [
        (f"T2_s{n}_pi{k}", sp.expand(expression))
        for (n, k), expression in sorted(monic.items())
        if n <= CAP and expression != 0
    ]
    chart_free = set(map(sp.Symbol, free_names))
    free = chart_free | bridge_variables()
    c = sp.Symbol("c")
    assert c in free
    row_symbols = set().union(*(row.free_symbols for _label, row in rows)) if rows else set()
    assert row_symbols <= chart_free

    residual, mapping, pivots, zero_rows = band.qstar_reduce(rows, set(free) - {c})
    remaining = free - set(mapping)
    assert c in remaining
    assert all(p.coefficient.is_Rational and p.coefficient != 0 for p in pivots)
    assert not set(mapping).intersection(
        set().union(*(row.free_symbols for _label, row in residual)) if residual else set()
    )

    singular = write_singular(residual, remaining)
    ledger_path = HERE / "t2-prefix-s100-pivots.jsonl"
    with ledger_path.open("w", encoding="utf-8") as stream:
        for pivot in pivots:
            stream.write(json.dumps({
                "row": pivot.label,
                "variable": str(pivot.variable),
                "coefficient": str(pivot.coefficient),
                "rhs": str(pivot.rhs),
            }, sort_keys=True) + "\n")
    result = {
        "type": "EXACT-Q NECESSARY T2 PREFIX / FALLACY-v2",
        "status": "COMPLETE[PREFIX-QSTAR]",
        "scope": {
            "normalized_expression": "s^396*T2",
            "coefficient_rows": "all pi coefficients through s^100",
            "logical_strength": "necessary prefix only; no full-bridge verdict",
            "truncation_exactness": "all localized series have nonnegative s support",
            "T2_columns_absent": first_columns,
        },
        "custody": {"count": custody["count"], "all_match": custody["all_match"]},
        "endpoint": endpoint,
        "support": {
            "F": bridge.series_summary(F),
            "G": bridge.series_summary(G),
            "monic": bridge.series_summary(monic),
        },
        "rows": {
            "input_count": len(rows),
            "input_sha256": digest_rows(rows),
            "first": rows[0][0] if rows else None,
            "last": rows[-1][0] if rows else None,
            "Qstar_pivots": len(pivots),
            "zero_or_dependent": zero_rows,
            "residual_count": len(residual),
            "residual_sha256": digest_rows(residual),
        },
        "pivots": {
            "ledger": str(ledger_path.relative_to(HERE.parents[1])),
            "ledger_sha256": hashlib.sha256(ledger_path.read_bytes()).hexdigest(),
            "variables": [str(p.variable) for p in pivots],
            "all_coefficients_Qstar": True,
            "localized_variable_excluded": "c",
        },
        "counting": {
            "stage7_free": len(chart_free),
            "adjoined_T_coefficients": len(bridge_variables()),
            "ambient_before_prefix_rows": len(free),
            "remaining_after_Qstar": len(remaining),
            "prefix_dimension_if_residual_nonunit": singular["dimension_formula_if_nonunit"],
            "warning": "This is an upper bound for the complete bridge, not its dimension.",
        },
        "singular": singular,
        "arithmetic": stats.__dict__,
        "resources": {
            "wall_seconds": round(time.perf_counter() - started, 3),
            "max_rss_kib": resource.getrusage(resource.RUSAGE_SELF).ru_maxrss,
            "threads": 1,
        },
    }
    output = HERE / "t2-prefix-s100.json"
    output.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
