	Command being timed: "python3 /tmp/jc2-lane.F6oLuI/inputs/uniform_binomial_identities.py"
	User time (seconds): 0.82
	System time (seconds): 0.04
	Percent of CPU this job got: 47%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.81
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 48224
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 10562
	Voluntary context switches: 1
	Involuntary context switches: 536
	Swaps: 0
	File system inputs: 0
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
