#!/usr/bin/env python3
"""E2: search for a degeneration weight omega such that the ideal generated by
the omega-INITIAL FORMS of the 2t-1 rows of I_(t,+) is already zero-dimensional
(dim <in_om(rows)> >= dim I, so dim 0 would be a degeneration certificate).
Structured omegas: all vectors in {-1,0,1}^t modulo multiples of the grading w
(adding c*w does not change initial forms), plus coordinate +-e_i.  Exact field
A_t via minpoly; each std under its own time cap (Singular option)."""
import subprocess, sys, itertools, json, time
HERE="/home/ubuntu/jc2/box/k16toptail-20260903"
def Ht(t):
    q=2*t+1; return f"{12*q*q}*yy^2-{12*q*(t+1)}*yy+{(t+1)*(3*t+2)}"
def run(t, cap):
    vars_=["b4"]+[f"q{j}_0" for j in range(2,t)]+["b3"]
    wts=[1]+list(range(2,t))+[t+1]; n=len(vars_)
    # omegas: {-1,0,1}^n, drop 0 and drop those equal to +-w-multiples; dedupe modulo w by canonical rep (subtract w*om[0]... simpler: keep all)
    oms=[om for om in itertools.product([-1,0,1],repeat=n) if any(om)]
    # canonical: two omegas equivalent iff difference is a rational multiple of w; dedupe
    seen=set(); uniq=[]
    for om in oms:
        # project out w: om - (om.w/w.w) w, store as tuple of Fractions -> use integers scaled by w.w
        ww=sum(x*x for x in wts); s=sum(a*b for a,b in zip(om,wts))
        key=tuple(ww*a - s*b for a,b in zip(om,wts))
        if key==tuple([0]*n): continue
        if key in seen: continue
        seen.add(key); uniq.append(om)
    print(f"t={t}: {len(oms)} raw omegas, {len(uniq)} distinct modulo w")
    sing=[f"""ring W=(0,yy),({",".join(vars_)}),wp({",".join(map(str,wts))});
minpoly={Ht(t)};
execute(read("{HERE}/rows_t{t}_exact.sing"));
proc inw(poly f, intvec om) {{
  int i; int j; int d; int m; poly g=0; intvec e; int first=1;
  for (i=1;i<=size(f);i++) {{
    e=leadexp(f[i]); d=0;
    for (j=1;j<=size(om);j++) {{ d=d+e[j]*om[j]; }}
    if (first==1) {{ m=d; g=f[i]; first=0; }}
    else {{ if (d>m) {{ m=d; g=f[i]; }} else {{ if (d==m) {{ g=g+f[i]; }} }} }}
  }}
  return(g);
}}
int i; intvec om; ideal J; ideal G; int tm;
"""]
    for om in uniq:
        sing.append(f"""om=intvec({",".join(map(str,om))}); J=0;
for (i=1;i<=size(TT);i++) {{ J[i]=inw(TT[i],om); }}
tm=timer; G=std(J);
print("OMEGA "+string(om)+" dim="+string(dim(G))+" size="+string(size(G))+" nterms="+string(size(J[1]))+","+string(size(J[size(J)]))+" t="+string(timer-tm));
""")
    sing.append("quit;\n")
    open(f"omega_t{t}.sing","w").write("".join(sing))
    t0=time.time()
    p=subprocess.run(["timeout",str(cap),"Singular","-q","--no-rc",f"omega_t{t}.sing"],capture_output=True,text=True)
    out=p.stdout; open(f"omega_t{t}.out","w").write(out)
    res=[l for l in out.splitlines() if l.startswith("OMEGA")]
    dims={}
    for l in res:
        d=int(l.split("dim=")[1].split()[0]); dims.setdefault(d,[]).append(l)
    print(f"t={t}: finished {len(res)}/{len(uniq)} omegas in {time.time()-t0:.1f}s (exit {p.returncode}); dim histogram: {{ {', '.join(f'{k}:{len(v)}' for k,v in sorted(dims.items()))} }}")
    for d in sorted(dims)[:2]:
        for l in dims[d][:6]: print("   ",l)
    if "error" in out.lower(): print("   SINGULAR ERROR lines:", [l for l in out.splitlines() if "error" in l.lower()][:3])
run(3, 300)
run(4, 480)
