#!/usr/bin/env python3
"""Prepare proof-preserving q4_1=1 and quadratic-field t=3 systems.

This driver starts from the already audited constant-pivot reduction, verifies
the positive grading on every residual generator, and uses the induced G_m
action to take the q4_1=1 slice on the c != 0 locus.  It then emits both:

* an exact-Q slice retaining a Rabinowitsch equation for the image of c; and
* an exact quadratic coefficient-field system over
  Q(y)/(147*y^2-84*y+11), where y=q7_1 and c is automatically a unit.

The optional quadratic-field affine pass divides only by explicitly checked
nonzero elements of that field.  Every inverse is verified modulo the
quadratic, and every pivot substitution is checked before it is accepted.
This program prepares Singular inputs but never invokes Singular.
"""

from __future__ import annotations

import dataclasses
import hashlib
import json
import math
import pathlib
import sys
import time

import sympy as sp


HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[2]
sys.path.insert(0, str(HERE))
import triangular_preprocess as tp  # noqa: E402


EXPECTED_TRIANGULAR_DRIVER_SHA256 = (
    "f2defb76d36172c541431b2fff04b34770438eef81167210fec404344fefbf93"
)

WEIGHTS = {
    "b1": 1,
    "b2": 2,
    "b3": 3,
    "b4": 4,
    "a1_0": 4,
    "a2_0": 8,
    "a4_0": 16,
    "a5_0": 20,
    "a6_0": 24,
    "a7_0": 28,
    "a8_0": 32,
    "a9_0": 36,
    "q2_0": 8,
    "q3_0": 12,
    "q4_0": 16,
    "q4_1": 13,
    "q5_0": 20,
    "q5_1": 17,
    "q6_0": 24,
    "q6_1": 21,
    "q7_0": 25,
    "q7_1": 26,
    "c": 65,
}


@dataclasses.dataclass
class SliceRow:
    source_index: int
    h_power: int
    monomial: tuple[int, int]
    expr: sp.Expr


@dataclasses.dataclass
class KPivot:
    step: int
    source_index: int
    h_power: int
    monomial: tuple[int, int]
    variable: sp.Symbol
    coefficient: sp.Expr
    inverse: sp.Expr
    step_rhs: sp.Expr
    remaining_rows_after: int
    expression_bytes_after: int


def sha256_file(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def weighted_degree(expr: sp.Expr, variables: list[sp.Symbol]) -> int:
    degrees = set()
    for monomial, _coefficient in sp.Poly(expr, *variables, domain=sp.QQ).terms():
        degrees.add(
            sum(exponent * WEIGHTS[str(variable)]
                for exponent, variable in zip(monomial, variables))
        )
    if len(degrees) != 1:
        raise AssertionError("row is not homogeneous: %s" % sorted(degrees))
    return degrees.pop()


def rational_associate(left: sp.Expr, right: sp.Expr,
                       variables: list[sp.Symbol]) -> sp.Rational | None:
    pleft = sp.Poly(left, *variables, domain=sp.QQ)
    pright = sp.Poly(right, *variables, domain=sp.QQ)
    if pleft.is_zero or pright.is_zero:
        return None
    ratio = sp.Rational(pleft.LC(), pright.LC())
    if (pleft - ratio * pright).is_zero:
        return ratio
    return None


def primitive_expr(expr: sp.Expr,
                   variables: list[sp.Symbol]) -> tuple[sp.Expr, sp.Rational]:
    poly, multiplier, _denominator, _content = (
        tp.primitive_integer_polynomial(expr, variables)
    )
    return poly.as_expr(), multiplier


def singular_expr(expr: sp.Expr, variables: list[sp.Symbol]) -> str:
    return tp.singular_polynomial(expr, variables)


def emit_actual_pair(lines: list[str]) -> None:
    lines.extend([
        "ring RAC=0,(gamma,pi),dp;",
        "poly FAC=pi;",
        "poly GAC=pi-(gamma^2)/2;",
        "poly JAC=diff(FAC,gamma)*diff(GAC,pi)-diff(FAC,pi)*diff(GAC,gamma);",
        'if (JAC==gamma) { print("CONTROL_ACTUAL_PAIR_PASS J=gamma"); }'
        ' else { print("CONTROL_ACTUAL_PAIR_FAIL"); }',
    ])


def emit_q_slice(rows: list[SliceRow], auxiliary: list[sp.Symbol], y: sp.Symbol,
                 method: str) -> str:
    if method not in ("std", "slimgb"):
        raise ValueError(method)
    T = sp.Symbol("T")
    variables = auxiliary + [y, T]
    polynomial_variables = auxiliary + [y]
    generators = [singular_expr(row.expr, polynomial_variables) for row in rows]
    # c = 10*y*(2-21*y)/343.  This primitive row is -343*(T*c-1).
    rab = 210 * T * y**2 - 20 * T * y + 343
    if sp.expand(rab + 343 * (T * 10 * y * (2 - 21*y) / 343 - 1)) != 0:
        raise AssertionError("slice Rabinowitsch image identity failed")
    generators.append(singular_expr(rab, variables))

    lines = [
        "// exact-Q normalized t=3 slice generated by t3_normalized_slice.py",
        "// q4_1=1 is existence-equivalent over Qbar on c!=0 by the verified grading",
        "// c=10*q7_1*(2-21*q7_1)/343; its nonvanishing is retained by T*c-1",
    ]
    emit_actual_pair(lines)
    lines.extend([
        "ring R=0,(%s),dp;" % ",".join(map(str, variables)),
        "option(redSB);",
        'if (nameof(basering)=="R") { print("CONTROL_RING_PASS R"); }'
        ' else { print("CONTROL_RING_FAIL"); }',
        'print("CONTROL_EMPTY_START");',
        "ideal CE=%s,T*%s-1;" % (y, y),
        "ideal GE=std(CE);",
        'if (typeof(GE)=="ideal" && nameof(basering)=="R")'
        ' { print("CONTROL_EMPTY_EXTRACT_RING_PASS"); }'
        ' else { print("CONTROL_EMPTY_EXTRACT_RING_FAIL"); }',
        'if (reduce(1,GE)==0) { print("CONTROL_EMPTY_PASS"); }'
        ' else { print("CONTROL_EMPTY_FAIL"); }',
        'print("CONTROL_NONEMPTY_START");',
        "ideal CN=%s-1,T*%s-1;" % (y, y),
        "ideal GN=std(CN);",
        'if (typeof(GN)=="ideal" && nameof(basering)=="R")'
        ' { print("CONTROL_NONEMPTY_EXTRACT_RING_PASS"); }'
        ' else { print("CONTROL_NONEMPTY_EXTRACT_RING_FAIL"); }',
        'if (reduce(1,GN)!=0) { print("CONTROL_NONEMPTY_PASS"); }'
        ' else { print("CONTROL_NONEMPTY_FAIL"); }',
        'print("MAIN_START t=3 normalized_q4_1=1 coefficient_field=Q '
        'slice_equations=%d chart_unknowns=%d plus_T=1");'
        % (len(rows), len(auxiliary) + 1),
        "ideal I=%s;" % ",\n".join(generators),
        "ideal G=%s(I);" % method,
        'print("MAIN_DONE basis_size=");',
        "size(G);",
        'if (reduce(1,G)==0) { print("MAIN_NORMALIZED_SLICE_EMPTY"); G; }'
        ' else { print("MAIN_NORMALIZED_SLICE_NONTRIVIAL");'
        ' print("BASIS_OUTPUT_TRUNCATED_TO_20");'
        ' int basis_cap=size(G); if (basis_cap>20) { basis_cap=20; }'
        ' for (int basis_i=1; basis_i<=basis_cap; basis_i++)'
        ' { G[basis_i]; } }',
        "quit;",
    ])
    return "\n".join(lines) + "\n"


class QuadraticField:
    def __init__(self, y: sp.Symbol, auxiliary: list[sp.Symbol]):
        self.y = y
        self.auxiliary = list(auxiliary)
        self.H = 147*y**2 - 84*y + 11
        self.domain = sp.QQ[tuple(self.auxiliary)]
        self.hpoly = sp.Poly(self.H, y, domain=self.domain)

    def reduce(self, expr: sp.Expr) -> sp.Expr:
        poly = sp.Poly(sp.expand(expr), self.y, domain=self.domain)
        return sp.expand(poly.rem(self.hpoly).as_expr())

    def inverse(self, coefficient: sp.Expr) -> sp.Expr:
        coefficient = self.reduce(coefficient)
        if coefficient.free_symbols - {self.y}:
            raise AssertionError("putative K coefficient contains chart variables")
        if coefficient == 0:
            raise ZeroDivisionError("zero coefficient in K")
        inverse = sp.invert(
            sp.Poly(coefficient, self.y, domain=sp.QQ),
            sp.Poly(self.H, self.y, domain=sp.QQ),
        ).as_expr()
        inverse = self.reduce(inverse)
        if self.reduce(coefficient * inverse - 1) != 0:
            raise AssertionError("quadratic-field inverse identity failed")
        return inverse


def field_associate(left: sp.Expr, right: sp.Expr, K: QuadraticField,
                    variables: list[sp.Symbol]) -> sp.Expr | None:
    """Return a in K* with left=a*right, or None.

    This is used only for exact duplicate removal and its identity is checked
    modulo H; it never guesses from names or leading monomials alone.
    """
    pleft = sp.Poly(left, *variables, domain=sp.QQ.frac_field(K.y))
    pright = sp.Poly(right, *variables, domain=sp.QQ.frac_field(K.y))
    if pleft.is_zero or pright.is_zero or pleft.monoms() != pright.monoms():
        return None
    ratio = K.reduce(pleft.LC() * K.inverse(pright.LC()))
    if K.reduce(left - ratio * right) == 0:
        return ratio
    return None


def deduplicate_k(rows: list[SliceRow], K: QuadraticField,
                  variables: list[sp.Symbol]):
    """Drop zero rows and literal duplicate reduced expressions.

    A prior version tested every pair for arbitrary K-star association.  That
    is proof-safe but needlessly expensive on the large low-band rows.  Exact
    duplicate removal gives the same quotient ideal and is linear-time.
    """
    kept: list[SliceRow] = []
    dropped: list[dict] = []
    representatives: dict[sp.Expr, SliceRow] = {}
    for row in rows:
        expr = K.reduce(row.expr)
        if expr == 0:
            dropped.append({
                "source_index": row.source_index,
                "reason": "zero_mod_H",
            })
            continue
        if expr not in representatives:
            representative = dataclasses.replace(row, expr=expr)
            representatives[expr] = representative
            kept.append(representative)
        else:
            representative = representatives[expr]
            dropped.append({
                "source_index": row.source_index,
                "reason": "literal_duplicate_mod_H",
                "representative_source_index": representative.source_index,
                "multiplier": "1",
            })
    return kept, dropped


def affine_candidates(rows: list[SliceRow], remaining: list[sp.Symbol],
                      K: QuadraticField):
    occurrences = {
        variable: sum(variable in row.expr.free_symbols for row in rows)
        for variable in remaining
    }
    candidates = []
    for row_index, row in enumerate(rows):
        terms = sp.Add.make_args(row.expr)
        for variable_index, variable in enumerate(remaining):
            if variable not in row.expr.free_symbols:
                continue
            coefficient_terms = []
            remainder_terms = []
            nonlinear = False
            for term in terms:
                exponent = term.as_powers_dict().get(variable, 0)
                if exponent == 0:
                    remainder_terms.append(term)
                elif exponent == 1:
                    coefficient_terms.append(term / variable)
                else:
                    nonlinear = True
                    break
            if nonlinear:
                continue
            coefficient = sp.Add(*coefficient_terms)
            remainder = sp.Add(*remainder_terms)
            if coefficient.free_symbols - {K.y} or coefficient == 0:
                continue
            if K.reduce(row.expr - coefficient*variable - remainder) != 0:
                raise AssertionError("affine decomposition failed")
            # Favor short remainders and variables occurring in few rows.
            # The inverse and expanded right side are computed only for the
            # chosen candidate, avoiding dozens of large speculative expands.
            score = (
                len(str(remainder)) * occurrences[variable],
                len(str(remainder)),
                occurrences[variable],
                len(str(row.expr)),
                row.source_index,
                variable_index,
            )
            candidates.append((score, row_index, variable_index, coefficient,
                               remainder))
    return candidates


def eliminate_over_k(rows: list[SliceRow], auxiliary: list[sp.Symbol],
                     K: QuadraticField, max_seconds: float = 600.0,
                     max_bytes: int = 12_000_000):
    started = time.monotonic()
    remaining = list(auxiliary)
    rows, initial_dropped = deduplicate_k(rows, K, remaining)
    pivots: list[KPivot] = []
    dropped = list(initial_dropped)
    terminal_unit = None

    while True:
        if time.monotonic() - started > max_seconds:
            raise RuntimeError("quadratic-field elimination time bound exceeded")
        constants = [row for row in rows
                     if not (row.expr.free_symbols - {K.y})]
        if constants:
            row = min(constants, key=lambda item: (len(str(item.expr)),
                                                   item.source_index))
            inverse = K.inverse(row.expr)
            terminal_unit = {
                "source_index": row.source_index,
                "constant": str(row.expr),
                "inverse": str(inverse),
                "identity_verified_mod_H": K.reduce(row.expr*inverse - 1) == 0,
            }
            break
        candidates = affine_candidates(rows, remaining, K)
        if not candidates:
            break
        (_score, row_index, variable_index, coefficient, remainder) = min(
            candidates, key=lambda item: item[0]
        )
        pivot_row = rows[row_index]
        variable = remaining[variable_index]
        inverse = K.inverse(coefficient)
        rhs = K.reduce(-inverse * remainder)
        if variable in rhs.free_symbols:
            raise AssertionError("pivot right side contains pivot variable")
        if K.reduce(pivot_row.expr.subs(variable, rhs)) != 0:
            raise AssertionError("K pivot does not kill its row")
        del rows[row_index]
        del remaining[variable_index]
        next_rows = []
        for row in rows:
            expr = row.expr
            if variable in expr.free_symbols:
                expr = K.reduce(expr.subs(variable, rhs))
            else:
                expr = K.reduce(expr)
            next_rows.append(dataclasses.replace(row, expr=expr))
        rows, newly_dropped = deduplicate_k(next_rows, K, remaining)
        dropped.extend(newly_dropped)
        expression_bytes = sum(len(str(row.expr)) for row in rows)
        if expression_bytes > max_bytes:
            raise RuntimeError("quadratic-field residual byte bound exceeded: %d"
                               % expression_bytes)
        pivots.append(KPivot(
            step=len(pivots) + 1,
            source_index=pivot_row.source_index,
            h_power=pivot_row.h_power,
            monomial=pivot_row.monomial,
            variable=variable,
            coefficient=coefficient,
            inverse=inverse,
            step_rhs=rhs,
            remaining_rows_after=len(rows),
            expression_bytes_after=expression_bytes,
        ))
        print("K_PIVOT step=%d source=%d variable=%s rows=%d vars=%d bytes=%d" % (
            len(pivots), pivot_row.source_index, variable, len(rows),
            len(remaining), expression_bytes), flush=True)
    return rows, remaining, pivots, dropped, terminal_unit, time.monotonic()-started


def emit_k_system(rows: list[SliceRow], remaining: list[sp.Symbol],
                  y: sp.Symbol, method: str, terminal_unit: dict | None) -> str:
    if method not in ("std", "slimgb"):
        raise ValueError(method)
    polynomial_variables = [y] + remaining
    generators = [singular_expr(row.expr, polynomial_variables) for row in rows]
    if terminal_unit is not None:
        # A checked nonzero coefficient-field constant is a unit.  Emitting 1
        # makes the final certificate explicit; the pivot table records its
        # preimage through the quotient isomorphisms.
        generators.append("1")
    if not generators:
        generators = ["0"]
    lines = [
        "// exact t=3 system over K=Q(y)/(147*y^2-84*y+11)",
        "// y denotes q7_1 after the rigorously normalized q4_1=1 slice",
        "// c=10*y*(2-21*y)/343 is a coefficient-field unit and is eliminated",
    ]
    emit_actual_pair(lines)
    lines.extend([
        "ring RC=(0,%s),(u,W),dp;" % y,
        "minpoly=147*%s^2-84*%s+11;" % (y, y),
        "number cbar=(10*%s*(2-21*%s))/343;" % (y, y),
        "number cbar_inverse=1/cbar;",
        'if (cbar*cbar_inverse==1) { print("CONTROL_C_UNIT_PASS"); }'
        ' else { print("CONTROL_C_UNIT_FAIL"); }',
        "ideal CE=u,W*u-1;",
        "ideal GE=std(CE);",
        'if (reduce(1,GE)==0) { print("CONTROL_EMPTY_PASS"); }'
        ' else { print("CONTROL_EMPTY_FAIL"); }',
        "ideal CN=u-1,W*u-1;",
        "ideal GN=std(CN);",
        'if (reduce(1,GN)!=0) { print("CONTROL_NONEMPTY_PASS"); }'
        ' else { print("CONTROL_NONEMPTY_FAIL"); }',
        "ring RK=(0,%s),(%s),dp;" % (y, ",".join(map(str, remaining))),
        "minpoly=147*%s^2-84*%s+11;" % (y, y),
        "option(redSB);",
        'if (nameof(basering)=="RK") { print("CONTROL_RING_PASS RK"); }'
        ' else { print("CONTROL_RING_FAIL"); }',
        'print("MAIN_START t=3 normalized_q4_1=1 coefficient_field=quadratic '
        'residual_equations=%d residual_unknowns=%d");'
        % (len(rows) + (1 if terminal_unit else 0), len(remaining)),
        "ideal I=%s;" % ",\n".join(generators),
        "ideal G=%s(I);" % method,
        'print("MAIN_DONE basis_size=");',
        "size(G);",
        'if (reduce(1,G)==0) { print("MAIN_QUADRATIC_FIELD_EMPTY"); G; }'
        ' else { print("MAIN_QUADRATIC_FIELD_NONTRIVIAL");'
        ' print("BASIS_OUTPUT_TRUNCATED_TO_20");'
        ' int basis_cap=size(G); if (basis_cap>20) { basis_cap=20; }'
        ' for (int basis_i=1; basis_i<=basis_cap; basis_i++)'
        ' { G[basis_i]; } }',
        "quit;",
    ])
    return "\n".join(lines) + "\n"


def main() -> None:
    if HERE != ROOT / "box/k16t3-20260903/preprocessed":
        raise RuntimeError("output directory invariant failed")
    if sha256_file(HERE / "triangular_preprocess.py") != EXPECTED_TRIANGULAR_DRIVER_SHA256:
        raise RuntimeError("triangular_preprocess.py hash differs from audited input")

    generic = tp.load_module(tp.GENERIC_DRIVER, "normalized_slice_generic")
    data = generic.build(t=3, gauged=True)
    reduction = tp.reduce_chart(data, 256, 600.0, 5_000_000)
    if len(reduction.rows) != 37 or len(reduction.remaining_variables) + 1 != 23:
        raise AssertionError("unexpected t=3 triangular reduction dimensions")

    all_variables = reduction.remaining_variables + [reduction.c]
    if set(map(str, all_variables)) != set(WEIGHTS):
        raise AssertionError("weight table does not match residual variables")
    homogeneity = []
    for row in reduction.rows:
        homogeneity.append({
            "source_index": row.source_index,
            "h_power": row.h_power,
            "monomial": list(row.monomial),
            "weighted_degree": weighted_degree(row.expr, all_variables),
        })

    by_name = {str(variable): variable for variable in all_variables}
    x = by_name["q4_1"]
    y = by_name["q7_1"]
    c = reduction.c
    Hhom = 11*x**4 - 84*x**2*y + 147*y**2
    H = Hhom.subs(x, 1)
    c_image = 10*x*y*(2*x**2 - 21*y) / 343

    c_rows = [row for row in reduction.rows if c in row.expr.free_symbols]
    if len(c_rows) != 1:
        raise AssertionError("expected exactly one c row")
    c_row = c_rows[0]
    c_coefficient = sp.diff(c_row.expr, c)
    c_remainder = sp.expand(c_row.expr - c_coefficient*c)
    if not c_coefficient.is_Rational or c_coefficient == 0:
        raise AssertionError("c row does not have a Q-constant pivot")
    solved_c = sp.expand(-c_remainder/c_coefficient)
    if sp.expand(solved_c - c_image) != 0:
        raise AssertionError("c-row closed form differs")

    base_matches = []
    for row in reduction.rows:
        if row is c_row:
            continue
        if row.expr.free_symbols <= {x, y}:
            ratio = rational_associate(row.expr, Hhom, all_variables)
            if ratio is not None:
                base_matches.append((row, ratio))
    if len(base_matches) != 1:
        raise AssertionError("expected one quadratic base row")
    base_row, base_ratio = base_matches[0]

    auxiliary = [variable for variable in reduction.remaining_variables
                 if variable not in (x, y)]
    q_variables = auxiliary + [y]
    sliced_raw = []
    for row in reduction.rows:
        if row is c_row:
            continue
        expr = sp.expand(row.expr.subs({x: 1, c: c_image.subs(x, 1)},
                                       simultaneous=True))
        sliced_raw.append(SliceRow(row.source_index, row.h_power,
                                  row.monomial, expr))

    # Replace each Q row by a primitive integral Q* associate and delete only
    # literal repeats of that canonical representative.
    q_rows: list[SliceRow] = []
    q_row_map = []
    canonical_to_index: dict[str, int] = {}
    for row in sliced_raw:
        primitive, multiplier = primitive_expr(row.expr, q_variables)
        key = str(primitive)
        if key not in canonical_to_index:
            canonical_to_index[key] = len(q_rows)
            q_rows.append(dataclasses.replace(row, expr=primitive))
            q_row_map.append({
                "source_index": row.source_index,
                "representative_source_index": row.source_index,
                "status": "kept",
                "integer_row_multiplier": str(multiplier),
            })
        else:
            representative = q_rows[canonical_to_index[key]]
            q_row_map.append({
                "source_index": row.source_index,
                "representative_source_index": representative.source_index,
                "status": "duplicate_dropped",
                "integer_row_multiplier": str(multiplier),
            })
    if not any(sp.expand(row.expr-H) == 0 for row in q_rows):
        # Primitive sign normalization may have chosen -H.
        if not any(sp.expand(row.expr+H) == 0 for row in q_rows):
            raise AssertionError("quadratic base row missing from Q slice")

    generated = []
    for method in ("std", "slimgb"):
        path = HERE / ("t3_normalized_Q_%s.sing" % method)
        path.write_text(emit_q_slice(q_rows, auxiliary, y, method),
                        encoding="utf-8")
        generated.append(path)

    # Pass to the exact quadratic coefficient field and remove H, which is now
    # the field's minimal polynomial rather than an ideal generator.
    K = QuadraticField(y, auxiliary)
    if K.reduce(H) != 0:
        raise AssertionError("quadratic reduction does not kill H")
    y_inverse = K.inverse(y)
    d_inverse = K.inverse(2 - 21*y)
    if K.reduce(y*y_inverse - 1) != 0 or K.reduce((2-21*y)*d_inverse - 1) != 0:
        raise AssertionError("base unit identities failed")
    k_input = []
    k_base_dropped = []
    for row in q_rows:
        expr = K.reduce(row.expr)
        if expr == 0:
            k_base_dropped.append(row.source_index)
        else:
            k_input.append(dataclasses.replace(row, expr=expr))
    if base_row.source_index not in k_base_dropped:
        raise AssertionError("identified base row did not vanish modulo H")

    (k_rows, k_remaining, pivots, k_dropped, terminal_unit,
     k_elapsed) = eliminate_over_k(k_input, auxiliary, K)

    pivot_lines = [
        "step\tsource_index_0based\th_power\tgamma_power\tpi_power"
        "\tpivot_variable\tcoefficient_in_K\tinverse_mod_H\tstep_rhs"
        "\tremaining_rows_after\texpression_bytes_after"
    ]
    for pivot in pivots:
        pivot_lines.append(
            "%d\t%d\t%d\t%d\t%d\t%s\t%s\t%s\t%s\t%d\t%d" % (
                pivot.step, pivot.source_index, pivot.h_power,
                pivot.monomial[0], pivot.monomial[1], pivot.variable,
                pivot.coefficient, pivot.inverse, pivot.step_rhs,
                pivot.remaining_rows_after, pivot.expression_bytes_after,
            )
        )
    pivot_path = HERE / "t3_normalized_K_pivots.tsv"
    pivot_path.write_text("\n".join(pivot_lines) + "\n", encoding="utf-8")
    generated.append(pivot_path)

    for method in ("std", "slimgb"):
        path = HERE / ("t3_normalized_K_%s.sing" % method)
        path.write_text(emit_k_system(k_rows, k_remaining, y, method,
                                      terminal_unit), encoding="utf-8")
        generated.append(path)

    audit = {
        "typing": "EXACT-SYMBOLIC-PREPROCESSING; no Singular result claimed",
        "source": {
            "generic_driver": str(tp.GENERIC_DRIVER.relative_to(ROOT)),
            "generic_driver_sha256": sha256_file(tp.GENERIC_DRIVER),
            "triangular_driver": str((HERE / "triangular_preprocess.py").relative_to(ROOT)),
            "triangular_driver_sha256": sha256_file(HERE / "triangular_preprocess.py"),
            "triangular_residual_equations": len(reduction.rows),
            "triangular_residual_unknowns_including_c": len(all_variables),
        },
        "grading": {
            "weights": WEIGHTS,
            "all_37_rows_homogeneous": len(homogeneity) == 37,
            "row_degrees": homogeneity,
            "q4_1_weight": 13,
            "c_weight": 65,
        },
        "scaling_equivalence": {
            "field": "algebraic closure of Q",
            "action": "v maps to lambda^weight(v)*v",
            "reason_q4_1_nonzero": "343*c=10*q4_1*q7_1*(2*q4_1^2-21*q7_1)",
            "normalization": "choose lambda with lambda^13*q4_1=1",
            "forward_and_reverse_existence_equivalence": True,
        },
        "c_row": {
            "source_index": c_row.source_index,
            "h_power": c_row.h_power,
            "monomial": list(c_row.monomial),
            "coefficient": str(c_coefficient),
            "solved_image": str(c_image),
            "identity_verified": True,
        },
        "base_row": {
            "source_index": base_row.source_index,
            "h_power": base_row.h_power,
            "monomial": list(base_row.monomial),
            "homogeneous_polynomial": str(Hhom),
            "associate_multiplier": str(base_ratio),
            "slice_minpoly": str(H),
            "discriminant": 588,
            "discriminant_is_square_in_Q": False,
            "irreducible_over_Q": True,
        },
        "base_units": {
            "y_inverse_mod_H": str(y_inverse),
            "two_minus_21y_inverse_mod_H": str(d_inverse),
            "H_at_0": str(H.subs(y, 0)),
            "H_at_2_over_21": str(H.subs(y, sp.Rational(2, 21))),
            "c_is_unit_in_K": True,
        },
        "Q_slice": {
            "raw_rows_after_c_elimination": len(sliced_raw),
            "rows_after_exact_duplicate_removal": len(q_rows),
            "auxiliary_unknowns": len(auxiliary),
            "unknowns_including_y": len(auxiliary) + 1,
            "plus_Rabinowitsch_T": 1,
            "row_map": q_row_map,
        },
        "K_elimination": {
            "input_rows_excluding_minpoly": len(k_input),
            "input_source_indices": [row.source_index for row in k_input],
            "base_or_zero_source_indices_removed_before_elimination": k_base_dropped,
            "input_auxiliary_unknowns": len(auxiliary),
            "pivot_count": len(pivots),
            "pivot_source_indices": [pivot.source_index for pivot in pivots],
            "pivot_variables": [str(pivot.variable) for pivot in pivots],
            "remaining_rows": len(k_rows),
            "remaining_row_sources": [
                {
                    "source_index": row.source_index,
                    "h_power": row.h_power,
                    "monomial": list(row.monomial),
                }
                for row in k_rows
            ],
            "remaining_unknowns": [str(v) for v in k_remaining],
            "dropped_rows": k_dropped,
            "terminal_unit": terminal_unit,
            "elapsed_seconds": round(k_elapsed, 6),
            "every_pivot_coefficient_inverse_checked_mod_H": True,
            "every_pivot_substitution_checked_mod_H": True,
        },
        "singular_launched_by_this_driver": False,
    }
    audit_path = HERE / "t3_normalized_audit.json"
    audit_path.write_text(json.dumps(audit, indent=2, sort_keys=True) + "\n",
                          encoding="utf-8")
    generated.append(audit_path)

    generated.append(HERE / "t3_normalized_slice.py")
    manifest_lines = ["%s  %s" % (sha256_file(path), path.name)
                      for path in sorted(generated, key=lambda item: item.name)]
    manifest_path = HERE / "SHA256SUMS.t3-normalized"
    manifest_path.write_text("\n".join(manifest_lines) + "\n", encoding="utf-8")
    print(json.dumps({
        "Q_slice_rows": len(q_rows),
        "K_input_rows": len(k_input),
        "K_pivots": len(pivots),
        "K_remaining_rows": len(k_rows),
        "K_remaining_unknowns": len(k_remaining),
        "K_terminal_unit": terminal_unit,
        "manifest": str(manifest_path),
        "manifest_sha256": sha256_file(manifest_path),
    }, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
