#!/usr/bin/env python3
"""Singular guided std on a Moh chart TSV, with the guided_gb control battery.

Ring is Q[parameters, T] (or F_p) under dp, generators = Jacobian rows + T*c-1.
Extraction used builder_fix y-first (lp(1),dp) on (y,x,params); those two
variables are already eliminated before this job.

Hilbert-driven std is attempted after a modular basis exists (lead-ideal
Hilbert series, all-1 weights). A modular UNIT is never promoted: exact-Q
confirmation is a separate std over characteristic 0.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(os.environ.get("ROOT", str(Path.home() / "moh-bigmem-20260905")))
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "lib"))


def sha256_path(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def read_rows(path: Path) -> list[str]:
    exprs: list[str] = []
    with path.open(encoding="utf-8") as handle:
        header = handle.readline()
        if not header.startswith("source_index|"):
            raise SystemExit(f"bad rows header in {path}: {header[:80]!r}")
        for line in handle:
            line = line.rstrip("\n")
            if not line.strip():
                continue
            parts = line.split("|", 4)
            if len(parts) != 5:
                raise SystemExit(f"bad row: {line[:80]!r}")
            expr = parts[4].strip()
            if not expr:
                raise SystemExit("empty generator")
            exprs.append(expr)
    if not exprs:
        raise SystemExit(f"no generators in {path}")
    return exprs


def load_variables(meta: dict) -> list[str]:
    variables = meta.get("variables")
    if not isinstance(variables, list) or not variables:
        raise SystemExit("metadata has no variables list")
    if variables[-1] != "c":
        raise SystemExit(f"localization variable c is not last: {variables[-1]!r}")
    if "T" in variables or "y" in variables or "x" in variables:
        raise SystemExit("solver ring unexpectedly contains y/x/T")
    return [str(v) for v in variables]


def emit_script(
    *,
    name: str,
    characteristic: int,
    variables: list[str],
    generators: list[str],
    hilbert_numerator: list[int] | None,
    hilbert_weights: list[int] | None,
) -> str:
    ring_vars = ",".join(variables + ["T"])
    nvars = len(variables) + 1
    lines = [
        "// generated by box/moh-bigmem-20260905/run_guided_job.py",
        f"// system={name}",
        f"// characteristic={characteristic}",
        f"// nvars={nvars}  (parameters + T); dp; T last",
        f"// extraction used builder_fix y-first (lp(1),dp) on (y,x,params)",
        f"ring R={characteristic},({ring_vars}),dp;",
        "option(redSB);",
        'if (nameof(basering)=="R") { print("CONTROL_RING_PASS R"); } else { print("CONTROL_RING_FAIL"); }',
        "ideal CE=c,T*c-1;",
        "ideal GE=std(CE);",
        'if (reduce(1,GE)==0) { print("CONTROL_EMPTY_PASS"); } else { print("CONTROL_EMPTY_FAIL"); }',
        "ideal CN=c-1,T*c-1;",
        "ideal GN=std(CN);",
        'if (reduce(1,GN)!=0) { print("CONTROL_NONEMPTY_PASS"); } else { print("CONTROL_NONEMPTY_FAIL"); }',
        f'print("MAIN_START equations={len(generators)} unknowns={len(variables)} char={characteristic} algorithm=std");',
        'print("GG__RUN main START");',
        "ideal GG_I_main =",
    ]
    for i, expr in enumerate(generators):
        comma = "," if i + 1 < len(generators) else ""
        lines.append(f"({expr}){comma}")
    lines.append(", (T*c-1);")
    lines += [
        'print("GG__GENERATOR_COUNT main "+string(size(GG_I_main)));',
        'print("GG__STD_BEGIN main");',
        "timer=1;",
        "int GG_TIMER_main=timer;",
    ]
    if hilbert_numerator and hilbert_weights:
        lines += [
            "intvec GG_HNUM_main=" + ",".join(str(v) for v in hilbert_numerator) + ";",
            "intvec GG_WTS_main=" + ",".join(str(v) for v in hilbert_weights) + ";",
            'print("GG__TARGET_HNUM main "+string(GG_HNUM_main));',
            'print("GG__WEIGHTS main "+string(GG_WTS_main));',
            "ideal GG_G_main=std(GG_I_main,GG_HNUM_main,GG_WTS_main);",
        ]
    else:
        lines.append("ideal GG_G_main=std(GG_I_main);")
    lines += [
        'print("GG__STD_SECONDS main "+string(timer-GG_TIMER_main));',
        "int GG_NF_ALL_main=1;",
        "int GG_NCHECK=size(GG_I_main);",
        "if (GG_NCHECK>64) { GG_NCHECK=64; }",
        "int gi;",
        "for (gi=1; gi<=GG_NCHECK; gi++)",
        "{",
        "  poly nf=reduce(GG_I_main[gi],GG_G_main);",
        "  if (nf!=0) { GG_NF_ALL_main=0; }",
        "}",
        'print("GG__NF_ALL_ZERO main "+string(GG_NF_ALL_main));',
        "poly GG_NF1_main=reduce(1,GG_G_main);",
        "int GG_UNIT_main=(GG_NF1_main==0);",
        'print("GG__UNIT main "+string(GG_UNIT_main));',
        'print("GG__NF1_SIZE main "+string(size(GG_NF1_main)));',
        'print("GG__BASIS_SIZE main "+string(size(GG_G_main)));',
        "int GG_DIM_main=dim(GG_G_main);",
        'print("GG__DIM main "+string(GG_DIM_main));',
        "int GG_VDIM_main=-1;",
        "if (GG_DIM_main==0)",
        "{",
        "  GG_VDIM_main=vdim(GG_G_main);",
        '  print("GG__VDIM main "+string(GG_VDIM_main));',
        "}",
        "else",
        "{",
        '  print("GG__VDIM main NONTERMINATING");',
        "}",
        "ideal GG_LEADRAW_main=lead(GG_G_main);",
        "ideal GG_LEADMIN_main=minbase(GG_LEADRAW_main);",
        'print("GG__LEAD_MIN_COUNT main "+string(size(GG_LEADMIN_main)));',
        "int lj; int lshow=size(GG_LEADMIN_main); if (lshow>12) { lshow=12; }",
        "for (lj=1; lj<=lshow; lj++)",
        "{",
        '  print("GG__LEAD "+string(lj)+" "+string(GG_LEADMIN_main[lj]));',
        "}",
        "int GG_LEAD_DIM_main=dim(GG_LEADMIN_main);",
        'print("GG__LEAD_DIM main "+string(GG_LEAD_DIM_main));',
        # Hilbert of the monomial lead ideal (always homogeneous). Used as a
        # hint for a later exact-Q pass; not itself a characteristic-0 proof.
        "intvec GG_HILB_main=hilb(GG_G_main,1);",
        'print("GG__HILB main "+string(GG_HILB_main));',
        "int GG_ACCEPT_main=(GG_NF_ALL_main==1);",
        'print("GG__ACCEPT main "+string(GG_ACCEPT_main));',
        'print("GG__RUN main END");',
        'print("GG__SCRIPT_DONE main 1");',
        "quit;",
        "",
    ]
    return "\n".join(lines)


def parse_markers(text: str) -> dict:
    def last_int(key: str) -> int | None:
        matches = re.findall(rf"GG__{key} main (-?\d+)", text)
        return int(matches[-1]) if matches else None

    unit = last_int("UNIT")
    dim = last_int("DIM")
    vdim = last_int("VDIM")
    basis = last_int("BASIS_SIZE")
    sample = last_int("SAMPLE_C1_T1_OTHERS0")
    leads = re.findall(r"GG__LEAD \d+ (.+)", text)
    hilb = re.findall(r"GG__HILB main (.+)", text)
    empty = "CONTROL_EMPTY_PASS" in text
    nonempty = "CONTROL_NONEMPTY_PASS" in text
    ring = "CONTROL_RING_PASS" in text
    return {
        "unit": None if unit is None else bool(unit),
        "dimension": dim,
        "vdim": vdim,
        "basis_size": basis,
        "sample_c1_t1_others0": None if sample is None else bool(sample),
        "lead_monomials_head": leads[:12],
        "hilb": hilb[-1].strip() if hilb else None,
        "control_ring": ring,
        "control_empty": empty,
        "control_nonempty": nonempty,
        "gg_script_done": "GG__SCRIPT_DONE main 1" in text,
        "gg_unit_line": unit,
    }


def run_one(
    *,
    script: Path,
    log_prefix: Path,
    timeout: int,
    cpus: int,
    memory_kb: int | None,
) -> dict:
    stdout_path = log_prefix.with_suffix(".out")
    stderr_path = log_prefix.with_suffix(".err")
    rc_path = log_prefix.with_suffix(".rc")
    rss_path = log_prefix.with_suffix(".rss.log")
    env = os.environ.copy()
    for key in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS"):
        env[key] = str(max(1, cpus))
    cmd = [
        "timeout",
        "--signal=TERM",
        "--kill-after=60s",
        f"{timeout}s",
        "/usr/bin/time",
        "-v",
        "stdbuf",
        "-oL",
        "-eL",
        "Singular",
        f"--cpus={cpus}",
        f"--threads={cpus}",
        f"--flint-threads={cpus}",
        "--no-rc",
        "-q",
        str(script),
    ]
    rss_path.write_text("", encoding="utf-8")
    sampler = subprocess.Popen(
        [
            "bash",
            "-c",
            f"while true; do echo utc=$(date -u +%Y-%m-%dT%H:%M:%SZ) >> {rss_path}; "
            f"pid=$(pgrep -n Singular || true); echo pid=$pid >> {rss_path}; "
            f"if [ -n \"$pid\" ] && [ -r /proc/$pid/status ]; then "
            f"awk '/VmPeak|VmSize|VmHWM|VmRSS/' /proc/$pid/status >> {rss_path}; fi; "
            f"sleep 20; done",
        ]
    )
    started = time.time()
    with stdout_path.open("w", encoding="utf-8") as out, stderr_path.open(
        "w", encoding="utf-8"
    ) as err:
        proc = subprocess.run(cmd, stdout=out, stderr=err, env=env)
    elapsed = time.time() - started
    sampler.kill()
    try:
        sampler.wait(timeout=2)
    except Exception:
        pass
    rc_path.write_text(f"{proc.returncode}\n", encoding="utf-8")
    stdout = stdout_path.read_text(encoding="utf-8", errors="replace")
    stderr = stderr_path.read_text(encoding="utf-8", errors="replace")
    markers = parse_markers(stdout)
    time_rss = None
    m = re.search(r"Maximum resident set size \(kbytes\):\s*(\d+)", stderr)
    if m:
        time_rss = int(m.group(1))
    sampled = [
        int(x) for x in re.findall(r"VmHWM:\s+(\d+)", rss_path.read_text(errors="replace"))
    ]
    return {
        "command": cmd,
        "returncode": proc.returncode,
        "elapsed_seconds": round(elapsed, 3),
        "timed_out": proc.returncode == 124,
        "gnu_time_peak_RSS_KiB": time_rss,
        "max_sampled_VmHWM_KiB": max(sampled) if sampled else None,
        "stdout_sha256": hashlib.sha256(stdout.encode()).hexdigest(),
        "stderr_sha256": hashlib.sha256(stderr.encode()).hexdigest(),
        "script_sha256": sha256_path(script),
        "markers": markers,
    }


def verdict_of(run: dict, characteristic: int) -> str:
    if run["timed_out"] or run["returncode"] == 124:
        return "TIMEOUT_NO_VERDICT"
    if run["returncode"] not in (0, None) and not run["markers"].get("gg_script_done"):
        if run["returncode"] and run["returncode"] >= 128:
            return "SIGNAL_OR_KILL_NO_VERDICT"
        return "ERROR_NO_VERDICT"
    markers = run["markers"]
    if not markers.get("gg_script_done"):
        return "HALT_OR_INCOMPLETE_NO_VERDICT"
    if not (markers.get("control_ring") and markers.get("control_empty") and markers.get("control_nonempty")):
        return "CONTROL_FAIL_NO_VERDICT"
    if markers.get("unit") is True:
        return "UNIT_MODULAR_ONLY" if characteristic > 0 else "UNIT_IDEAL_CHAR0"
    if markers.get("dimension") is None:
        return "INCOMPLETE_NO_VERDICT"
    if markers["dimension"] > 0:
        return "NONUNIT_POSDIM"
    return "NONUNIT_DIM0"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--workdir", type=Path, required=True)
    parser.add_argument("--meta", type=Path, required=True)
    parser.add_argument("--rows", type=Path, required=True)
    parser.add_argument("--name", required=True)
    parser.add_argument("--primes", default="1073741827")
    parser.add_argument("--timeout", type=int, default=10800)
    parser.add_argument("--cpus", type=int, default=32)
    parser.add_argument("--skip-char0", action="store_true")
    args = parser.parse_args()

    workdir: Path = args.workdir
    workdir.mkdir(parents=True, exist_ok=True)
    meta = json.loads(args.meta.read_text(encoding="utf-8"))
    variables = load_variables(meta)
    generators = read_rows(args.rows)
    primes = [int(p) for p in args.primes.split(",") if p.strip()]
    custody = {
        "name": args.name,
        "rows": str(args.rows.resolve()),
        "rows_sha256": sha256_path(args.rows),
        "rows_bytes": args.rows.stat().st_size,
        "meta": str(args.meta.resolve()),
        "meta_sha256": sha256_path(args.meta),
        "parameter_count": len(variables),
        "generator_count": len(generators),
        "ring": f"char,( {','.join(variables)}, T ), dp",
        "order": "dp",
        "localization": "T*c-1",
        "host": os.uname().nodename,
        "start_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    print(
        f"GUIDED_START name={args.name} gens={len(generators)} nvars={len(variables)+1} "
        f"rows_sha={custody['rows_sha256']}",
        flush=True,
    )

    runs: list[dict] = []
    remaining = args.timeout
    unit_modular = None
    hilbert_num = None
    for prime in primes:
        if remaining < 120:
            break
        slice_t = min(3600, remaining) if len(primes) > 1 else remaining
        if args.skip_char0:
            slice_t = remaining
        script = workdir / f"{args.name}_p{prime}.sing"
        script.write_text(
            emit_script(
                name=args.name,
                characteristic=prime,
                variables=variables,
                generators=generators,
                hilbert_numerator=None,
                hilbert_weights=None,
            ),
            encoding="utf-8",
        )
        print(f"MODULAR_START p={prime} timeout={slice_t} utc={time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}", flush=True)
        run = run_one(
            script=script,
            log_prefix=workdir / f"{args.name}_p{prime}",
            timeout=slice_t,
            cpus=args.cpus,
        )
        run["characteristic"] = prime
        run["verdict"] = verdict_of(run, prime)
        runs.append(run)
        remaining = max(0, remaining - int(run["elapsed_seconds"]))
        print(
            f"MODULAR_END p={prime} rc={run['returncode']} verdict={run['verdict']} "
            f"unit={run['markers'].get('unit')} dim={run['markers'].get('dimension')} "
            f"vdim={run['markers'].get('vdim')} rss={run.get('gnu_time_peak_RSS_KiB')} "
            f"wall={run['elapsed_seconds']}",
            flush=True,
        )
        if run["verdict"] == "UNIT_MODULAR_ONLY":
            unit_modular = prime
            break
        hilb = run["markers"].get("hilb")
        if hilb and run["verdict"].startswith("NONUNIT"):
            try:
                hilbert_num = [int(x) for x in hilb.replace("(", " ").replace(")", " ").split() if re.fullmatch(r"-?\d+", x)]
            except Exception:
                hilbert_num = None

    char0 = None
    if not args.skip_char0 and remaining >= 120:
        # Exact-Q. If a modular UNIT occurred, this is the required confirmation
        # on identical generators. A char-0 [1] from msolve is not this step.
        weights = [1] * (len(variables) + 1) if hilbert_num else None
        use_hint = bool(hilbert_num and weights and unit_modular is None)
        script = workdir / f"{args.name}_p0.sing"
        script.write_text(
            emit_script(
                name=args.name,
                characteristic=0,
                variables=variables,
                generators=generators,
                hilbert_numerator=hilbert_num if use_hint else None,
                hilbert_weights=weights if use_hint else None,
            ),
            encoding="utf-8",
        )
        print(
            f"EXACTQ_START timeout={remaining} hint={use_hint} "
            f"trigger_modular_unit={unit_modular} utc={time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}",
            flush=True,
        )
        run = run_one(
            script=script,
            log_prefix=workdir / f"{args.name}_p0",
            timeout=remaining,
            cpus=args.cpus,
        )
        run["characteristic"] = 0
        run["verdict"] = verdict_of(run, 0)
        run["hilbert_hint_used"] = use_hint
        char0 = run
        runs.append(run)
        print(
            f"EXACTQ_END rc={run['returncode']} verdict={run['verdict']} "
            f"unit={run['markers'].get('unit')} dim={run['markers'].get('dimension')} "
            f"vdim={run['markers'].get('vdim')} rss={run.get('gnu_time_peak_RSS_KiB')} "
            f"wall={run['elapsed_seconds']}",
            flush=True,
        )
    elif unit_modular is not None:
        print("EXACTQ_SKIPPED_NO_TIME_AFTER_MODULAR_UNIT", flush=True)

    final = "OPEN_NO_CHAR0_CERTIFICATE"
    if char0 is not None:
        final = char0["verdict"]
    elif unit_modular is not None:
        final = "MODULAR_UNIT_WITHOUT_EXACT_Q"
    elif runs:
        final = runs[-1]["verdict"] + "_MODULAR_ONLY"

    result = {
        "custody": custody,
        "final_verdict": final,
        "modular_unit_prime": unit_modular,
        "runs": runs,
        "end_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "fallacy_v2": (
            "A first-prime [1] from msolve is not a char-0 certificate; "
            "header-only/timeout/halt is not a result; modular UNIT is a signal only."
        ),
    }
    out = workdir / "guided_gb_result.json"
    out.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"GUIDED_FINAL verdict={final} json={out}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
