#!/usr/bin/env python3
"""Desk replay for the quartic branch-topology and monodromy ledger.

The geometric inputs are not encoded: finite-flat local length, the source
forest, the Arzhantsev--Zaidenberg classification, and weighted radial
global/local equivalence.  This script checks the finite S4 centralizers,
local-factor orbit bounds, transitive-subgroup rows, and the exact Euler/
graph identities used after those inputs.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from itertools import combinations, permutations


Permutation = tuple[int, int, int, int]
IDENTITY: Permutation = (0, 1, 2, 3)


def compose(left: Permutation, right: Permutation) -> Permutation:
    return tuple(left[right[index]] for index in range(4))  # type: ignore[return-value]


def generated(generators: tuple[Permutation, ...]) -> frozenset[Permutation]:
    closure = {IDENTITY, *generators}
    changed = True
    while changed:
        changed = False
        for left in tuple(closure):
            for right in tuple(closure):
                value = compose(left, right)
                if value not in closure:
                    closure.add(value)
                    changed = True
    return frozenset(closure)


def orbit(group: frozenset[Permutation], point: int) -> frozenset[int]:
    return frozenset(element[point] for element in group)


def transitive(group: frozenset[Permutation]) -> bool:
    return len(orbit(group, 0)) == 4


def cycle_type(perm: Permutation) -> tuple[int, ...]:
    unseen = set(range(4))
    lengths: list[int] = []
    while unseen:
        current = min(unseen)
        length = 0
        while current in unseen:
            unseen.remove(current)
            current = perm[current]
            length += 1
        lengths.append(length)
    return tuple(sorted(lengths, reverse=True))


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--mutate-allow-cone-rank-drop",
        action="store_true",
        help="replace a legal e=3 specialization by the forbidden u=2 rank drop",
    )
    args = parser.parse_args()

    s4 = tuple(permutations(range(4)))
    transpositions = tuple(p for p in s4 if cycle_type(p) == (2, 1, 1))
    three_cycles = tuple(p for p in s4 if cycle_type(p) == (3, 1))
    require(len(transpositions) == 6, "S4 transposition census")
    require(len(three_cycles) == 8, "S4 three-cycle census")

    centralizer_rows: dict[str, dict[str, int | bool]] = {}
    for label, element in (
        ("211", transpositions[0]),
        ("31", three_cycles[0]),
    ):
        centralizer = frozenset(
            g for g in s4 if compose(g, element) == compose(element, g)
        )
        require(not transitive(centralizer), f"{label} centralizer must be intransitive")
        centralizer_rows[label] = {
            "order": len(centralizer),
            "transitive": transitive(centralizer),
        }
    require(centralizer_rows["211"]["order"] == 4, "transposition centralizer order")
    require(centralizer_rows["31"]["order"] == 3, "three-cycle centralizer order")

    local_factor_groups = {
        "211": generated(((1, 0, 2, 3),)),
        "31": generated(((1, 2, 0, 3), (1, 0, 2, 3))),
        "22": generated(((1, 0, 2, 3), (0, 1, 3, 2))),
    }
    for partition, group in local_factor_groups.items():
        require(not transitive(group), f"local {partition} factorization is intransitive")

    # Enumerate all subgroups generated by at most two S4 elements.  Every
    # subgroup of S4 is two-generated; the resulting transitive orders are
    # the familiar C4/V4, D4, A4, S4 rows.
    subgroups = {generated((g,)) for g in s4}
    subgroups |= {generated(pair) for pair in combinations(s4, 2)}
    transitive_groups = tuple(group for group in subgroups if transitive(group))
    transitive_orders = sorted({len(group) for group in transitive_groups})
    require(transitive_orders == [4, 8, 12, 24], "transitive S4 subgroup orders")
    require(
        all(len(group) != 4 or all(len(orbit(group, i)) == 4 for i in range(4))
            for group in transitive_groups),
        "transitive order-four actions must be regular",
    )

    fixed_inertia_rows: dict[str, dict[str, int | bool]] = {}
    for group in transitive_groups:
        fixed_inertia = tuple(
            element
            for element in group
            if cycle_type(element) in {(2, 1, 1), (3, 1)}
        )
        inertia_closure = generated(fixed_inertia)
        row = {
            "fixed_inertia_count": len(fixed_inertia),
            "closure_order": len(inertia_closure),
            "closure_transitive": transitive(inertia_closure),
        }
        key = str(len(group))
        if key in fixed_inertia_rows:
            require(
                fixed_inertia_rows[key] == row,
                f"all transitive order-{key} rows must have the same inertia ledger",
            )
        else:
            fixed_inertia_rows[key] = row
    require(
        sorted(
            int(order)
            for order, row in fixed_inertia_rows.items()
            if row["closure_transitive"]
        )
        == [12, 24],
        "fixed-sheet inertia can normally generate only A4 or S4",
    )

    a4_groups = tuple(group for group in transitive_groups if len(group) == 12)
    require(len(a4_groups) == 1, "unique A4 subgroup in S4")
    a4 = a4_groups[0]
    pair_stabilizer = generated(((1, 0, 2, 3), (0, 1, 3, 2)))
    a4_pair_local = a4 & pair_stabilizer
    require(len(a4_pair_local) == 2, "A4 intersection with S2xS2")
    require(
        not any(cycle_type(element) == (3, 1) for element in a4_pair_local),
        "an A4 (2,2) local group cannot contain divisorial three-cycle inertia",
    )

    # Exhaustively replay the graph and Euler cancellations on a bounded
    # integer box.  h=b0(R), k=b0(B), beta=b1(B), and n22 are linked by
    # beta=n22-h+k.  The two expressions for e(U) must coincide.
    ledger_rows = 0
    for h in range(1, 7):
        for k in range(1, h + 1):
            for beta in range(0, 7):
                n22 = h - k + beta
                if n22 < 0:
                    continue
                e_b = k - beta
                require(e_b == h - n22, "branch Euler/quotient-graph identity")
                for e_t31 in range(-6, 7):
                    for n4 in range(0, 5):
                        e_u_strata = 4 - 2 * e_b - e_t31 - 2 * (n22 + n4)
                        e_u_cancelled = 4 - 2 * h - e_t31 - 2 * n4
                        require(e_u_strata == e_u_cancelled, "(2,2) Euler cancellation")
                        ledger_rows += 1

    # A weighted-cone component is C*.  At a special point on a generic
    # e-sheet ramification component, local length >= e gives u_special <=
    # 4-e=u_generic.  The mutation is the precise illegal 3 -> 2 rank drop.
    cone_rows = [(2, 2), (2, 1), (2, 0), (3, 1), (3, 0)]
    if args.mutate_allow_cone_rank_drop:
        cone_rows.append((3, 2))
    cone_defect = 0
    for ramification_index, u_special in cone_rows:
        u_generic = 4 - ramification_index
        require(
            u_special <= u_generic,
            "specialization cannot lower the local ramified factor rank",
        )
        cone_defect += u_special - u_generic
    require(cone_defect <= 0, "weighted-cone exceptional Euler corrections")

    payload = {
        "status": "PASS-QUARTIC-BRANCH-TOPOLOGY",
        "s4_order": len(s4),
        "centralizer_rows": centralizer_rows,
        "local_factor_group_orders": {
            key: len(value) for key, value in sorted(local_factor_groups.items())
        },
        "transitive_subgroup_orders": transitive_orders,
        "fixed_inertia_rows_by_group_order": fixed_inertia_rows,
        "a4_pair_local_order": len(a4_pair_local),
        "regular_order_four_rows": sum(
            1 for group in transitive_groups if len(group) == 4
        ),
        "ledger_rows_checked": ledger_rows,
        "cone_defect_fixture": cone_defect,
        "acyclic_positive_euler_survives": False,
    }
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    payload["payload_sha256"] = hashlib.sha256(canonical.encode()).hexdigest()
    print(json.dumps(payload, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
