#!/usr/bin/env python3
"""Desk replay for the cyclic-monodromy edge of the cubic affine survivor.

This is deliberately tiny.  It verifies the permutation statement used when
the connected branch curve is a coordinate affine line: a connected
three-sheet cover of its complement has cyclic monodromy generated by a
3-cycle, whereas the promoted cubic fibre type (2,1) gives a transposition.
No geometric classification is encoded here.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from itertools import permutations


Permutation = tuple[int, int, int]


def compose(left: Permutation, right: Permutation) -> Permutation:
    return tuple(left[right[i]] for i in range(3))  # type: ignore[return-value]


def power(perm: Permutation, exponent: int) -> Permutation:
    result: Permutation = (0, 1, 2)
    for _ in range(exponent):
        result = compose(perm, result)
    return result


def orbit(perm: Permutation, point: int) -> tuple[int, ...]:
    return tuple(sorted({power(perm, exponent)[point] for exponent in range(6)}))


def cycle_type(perm: Permutation) -> tuple[int, ...]:
    unseen = set(range(3))
    lengths: list[int] = []
    while unseen:
        start = min(unseen)
        current = start
        length = 0
        while current in unseen:
            unseen.remove(current)
            current = perm[current]
            length += 1
        lengths.append(length)
    return tuple(sorted(lengths, reverse=True))


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--mutate-transposition-to-3cycle",
        action="store_true",
        help="deliberately destroy the (2,1) fibre-type premise",
    )
    args = parser.parse_args()

    all_permutations = tuple(permutations(range(3)))
    rows = []
    for perm in all_permutations:
        transitive = len(orbit(perm, 0)) == 3
        rows.append(
            {
                "permutation": "".join(str(i) for i in perm),
                "cycle_type": list(cycle_type(perm)),
                "cyclic_action_transitive": transitive,
            }
        )

    transpositions = [row for row in rows if row["cycle_type"] == [2, 1]]
    three_cycles = [row for row in rows if row["cycle_type"] == [3]]
    require(len(transpositions) == 3, "S3 must have three transpositions")
    require(len(three_cycles) == 2, "S3 must have two 3-cycles")
    require(
        all(not row["cyclic_action_transitive"] for row in transpositions),
        "a cyclic group generated by a transposition cannot act transitively on 3 letters",
    )
    require(
        all(row["cyclic_action_transitive"] for row in three_cycles),
        "every 3-cycle must act transitively on 3 letters",
    )

    selected_type = [3] if args.mutate_transposition_to_3cycle else [2, 1]
    selected = [row for row in rows if row["cycle_type"] == selected_type]
    require(selected_type == [2, 1], "mutation changed the charged cubic fibre type")
    require(
        all(not row["cyclic_action_transitive"] for row in selected),
        "the coordinate-line complement would admit the charged connected cover",
    )

    payload = {
        "status": "PASS-CUBIC-AFFINE-SMOOTH-BRANCH-MONODROMY",
        "s3_order": len(rows),
        "transposition_count": len(transpositions),
        "three_cycle_count": len(three_cycles),
        "charged_fibre_type": selected_type,
        "charged_cyclic_action_transitive": False,
    }
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    payload["payload_sha256"] = hashlib.sha256(canonical.encode()).hexdigest()
    print(json.dumps(payload, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
