#!/usr/bin/env python3
"""Desk replay for the all-degree acyclic-companion obstruction.

The geometric proof uses the Arzhantsev--Zaidenberg normal forms for reduced
simply connected plane curves.  This script checks only the finite
permutation lemmas used after that classification:

* a nonidentity permutation with a fixed point has a nonempty proper fixed
  set, and its full centralizer preserves that set;
* the cyclic group generated by such a permutation is intransitive;
* a point stabilizer is intransitive (the weighted-cone case);
* independently based companion permutations can generate a transitive
  group, while identity "inertia" destroys properness of the fixed set.

Canonical representatives of every relevant cycle type are exhaustively
checked through degree eight.  The theorem for arbitrary degree is the
one-line fixed-set argument, not an inference from this finite replay.
No curve classification, inertia theorem, or cover realization is encoded.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from itertools import permutations


Permutation = tuple[int, ...]


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def identity(degree: int) -> Permutation:
    return tuple(range(degree))


def compose(left: Permutation, right: Permutation) -> Permutation:
    require(len(left) == len(right), "permutations must have equal degree")
    return tuple(left[right[index]] for index in range(len(left)))


def fixed_set(perm: Permutation) -> frozenset[int]:
    return frozenset(index for index, image in enumerate(perm) if image == index)


def support(perm: Permutation) -> frozenset[int]:
    return frozenset(index for index, image in enumerate(perm) if image != index)


def orbit(group: frozenset[Permutation], point: int) -> frozenset[int]:
    return frozenset(element[point] for element in group)


def generated(generators: tuple[Permutation, ...]) -> frozenset[Permutation]:
    degree = len(generators[0]) if generators else 0
    closure = {identity(degree), *generators}
    changed = True
    while changed:
        changed = False
        elements = tuple(closure)
        for left in elements:
            for right in elements:
                product = compose(left, right)
                if product not in closure:
                    closure.add(product)
                    changed = True
    return frozenset(closure)


def integer_partitions(total: int, ceiling: int | None = None) -> tuple[tuple[int, ...], ...]:
    """Return decreasing integer partitions of total."""

    if total == 0:
        return ((),)
    maximum = total if ceiling is None else min(total, ceiling)
    result: list[tuple[int, ...]] = []
    for first in range(maximum, 0, -1):
        for tail in integer_partitions(total - first, first):
            result.append((first, *tail))
    return tuple(result)


def canonical_permutation(cycle_lengths: tuple[int, ...]) -> Permutation:
    degree = sum(cycle_lengths)
    result = list(range(degree))
    start = 0
    for length in cycle_lengths:
        cycle = tuple(range(start, start + length))
        for index, value in enumerate(cycle):
            result[value] = cycle[(index + 1) % length]
        start += length
    return tuple(result)


def cycle_type(perm: Permutation) -> tuple[int, ...]:
    unseen = set(range(len(perm)))
    lengths: list[int] = []
    while unseen:
        start = min(unseen)
        current = start
        length = 0
        while current in unseen:
            unseen.remove(current)
            current = perm[current]
            length += 1
        lengths.append(length)
    return tuple(sorted(lengths, reverse=True))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--mutate-drop-centrality",
        action="store_true",
        help="deliberately let arbitrary permutations act on the spine fixed set",
    )
    args = parser.parse_args()

    summaries: dict[str, dict[str, int]] = {}
    mutation_exercised = False

    for degree in range(2, 9):
        symmetric_group = tuple(permutations(range(degree)))
        relevant_types = tuple(
            partition
            for partition in integer_partitions(degree)
            if 1 in partition and partition != (1,) * degree
        )
        multiple_companion_types = 0
        centralizer_pairs = 0

        for partition in relevant_types:
            spine = canonical_permutation(partition)
            require(cycle_type(spine) == partition, "canonical cycle type drift")
            fixed = fixed_set(spine)
            require(0 < len(fixed) < degree, "spine fixed set must be nonempty proper")
            if len(fixed) >= 2:
                multiple_companion_types += 1

            centralizer = tuple(
                element
                for element in symmetric_group
                if compose(element, spine) == compose(spine, element)
            )
            allowed = symmetric_group if args.mutate_drop_centrality else centralizer
            if args.mutate_drop_centrality:
                mutation_exercised = True
            for element in allowed:
                transported = frozenset(element[index] for index in fixed)
                require(
                    transported == fixed,
                    "an allowed comb image moved a spine-fixed sheet out of the fixed set",
                )
            centralizer_pairs += len(centralizer)

            line_image = generated((spine,))
            require(
                len(orbit(line_image, min(fixed))) < degree,
                "a line image with a companion cannot be transitive",
            )

        point_stabilizer = frozenset(
            element for element in symmetric_group if element[0] == 0
        )
        require(
            orbit(point_stabilizer, 0) == frozenset({0}),
            "a cone companion point must remain fixed",
        )
        require(
            len(point_stabilizer) < len(symmetric_group),
            "a point stabilizer must be a proper subgroup",
        )

        summaries[str(degree)] = {
            "cycle_types_nonidentity_with_fixed_points": len(relevant_types),
            "cycle_types_with_multiple_fixed_points": multiple_companion_types,
            "centralizer_elements_checked": centralizer_pairs,
            "point_stabilizer_order": len(point_stabilizer),
        }

    require(
        not args.mutate_drop_centrality or mutation_exercised,
        "centrality mutation was not exercised",
    )

    # Missing-companion control: a local/global 3-cycle is transitive.
    three_cycle: Permutation = (1, 2, 0)
    three_cycle_group = generated((three_cycle,))
    require(not fixed_set(three_cycle), "the 3-cycle control must have no companion")
    require(
        orbit(three_cycle_group, 0) == frozenset({0, 1, 2}),
        "the missing-companion control must be transitive",
    )

    # Disconnected-branch control: differently labelled local companions can
    # generate S3, so the proof must use centrality or global=local topology.
    transposition_01: Permutation = (1, 0, 2)
    transposition_12: Permutation = (0, 2, 1)
    disconnected_group = generated((transposition_01, transposition_12))
    require(len(disconnected_group) == 6, "two companion transpositions must generate S3")
    require(
        orbit(disconnected_group, 0) == frozenset({0, 1, 2}),
        "the disconnected companion control must be transitive",
    )
    disconnected_support_sum = len(support(transposition_01)) + len(
        support(transposition_12)
    )
    require(
        disconnected_support_sum == 4,
        "the disconnected control must saturate the d+1 support bound",
    )
    require(
        3 - disconnected_support_sum == -1,
        "the parallel-line Euler control must have upper bound -1",
    )

    # Nonnormal conductor control: identity spine monodromy has every sheet
    # fixed, so its centralizer supplies no proper invariant subset.
    identity_two = identity(2)
    require(
        fixed_set(identity_two) == frozenset({0, 1}),
        "identity inertia must have an improper full fixed set",
    )
    require(
        len(generated((identity_two, (1, 0)))) == 2,
        "a tooth can connect the degree-two nonnormal conductor control",
    )

    payload = {
        "status": "PASS-ALL-DEGREE-ACYCLIC-COMPANION",
        "degrees_exhausted": [2, 8],
        "by_degree": summaries,
        "degree_two_relevant_spine_types": summaries["2"][
            "cycle_types_nonidentity_with_fixed_points"
        ],
        "missing_companion_control_transitive": True,
        "disconnected_companion_control_order": len(disconnected_group),
        "disconnected_support_sum": disconnected_support_sum,
        "parallel_line_euler_upper_bound": 3 - disconnected_support_sum,
        "nonnormal_identity_spine_fixed_set_is_proper": False,
    }
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    payload["payload_sha256"] = hashlib.sha256(canonical.encode()).hexdigest()
    print(json.dumps(payload, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
