#!/usr/bin/env python3
"""Enumerate unmarked D9 root/fibre signatures with exact integer checks.

The reflection subsystem convention is the one generated by all roots in
each signed-coordinate block.  A balanced block on m coordinates is
``B_m=A_{m-1}``; an unbalanced block is ``U_2=A1+A1``, ``U_3=A3``, or
``U_m=D_m`` for m>=4.  Unused coordinates are geometrically the one-blowup
smooth fibre block B_1.

This program classifies only unmarked weighted fibre-forest combinatorial
types.  It does not enumerate effective embeddings, blowup locations,
carrier curves, target-image labels, or analytic/projective realizations.
"""

from __future__ import annotations

import argparse
from collections import Counter
import json
from pathlib import Path
from typing import Iterable


SCHEMA = "jc2.d9_fibre_signatures.v1"
TOTAL_BLOWUPS = 9


def block_species() -> tuple[tuple[str, int], ...]:
    return tuple((kind, size) for size in range(2, 10) for kind in ("B", "U"))


def signatures() -> Iterable[tuple[int, tuple[int, ...]]]:
    """Yield (unused, multiplicities) for every two-coloured partition of <=9."""
    species = block_species()

    def visit(index: int, remaining: int, values: tuple[int, ...]):
        if index == len(species):
            yield remaining, values
            return
        _, size = species[index]
        for multiplicity in range(remaining // size + 1):
            yield from visit(
                index + 1,
                remaining - size * multiplicity,
                values + (multiplicity,),
            )

    yield from visit(0, TOTAL_BLOWUPS, ())


def matvec(matrix: list[list[int]], vector: list[int]) -> list[int]:
    return [sum(a * b for a, b in zip(row, vector)) for row in matrix]


def fibre_block(kind: str, size: int) -> dict[str, object]:
    """Return the canonical weighted final fibre tree for B_size or U_size."""
    if kind == "B":
        # size blowups: two (-1)-ends and size-1 exceptional (-2)-vertices.
        self_intersections = [-1] + [-2] * (size - 1) + [-1]
        beta = [1] * (size + 1)
        edges = [[i + 1, i + 2] for i in range(size)]
        root_vertices = list(range(2, size + 1))
        root_type = "zero" if size == 1 else f"A{size - 1}"
        marked_original_orbits = size // 2 + 1
    elif kind == "U" and size == 2:
        # The two A1 singularities are separated by the multiplicity-two (-1).
        self_intersections = [-2, -2, -1]
        beta = [1, 1, 2]
        edges = [[1, 3], [2, 3]]
        root_vertices = [1, 2]
        root_type = "A1+A1"
        marked_original_orbits = 1
    elif kind == "U" and 3 <= size <= 9:
        # Root vertex 1 is the beta-two fork; 2,3 are beta-one short leaves.
        # Vertices 4,...,size form the long root arm.  Vertex size+1 is (-1).
        self_intersections = [-2] * size + [-1]
        beta = [2, 1, 1] + [2] * (size - 3) + [2]
        edges = [[1, 2], [1, 3]]
        if size == 3:
            edges.append([1, 4])
        else:
            edges.append([1, 4])
            edges.extend([[i, i + 1] for i in range(4, size + 1)])
        root_vertices = list(range(1, size + 1))
        root_type = "A3" if size == 3 else f"D{size}"
        marked_original_orbits = 1
    else:
        raise ValueError((kind, size))

    vertex_count = len(self_intersections)
    matrix = [[0] * vertex_count for _ in range(vertex_count)]
    for index, value in enumerate(self_intersections):
        matrix[index][index] = value
    for left, right in edges:
        matrix[left - 1][right - 1] = 1
        matrix[right - 1][left - 1] = 1

    assert len(edges) == vertex_count - 1
    assert matvec(matrix, beta) == [0] * vertex_count
    assert sum(
        multiplicity
        for multiplicity, square in zip(beta, self_intersections)
        if square == -1
    ) == 2
    assert all(square in (-1, -2) for square in self_intersections)
    assert all(
        square + 2 == (1 if square == -1 else 0)
        for square in self_intersections
    )

    return {
        "tag": f"{kind}{size}",
        "blowups": size,
        "root_type": root_type,
        "root_vertices": root_vertices,
        "self_intersections": self_intersections,
        "fibre_multiplicities_beta": beta,
        "edges": edges,
        "marked_original_component_orbits": marked_original_orbits,
    }


def coefficient_of_product(exponents: dict[int, int], degree: int) -> int:
    """Coefficient of product_k (1-x^k)^(-exponents[k]) through degree."""
    values = [0] * (degree + 1)
    values[0] = 1
    for size, colours in sorted(exponents.items()):
        for _ in range(colours):
            for target in range(size, degree + 1):
                values[target] += values[target - size]
    return values[degree]


def signature_record(unused: int, values: tuple[int, ...]) -> dict[str, object]:
    species = block_species()
    blocks = [
        {"tag": f"{kind}{size}", "multiplicity": multiplicity}
        for (kind, size), multiplicity in zip(species, values)
        if multiplicity
    ]
    support = TOTAL_BLOWUPS - unused
    fibre_count = unused + sum(values)
    root_components = 0
    unbalanced_blocks = 0
    root_rank = 0
    for (kind, size), multiplicity in zip(species, values):
        if not multiplicity:
            continue
        if kind == "B":
            root_components += multiplicity
            root_rank += multiplicity * (size - 1)
        else:
            unbalanced_blocks += multiplicity
            root_components += multiplicity * (2 if size == 2 else 1)
            root_rank += multiplicity * size
    return {
        "unused_coordinates_B1": unused,
        "support_size": support,
        "blocks": blocks,
        "fibre_count": fibre_count,
        "root_rank": root_rank,
        "root_connected_components": root_components,
        "root_connectivity": (
            "zero" if root_components == 0 else "connected" if root_components == 1 else "disconnected"
        ),
        "span_saturated": unbalanced_blocks <= 1,
    }


def build_payload() -> dict[str, object]:
    records = [signature_record(unused, values) for unused, values in signatures()]
    records.sort(
        key=lambda record: (
            record["support_size"],
            tuple((block["tag"], block["multiplicity"]) for block in record["blocks"]),
        )
    )
    connectivity = Counter(record["root_connectivity"] for record in records)
    support = Counter(record["support_size"] for record in records)
    saturated = [record for record in records if record["span_saturated"]]
    saturated_connectivity = Counter(record["root_connectivity"] for record in saturated)

    assert len(records) == 115
    assert connectivity == {"zero": 1, "connected": 15, "disconnected": 99}
    assert [support[index] for index in range(10)] == [1, 0, 2, 2, 5, 6, 13, 16, 30, 40]
    assert len(saturated) == 75
    assert saturated_connectivity == {"zero": 1, "connected": 15, "disconnected": 59}

    marked_exponents = {1: 1}
    marked_exponents.update({size: size // 2 + 2 for size in range(2, 10)})
    marked_count = coefficient_of_product(marked_exponents, TOTAL_BLOWUPS)

    blocks = [fibre_block("B", 1)]
    blocks.extend(
        fibre_block(kind, size)
        for size in range(2, 10)
        for kind in ("B", "U")
    )
    return {
        "schema": SCHEMA,
        "scope": {
            "ambient_root_lattice": "D9(-1)",
            "equivalence": "W(D9) on unmarked full reflection subsystems",
            "geometric_output": "unmarked weighted fibre-forest combinatorial types",
            "excluded": [
                "effective exceptional-curve embeddings",
                "blowup locations and moduli",
                "original-fibre-component markings",
                "carrier and target-image labels",
                "Cartier decorations and analytic/projective realizability",
            ],
        },
        "counts": {
            "all_reflection_subsystem_signatures": len(records),
            "zero": connectivity["zero"],
            "connected": connectivity["connected"],
            "disconnected": connectivity["disconnected"],
            "span_saturated_all": len(saturated),
            "span_saturated_disconnected": saturated_connectivity["disconnected"],
            "marked_original_component_species_count": marked_count,
        },
        "support_histogram_0_through_9": [support[index] for index in range(10)],
        "generating_functions": {
            "unmarked": "(1-x)^-1 product_{m=2}^9 (1-x^m)^-2",
            "original_component_marked": "(1-x)^-1 product_{m=2}^9 (1-x^m)^-(floor(m/2)+2)",
        },
        "fibre_blocks": blocks,
        "signatures": records,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, help="write canonical JSON here")
    args = parser.parse_args()
    encoded = json.dumps(build_payload(), sort_keys=True, separators=(",", ":")) + "\n"
    if args.output:
        args.output.write_text(encoded, encoding="utf-8")
    else:
        print(encoded, end="")


if __name__ == "__main__":
    main()
