#!/usr/bin/env python3
"""Independent verification of the ACTUAL-STABILIZER screen.

Re-implements the orbit-multiset tree from Moh (9)-(13) with an explicit
centre-support modulus Lcal (Lemma A), independently of the charged driver,
then cross-checks against the charged StabTree on every row.
"""
import importlib.util, json, sys, time
from fractions import Fraction as F
from functools import lru_cache
from math import gcd, lcm
from pathlib import Path

LANE = Path("/tmp/jc2-lane.LKbCI2/inputs")
ROOT = Path("/home/ubuntu/jc2")

def load(name, path):
    sp = importlib.util.spec_from_file_location(name, path)
    m = importlib.util.module_from_spec(sp); sys.modules[name] = m
    sp.loader.exec_module(m); return m

B  = load("moh_skeleton_full", LANE / "moh_skeleton_full.py")
sys.modules["moh_skeleton_full_frozen"] = B
OP = load("opus5_probe_live", ROOT / "box/wholetree-drivers-20260903/opus5_probe.py")

# ---------------- independent tree ----------------------------------------
class Tree:
    """Moh pp.200-201 (7),(9),(10),(11),(12),(13) + p.171 ODE + p.188 Prop 5.6.

    centre_L is the modulus of the field k((t^{1/centre_L})) generated by the
    ACTUAL centre of the current disc:  start 1; a selected factor pi (zero
    centre coefficient) leaves it; a selected factor pi-a, a != 0, replaces it
    by lcm(centre_L, den delta).  actual=False restores Moh (8)'s L.
    """
    def __init__(self, n, m, Ms, actual=True):
        self.n, self.m = n, m
        full = [-m] + list(Ms)
        self.s = s = len(full)
        self.M = {i+1: full[i] for i in range(s)}
        d = [n]
        for M in full: d.append(gcd(d[-1], M))
        self.d = {i+1: d[i] for i in range(len(d))}
        self.ns, self.ms = n // self.d[2], m // self.d[2]
        self.actual = actual

    def delta(self, i, high):
        num, den = F(self.n - self.M[i]), F(self.n - self.M[self.s] - 1)
        for k, V in zip(range(i+1, self.s+1), high):
            num *= V*(self.n - self.M[k]) - self.d[k]
            den *= V*(self.n - self.M[k-1]) - self.d[k]
        return 1 - num/den

    def run(self, V):
        # top window: Lemma 5.3 p.185  d_s > V_s > d_s/2
        if not (self.d[self.s] > V[self.s] > F(self.d[self.s], 2)): return None
        need = tuple(V[i] for i in range(self.s-1, 1, -1))
        self.memo = {}
        return self.node(self.s-1, (V[self.s],), True, need, 1)

    def node(self, j, high, danger, need, cL):
        k = (j, high, danger, need, cL)
        if k in self.memo: return self.memo[k]
        r = self._node(j, high, danger, need, cL); self.memo[k] = r; return r

    def _node(self, j, high, danger, need, cL):
        dl = self.delta(j, high)
        A  = (cL*dl).denominator                  # (8) at the ACTUAL modulus
        Vp = high[0]
        P  = Vp*self.d[j]//self.d[j+1]            # deg p(pi), (9) LHS
        Q  = Vp*(self.n-self.M[j])//self.d[j+1]   # deg q(pi), Prop 4.6(2)
        lo = F(self.d[j], self.n-self.M[j])       # (7) / Def 5.1(2) threshold
        if need is not None and not (F(need[0]) > lo): return None
        removable = (dl.denominator == 1 and dl <= 0)   # p.190 (x,y)->(x,y-ax-b)

        def child(v, is_zero, tail):
            nL = cL if (self.actual and is_zero) else lcm(cL, dl.denominator)
            nd = danger and (is_zero or removable)
            nh = (v,) + high
            if j == 2:
                d1 = self.delta(1, nh)
                A1 = (nL*d1).denominator
                c12 = (self.ns*v % A1 == 0) and ((self.ms*v-1) % A1 == 0)
                c13 = (self.ms*v % A1 == 0) and ((self.ns*v-1) % A1 == 0)
                if nd: return None                      # Prop 5.6 p.188
                return {"A1": A1} if (c12 or c13) else None
            return self.node(j-1, nh, nd, tail, nL)

        for b in range(P % A, P+1, A):                  # (11): mult(0)=jA+sq
            if b > 0 and P == Q*b: continue             # ODE p.171 / A.3
            zmaj = F(b) > lo
            if zmaj and child(b, True, None) is None: continue
            total = (P-b)//A                            # nonzero mass / A
            cap   = (Q - (1 if b > 0 else 0))//A        # #orbits <= Q, 4.6(3),(4)
            coins = []
            for v in range(1, total+1):                 # (10): v <= tri
                if P == Q*v: continue
                maj = F(v) > lo
                if maj and child(v, False, None) is None: continue
                coins.append((v, maj))
            modes = [("free", ())] if need is None else []
            if need is not None:
                if b == need[0] and zmaj: modes.append(("zero", ()))
                if any(v == need[0] for v, _ in coins) and need[0] <= total:
                    modes.append(("nonzero", (need[0],)))
            for mode, pre in modes:
                sc = None
                if mode == "zero":    sc = child(b, True, need[1:] or None)
                elif mode == "nonzero": sc = child(need[0], False, need[1:] or None)
                if mode != "free" and sc is None: continue
                sol = self.fill(total - sum(pre), cap - len(pre), tuple(coins),
                                zmaj or bool(pre))
                if sol is not None:
                    return {"j": j, "A": A, "P": P, "b": b, "mode": mode,
                            "orbits": list(pre)+list(sol), "cL": cL,
                            "delta": str(dl), "child": sc}
        return None

    def fill(self, target, kmax, coins, has_major):
        if kmax < 0 or target < 0: return None
        @lru_cache(maxsize=None)
        def go(rem, kk, idx, hm):
            if rem == 0: return () if hm else None
            if kk == 0: return None
            for i in range(idx, len(coins)):
                v, maj = coins[i]
                if v > rem: break
                t = go(rem-v, kk-1, i, hm or maj)
                if t is not None: return (v,)+t
            return None
        return go(target, kmax, 0, has_major)

def op_actual(n, m, Ms, V): return Tree(n, m, Ms, True ).run(V) is not None
def op_coarse(n, m, Ms, V): return Tree(n, m, Ms, False).run(V) is not None

def op_live(n, m, Ms, V):
    T = OP.Tree(n, m, Ms, gate=False, ode=True, capacity=False, passport=False)
    T.recenter = True; T._memo = {}; T.why = []
    if not (T.d[T.s] > V[T.s] > F(T.d[T.s], 2)): return False
    need = tuple(V[i] for i in range(T.s-1, 1, -1))
    return T.ok(T.s-1, (V[T.s],), True, need) is not None

# ---------------- population ----------------------------------------------
if __name__ == "__main__":
    t0 = time.monotonic()
    NMAX = int(sys.argv[1]) if len(sys.argv) > 1 else 200
    rows = []
    for n in range(16, NMAX+1):
        for (m, Ms, V) in B.census(n, Kmin=2, full=True):
            rows.append((n, m, Ms, V))
    print("census (1)-(13) rows:", len(rows))
    co = ac = 0; mism = 0; lost = []; kept = []
    for (n, m, Ms, V) in rows:
        c = op_coarse(n, m, Ms, V)
        l = op_live(n, m, Ms, V)
        if c != l: mism += 1
        a = op_actual(n, m, Ms, V)
        if c: co += 1
        if a: ac += 1; kept.append((n, m, Ms, tuple(V[i] for i in range(2, len(Ms)+2))))
        if c and not a: lost.append((n, m, Ms, tuple(V[i] for i in range(2, len(Ms)+2))))
        assert not (a and not c), ("actual not a subset of coarse", n, m, Ms, V)
    print("coarse operative:", co, " live-probe mismatch:", mism)
    print("actual operative:", ac, " lost:", len(lost), " gained:", ac-(co-len(lost)))
    from collections import Counter
    print("kept by s:", dict(sorted(Counter(len(r[2])+1 for r in kept).items())))
    print("kept n<=100:", sum(1 for r in kept if r[0] <= 100))
    json.dump({"kept": [list(map(lambda z: z if not isinstance(z, tuple) else list(z), r)) for r in kept],
               "n_lost": len(lost)},
              open("/home/ubuntu/jc2/box/actual-stabilizer-soundness-20260906/verify.json", "w"))
    print("elapsed %.1fs" % (time.monotonic()-t0))
