#!/usr/bin/env python3
"""PROP 5.5(k): the k-generalisation of Moh Prop 5.5 (pp.186-188) for J = c*gamma^k.

Closed form derived in the report:
    delta_1' = (k+1) * (P*U2 - R) / ( R * (P*V2 - 1) ),      R = n' - M2' - 1
    delta_2' = -(k+1)/R
with P = n* + m* = (n'-M1')/d2', d2' = gcd(n',m'), U2' = d2' - V2'.
Cross-checked against (k+1)*Def 5.1(3) [phi_delta.py, Grok lane] on every row.
"""
from fractions import Fraction as F
from math import gcd

# ---- Moh Def 5.1(3), p.179 (SOURCE-READ) ------------------------------------
def def51(n, M, d, V, s, i):
    num = F(n - M[i]); den = F(n - M[s] - 1)
    for j in range(i+1, s+1):
        num *= (V[j]*(n - M[j]) - d[j])
        den *= (V[j]*(n - M[j-1]) - d[j])
    return 1 - num/den

def phi(n, m, M2, V2, k):
    """(k+1) * Def5.1(3) at s'=2 -> (delta_2', delta_1')."""
    d2 = gcd(n, m)
    M = {1: -m, 2: M2}; d = {1: n, 2: d2, 3: gcd(d2, M2)}; V = {2: V2, 3: gcd(d2, M2)}
    return (k+1)*def51(n,M,d,V,2,2), (k+1)*def51(n,M,d,V,2,1)

def closed(n, m, M2, V2, k):
    """Closed form of the same two radii."""
    d2 = gcd(n, m); P = (n + m)//d2; U2 = d2 - V2; R = n - M2 - 1
    return F(-(k+1), R), F((k+1)*(P*U2 - R), R*(P*V2 - 1))

# ---- TEST-55(k): the k-form of Moh's pp.187-188 chain ------------------------
def test55k(n, m, M2, V2, k, lattice="delta2"):
    d2 = gcd(n, m); nstar = n//d2; mstar = m//d2; P = nstar + mstar
    U2 = d2 - V2; R = n - M2 - 1
    out = {"n":n,"m":m,"M2":M2,"V2":V2,"k":k,"d2":d2,"nstar":nstar,"mstar":mstar,
           "P":P,"U2":U2,"R":R}
    kills = []; notes = []
    # (H) structural hypotheses of Def 5.1(2) / strict tower
    if not (V2 > F(d2, R+1)):   kills.append("H-major: V2 <= d2/(n-M2) violates Def 5.1(2)")
    if not (V2 < d2):           kills.append("H-strict: V2 >= d2 (D_1 = D_2, tower not strict)")
    d1p, d1 = closed(n, m, M2, V2, k)
    out["delta2"] = d1p; out["delta1"] = d1
    A = d1.denominator; B = d1.numerator
    out["A"] = A; out["B"] = B
    dg = nstar*V2      # deg_pi g_sigma            (Def 5.1(1))
    dT = mstar*V2      # deg_pi T^psi_{1,sigma}    (Def 5.1(1))
    out["deg_g"] = dg; out["deg_T"] = dT
    if A <= 1:
        notes.append("A'=1: Galois step vacuous (needs A'>1)")
        out["verdict"] = "INAPPLICABLE(A'=1)"; out["kills"]=kills; out["notes"]=notes
        return out
    # -- Galois step (Moh p.188).  CORRECTED MODULUS.
    #    sigma_1 = sum a_j t^j + pi t^{delta_1'} ; let L = index of the lattice
    #    generated by ZZ and the exponents j of the common part.  Conjugating
    #    k((t^{1/(L*Aa)})) over k((t^{1/L})) sends pi -> zeta pi with zeta of order
    #        Aa = A' / gcd(A', L)                       [Moh p.188 is L = 1]
    #    hence every pi-exponent of g_sigma is == deg g_sigma (mod Aa), same for T.
    #    L >= denom(delta_2') always (delta_2' is a common-part exponent); the
    #    controls all realise L = denom(delta_2') exactly.
    L = 1 if lattice == "moh" else d1p.denominator
    Aa = A // gcd(A, L)
    out["L"] = L; out["Aa"] = Aa
    dg = nstar*V2      # deg_pi g_sigma            (Def 5.1(1) + Prop 4.6(4))
    dT = mstar*V2      # deg_pi T^psi_{1,sigma}    (Def 5.1(1) + Prop 4.6(5))
    out["deg_g"] = dg; out["deg_T"] = dT
    rg, rT = dg % Aa, dT % Aa
    out["res"] = (rg, rT)
    if Aa > 1:
        if rg == 0 and rT == 0:
            kills.append("GALOIS: Aa | both degrees => pi | g_s' and pi | T_s' "
                         "=> (g_s',T_s') != 1, contradicting D = c != 0")
        if rg != 0 and rT != 0:
            # both leading exponent classes are nonzero => pi | g_s and pi | T_s
            kills.append("GALOIS: Aa | neither degree => pi | g_s and pi | T_s "
                         "=> (g_s,T_s) != 1, contradicting D = c != 0")
        # Prop A.5 (p.207): g_s * T_s has only SIMPLE roots => the smallest
        # exponent present in each is <= 1, and it is == deg mod Aa.
        if rg > 1:
            kills.append("A5-SIMPLE: pi^%d || g_s (deg g_s = %d == %d mod %d) "
                         "=> multiple root at 0, contra Prop A.5" % (rg,dg,rg,Aa))
        if rT > 1:
            kills.append("A5-SIMPLE: pi^%d || T_s (deg T_s = %d == %d mod %d) "
                         "=> multiple root at 0, contra Prop A.5" % (rT,dT,rT,Aa))
    if Aa > dg and Aa > dT and dg >= 1 and dT >= 1:
        kills.append("MONOMIAL: Aa > max(deg g_s, deg T_s) => both pi-monomials "
                     "=> D(.,.,g_s,T_s) == 0, contradicting D = nonzero const")
    # -- divisibility chain (Moh p.188 restated; needs rho = R/(k+1) integral)
    if R % (k+1) == 0:
        rho = R//(k+1)
        num = P*U2 - R; den = rho*(P*V2 - 1)
        g0 = gcd(abs(num), den) if num else den
        Psi = (rho*(k+1) + 1)*V2 - d2          # = rho*(k+1)*V2 - U2 > 0 by Def 5.1(2)
        out["rho"] = rho; out["g0"] = g0; out["Psi"] = Psi
        out["g0|rho*Psi"] = (rho*Psi) % g0 == 0
        if rho == 1 and Aa == A:
            # Galois branch (Moh p.188): A'|n*V2 => A'|m*V2-1 => (A',V2)=1 => V2|D;
            # symmetric branch => V2|E.  Either way g0 = D+E >= V2.
            out["g0>=V2"] = g0 >= V2; out["g0|Psi"] = Psi % g0 == 0
            if (rg == 0) != (rT == 0):        # the XOR branch, where the chain applies
                if g0 < V2:
                    kills.append("DIVCHAIN: g0 = D+E < V2' contradicts V2'|D (resp. V2'|E)")
                if V2 > Psi:
                    kills.append("MASTER: V2' > (k+2)V2'-d2' >= g0 >= V2'  "
                                 "(Moh's V2 > V2-U2 = C(D+E) >= D >= V2)")
    out["kills"] = kills; out["notes"] = notes
    out["verdict"] = "KILLED" if kills else "SURVIVES"
    return out

def show(lab, r):
    print("  %-34s d2=%d n*=%d m*=%d P=%d U2=%d R=%d | d2'=%-5s d1'=%-6s A'=%-3d "
          "deg(g_s,T_s)=(%d,%d) Aa=%-4s res=%-8s | %s"
          % (lab, r["d2"], r["nstar"], r["mstar"], r["P"], r["U2"], r["R"],
             r["delta2"], r["delta1"], r.get("A",1), r.get("deg_g",0), r.get("deg_T",0),
             r.get("Aa","-"), str(r.get("res","-")), r["verdict"]))
    for kk in r["kills"]: print("        KILL:", kk)
    for nn in r["notes"]: print("        note:", nn)

if __name__ == "__main__":
    P207 = [("(16,12) V2=3  k=1", 16,12,13,3,1, F(-1),   F(1,4)),
            ("(21,14) V2=2  k=1", 21,14,16,2,1, F(-1,2), F(7,6)),
            ("(21,14) V2=5  k=1", 21,14,18,5,1, F(-1),   F(1,3)),
            ("(15,10) V2=3  k=2", 15,10,11,3,2, F(-1),   F(1,2)),
            ("(15,10) V2=2  k=2", 15,10,11,2,2, F(-1),   F(4,3))]
    print("== A. closed form == (k+1)*Def5.1(3) == printed p.207 ==")
    allok = True
    for lab,n,m,M2,V2,k,p2,p1 in P207:
        c = closed(n,m,M2,V2,k); f = phi(n,m,M2,V2,k)
        ok = (c == f == (p2,p1)); allok &= ok
        print("  %-20s closed=%-14s phi=%-14s printed=%-14s %s"
              % (lab, str(c), str(f), str((p2,p1)), "MATCH" if ok else "FAIL"))
    print("  all 10 rationals, closed form == Phi == printed:", allok)

    print("\n== B. TEST-55(k) on Moh's five descended rows (p.207) ==")
    for lab,n,m,M2,V2,k,_,_ in P207: show(lab, test55k(n,m,M2,V2,k))

    print("\n== C. TEST-55(k) on the D=105 descended pair G2, G3 (delta 17(q)) ==")
    for lab,n,m,M2,V2,k in [("G2 (15,10;4;1;X^4)",15,10,4,1,4),
                            ("G3 (21,14;8;1;X^2)",21,14,8,1,2)]:
        show(lab, test55k(n,m,M2,V2,k))

    print("\n== D. k=0 (Moh's own Prop 5.5): the test must kill EVERY admissible row ==")
    bad = []; tot = 0
    for n in range(3, 41):
        for m in range(2, n):
            d2 = gcd(n,m)
            if d2 < 2: continue
            M2 = n-2               # k=0, delta_2 = -1  =>  R = 1
            for V2 in range(1, d2+1):
                r = test55k(n,m,M2,V2,0)
                if r["kills"] and r["kills"][0].startswith("H-"): continue
                tot += 1
                if r["verdict"] != "KILLED": bad.append((n,m,V2,r))
    print("  admissible k=0 rows scanned: %d ; survivors: %d" % (tot, len(bad)))
    for n,m,V2,r in bad[:10]: show("SURVIVOR (%d,%d) V2=%d"%(n,m,V2), r)

    print("\n== E. census: how much does TEST-55(k) cut for k >= 1, delta_2' = -1? ==")
    from collections import Counter
    for kk in range(0, 7):
        tot=0; killed=0; why=Counter()
        for n in range(3, 41):
            for m in range(2, n):
                d2 = gcd(n,m)
                if d2 < 2: continue
                M2 = n - kk - 2
                if M2 <= -m or (n - M2 - 1) != kk+1: continue
                for V2 in range(1, d2+1):
                    r = test55k(n,m,M2,V2,kk)
                    if r["kills"] and r["kills"][0].startswith("H-"): continue
                    if r["verdict"].startswith("INAPPLIC"): continue
                    tot += 1
                    if r["verdict"]=="KILLED":
                        killed += 1; why[r["kills"][0].split(":")[0]] += 1
        print("   k=%d  admissible rows %4d  killed %4d (%5.1f%%)  by %s"
              % (kk, tot, killed, 100.0*killed/max(tot,1), dict(why)))

    print("\n== F. the master inequality is SHARP: genuine family saturates it ==")
    for p,q in [(2,2),(3,2),(3,3),(4,3),(5,2),(6,4)]:
        k=p-1; n=p*q; m=p; M2=n-k-2
        r=test55k(n,m,M2,1,k)
        print("   P=pi^%d-gamma^%d, Q=P^%d+a*pi : (n',m')=(%d,%d) k=%d V2'=1 "
              "d2'=%d (k+1)V2'=%d  -> %s" % (p,p,q,n,m,k,r["d2"],(k+1)*1,r["verdict"]))
