#!/usr/bin/env python3
"""Fail-closed preflight core for a D43 common-integral emitter.

This file deliberately does *not* reconstruct rows from modular residues.
It provides only the pieces that are already pinned by committed sources:

* exact arithmetic in the a00pp coefficient algebra generated by
  zeta_42, r3, A1, A2 and h;
* simple-root/primitive-root and denominator gates for specialization;
* separate source-existence and banked-presentation certification shells.

The basis order is (zeta42, r3, A1, A2, h), with exponent bounds
(12, 2, 3, 3, 2).  Arithmetic uses Fraction coefficients and the relations

    Phi_42(zeta42) = 0,       r3^2 = 3,
    A1^3 = 3 + r3,            A2^3 = 3 - r3,
    2 h^2 = 3.

Scope: residue-A, a00pp radical frame.  The 36-fiber selector algebra has
independent h1/h2 signs and is intentionally not claimed here.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from dataclasses import dataclass
from fractions import Fraction
from typing import Dict, Iterable, Mapping, MutableMapping, Tuple


# Low-to-high coefficients.  This is the literal polynomial asserted in
# cases/r1_experiment.py, not z^42 - 1 (which admits imprimitive roots).
PHI42 = (1, 1, 0, -1, -1, 0, 1, 0, -1, -1, 0, 1, 1)
PHI42_DERIV = tuple(i * PHI42[i] for i in range(1, len(PHI42)))

BASIS_SHAPE = (12, 2, 3, 3, 2)
BASIS_RANK = math.prod(BASIS_SHAPE)
SOURCE_NEWTON_DENOMINATORS = (1, 2, 3, 4, 5, 6)
SOURCE_DENOMINATOR_PRIMES = (2, 3, 5)
ETALE_LOCALIZATION_PRIMES = (2, 3, 5, 7)

Exp = Tuple[int, int, int, int, int]
ZERO_EXP: Exp = (0, 0, 0, 0, 0)


def _poly_eval(coefficients: Iterable[int], x: int, modulus: int) -> int:
    value = 0
    for coefficient in reversed(tuple(coefficients)):
        value = (value * x + coefficient) % modulus
    return value


def _prime_support(n: int) -> Tuple[int, ...]:
    n = abs(int(n))
    if n < 1:
        raise ValueError("denominator must be nonzero")
    out = []
    divisor = 2
    while divisor * divisor <= n:
        if n % divisor == 0:
            out.append(divisor)
            while n % divisor == 0:
                n //= divisor
        divisor += 1 if divisor == 2 else 2
    if n > 1:
        out.append(n)
    return tuple(out)


class RadicalCoefficient:
    """Sparse exact element in the 432-term canonical quotient basis."""

    def __init__(self, terms: Mapping[Exp, Fraction] | None = None):
        raw: Dict[Exp, Fraction] = {}
        for exponent, coefficient in (terms or {}).items():
            if len(exponent) != 5 or any(int(e) != e or e < 0 for e in exponent):
                raise ValueError("bad radical exponent %r" % (exponent,))
            coefficient = Fraction(coefficient)
            if coefficient:
                raw[tuple(int(e) for e in exponent)] = (
                    raw.get(tuple(exponent), Fraction(0)) + coefficient
                )
        self._terms = self._normalize(raw)

    @classmethod
    def scalar(cls, value) -> "RadicalCoefficient":
        value = Fraction(value)
        return cls({ZERO_EXP: value}) if value else cls()

    @classmethod
    def generator(cls, name: str) -> "RadicalCoefficient":
        positions = {"zeta42": 0, "r3": 1, "A1": 2, "A2": 3, "h": 4}
        if name not in positions:
            raise KeyError(name)
        exponent = [0] * 5
        exponent[positions[name]] = 1
        return cls({tuple(exponent): Fraction(1)})

    @staticmethod
    def _normalize(raw: MutableMapping[Exp, Fraction]) -> Dict[Exp, Fraction]:
        pending = [(exponent, Fraction(coefficient))
                   for exponent, coefficient in raw.items() if coefficient]
        out: Dict[Exp, Fraction] = {}
        while pending:
            exponent, coefficient = pending.pop()
            if not coefficient:
                continue
            z, r, a1, a2, h = exponent
            if z >= 12:
                # z^12 = -sum_{j=0}^{11} PHI42[j] z^j.
                base = z - 12
                for j, phi_coefficient in enumerate(PHI42[:-1]):
                    if phi_coefficient:
                        pending.append(((base + j, r, a1, a2, h),
                                        -coefficient * phi_coefficient))
            elif r >= 2:
                pending.append(((z, r - 2, a1, a2, h), 3 * coefficient))
            elif a1 >= 3:
                pending.append(((z, r, a1 - 3, a2, h), 3 * coefficient))
                pending.append(((z, r + 1, a1 - 3, a2, h), coefficient))
            elif a2 >= 3:
                pending.append(((z, r, a1, a2 - 3, h), 3 * coefficient))
                pending.append(((z, r + 1, a1, a2 - 3, h), -coefficient))
            elif h >= 2:
                pending.append(((z, r, a1, a2, h - 2),
                                Fraction(3, 2) * coefficient))
            else:
                out[exponent] = out.get(exponent, Fraction(0)) + coefficient
                if not out[exponent]:
                    del out[exponent]
        assert all(all(e < bound for e, bound in zip(exponent, BASIS_SHAPE))
                   for exponent in out)
        return out

    @staticmethod
    def _coerce(value) -> "RadicalCoefficient":
        return value if isinstance(value, RadicalCoefficient) \
            else RadicalCoefficient.scalar(value)

    @property
    def terms(self) -> Dict[Exp, Fraction]:
        return dict(self._terms)

    def __bool__(self) -> bool:
        return bool(self._terms)

    def __add__(self, other) -> "RadicalCoefficient":
        other = self._coerce(other)
        terms = dict(self._terms)
        for exponent, coefficient in other._terms.items():
            terms[exponent] = terms.get(exponent, Fraction(0)) + coefficient
        return RadicalCoefficient(terms)

    __radd__ = __add__

    def __neg__(self) -> "RadicalCoefficient":
        return RadicalCoefficient({e: -c for e, c in self._terms.items()})

    def __sub__(self, other) -> "RadicalCoefficient":
        return self + (-self._coerce(other))

    def __rsub__(self, other) -> "RadicalCoefficient":
        return self._coerce(other) - self

    def __mul__(self, other) -> "RadicalCoefficient":
        other = self._coerce(other)
        raw: Dict[Exp, Fraction] = {}
        for left_exp, left_coefficient in self._terms.items():
            for right_exp, right_coefficient in other._terms.items():
                exponent = tuple(a + b for a, b in zip(left_exp, right_exp))
                raw[exponent] = (raw.get(exponent, Fraction(0)) +
                                 left_coefficient * right_coefficient)
        return RadicalCoefficient(raw)

    __rmul__ = __mul__

    def __pow__(self, exponent: int) -> "RadicalCoefficient":
        if int(exponent) != exponent or exponent < 0:
            raise ValueError("only nonnegative integral powers are supported")
        result = RadicalCoefficient.scalar(1)
        base = self
        exponent = int(exponent)
        while exponent:
            if exponent & 1:
                result = result * base
            base = base * base
            exponent >>= 1
        return result

    def __eq__(self, other) -> bool:
        try:
            other = self._coerce(other)
        except (TypeError, ValueError):
            return False
        return self._terms == other._terms

    def denominator_prime_support(self) -> Tuple[int, ...]:
        support = set()
        for coefficient in self._terms.values():
            support.update(_prime_support(coefficient.denominator))
        return tuple(sorted(support))

    def assert_source_denominators(self) -> None:
        extra = set(self.denominator_prime_support()) - set(SOURCE_DENOMINATOR_PRIMES)
        if extra:
            raise ValueError("unregistered source denominator primes %s" %
                             sorted(extra))

    def specialize(self, modulus: int, frame: "RootFrame") -> int:
        values = (frame.zeta42, frame.r3, frame.A1, frame.A2, frame.h)
        total = 0
        for exponent, coefficient in self._terms.items():
            denominator = coefficient.denominator
            if math.gcd(denominator, modulus) != 1:
                raise ZeroDivisionError("denominator %d is not a unit mod %d" %
                                        (denominator, modulus))
            term = coefficient.numerator % modulus
            term = term * pow(denominator, -1, modulus) % modulus
            for value, power in zip(values, exponent):
                term = term * pow(value, power, modulus) % modulus
            total = (total + term) % modulus
        return total

    def json_terms(self):
        return [{"exponents": list(exponent),
                 "coefficient": [coefficient.numerator,
                                 coefficient.denominator]}
                for exponent, coefficient in sorted(self._terms.items())]


def collapse_r1_ring_element(element) -> Dict[Tuple[int, int], RadicalCoefficient]:
    """Collapse one committed ``r1_experiment.R_ext`` element at a00pp.

    An R_ext key is ``(z,A1,A2,W1,HW1,W2,HW2,EB)`` and its value is the
    pair ``(c0,c1)`` representing ``c0+c1*r3``.  This adapter performs only
    the literal a00pp substitution ``HW_i = h*W_i``.  It refuses the frozen
    B radical, negative Laurent exponents, or malformed keys rather than
    inventing a convention.  The returned key is the polynomial-coordinate
    monomial ``(W1 exponent, W2 exponent)``; its value is an exact radical
    coefficient.
    """
    out: Dict[Tuple[int, int], RadicalCoefficient] = {}
    for key, k3_coefficient in element.items():
        if len(key) != 8:
            raise ValueError("bad R_ext key %r" % (key,))
        za, ea1, ea2, ew1, ehw1, ew2, ehw2, eB = (int(e) for e in key)
        if eB:
            raise ValueError("EB exponent survives a00pp collapse: %r" %
                             (key,))
        if any(e < 0 for e in (za, ea1, ea2, ew1, ehw1, ew2, ehw2)):
            raise ValueError("negative R_ext exponent requires an explicit "
                             "chart adapter: %r" % (key,))
        try:
            c0, c1 = (Fraction(k3_coefficient[0]),
                      Fraction(k3_coefficient[1]))
        except (IndexError, TypeError) as error:
            raise ValueError("bad K3 coefficient %r" %
                             (k3_coefficient,)) from error
        w_monomial = (ew1 + ehw1, ew2 + ehw2)
        coefficient = out.get(w_monomial, RadicalCoefficient())
        if c0:
            coefficient += RadicalCoefficient({
                (za, 0, ea1, ea2, ehw1 + ehw2): c0})
        if c1:
            coefficient += RadicalCoefficient({
                (za, 1, ea1, ea2, ehw1 + ehw2): c1})
        if coefficient:
            out[w_monomial] = coefficient
        else:
            out.pop(w_monomial, None)
    return out


@dataclass(frozen=True)
class RootFrame:
    zeta42: int
    r3: int
    A1: int
    A2: int
    h: int

    def reduced(self, modulus: int) -> "RootFrame":
        return RootFrame(*(value % modulus for value in
                           (self.zeta42, self.r3, self.A1, self.A2, self.h)))


REGISTERED_FRAMES = {
    105337: RootFrame(2779, 795, 50630, 10114, 50267),
    105673: RootFrame(13862, 14686, 38664, 46664, 35053),
}

# The source-model Hensel frame currently banked only at p=105337.
REGISTERED_P2_FRAME_105337 = RootFrame(
    8852313585, 11012141449, 786496672, 8038065910, 6003627245)


class SpecializationError(ValueError):
    pass


def validate_specialization(modulus: int, frame: RootFrame,
                            denominators: Iterable[int] = ()) -> dict:
    """Validate the literal radical map, primitivity, and simple-root gates."""
    if modulus <= 2:
        raise SpecializationError("modulus must be odd and > 2")
    frame = frame.reduced(modulus)
    z, r, a1, a2, h = (frame.zeta42, frame.r3, frame.A1,
                        frame.A2, frame.h)
    equations = {
        "Phi42(zeta42)": _poly_eval(PHI42, z, modulus),
        "r3^2-3": (r * r - 3) % modulus,
        "A1^3-(3+r3)": (pow(a1, 3, modulus) - 3 - r) % modulus,
        "A2^3-(3-r3)": (pow(a2, 3, modulus) - 3 + r) % modulus,
        "2*h^2-3": (2 * h * h - 3) % modulus,
    }
    failed = {name: residue for name, residue in equations.items() if residue}
    if failed:
        raise SpecializationError("defining equations fail: %s" % failed)

    order_tests = {d: pow(z, d, modulus) for d in (6, 14, 21, 42)}
    if order_tests[42] != 1 or any(order_tests[d] == 1 for d in (6, 14, 21)):
        raise SpecializationError("zeta42 does not have exact order 42: %s" %
                                  order_tests)

    derivatives = {
        "Phi42'(zeta42)": _poly_eval(PHI42_DERIV, z, modulus),
        "2*r3": 2 * r % modulus,
        "3*A1^2": 3 * a1 * a1 % modulus,
        "3*A2^2": 3 * a2 * a2 % modulus,
        "4*h": 4 * h % modulus,
    }
    nonunits = {name: value for name, value in derivatives.items()
                if math.gcd(value, modulus) != 1}
    if nonunits:
        raise SpecializationError("non-simple radical roots: %s" % nonunits)

    bad_denominators = [int(d) for d in denominators
                        if not d or math.gcd(int(d), modulus) != 1]
    if bad_denominators:
        raise SpecializationError("nonunit denominators: %s" %
                                  bad_denominators)
    return {"modulus": modulus, "equations": equations,
            "order_tests": order_tests, "derivatives": derivatives,
            "denominators": [int(d) for d in denominators]}


def validate_registered_prime(prime: int, frame: RootFrame | None = None) -> dict:
    if prime not in REGISTERED_FRAMES:
        raise SpecializationError("unregistered D43 prime %d" % prime)
    expected = REGISTERED_FRAMES[prime]
    actual = (frame or expected).reduced(prime)
    if actual != expected:
        raise SpecializationError("root frame drift at p=%d: %r != %r" %
                                  (prime, actual, expected))
    return validate_specialization(prime, actual, SOURCE_NEWTON_DENOMINATORS)


class BundleNotReady(RuntimeError):
    pass


class CertificationBundle:
    """Two-tier metadata shell for a future exact emitter.

    ``seal_source`` needs the common 34 parked rows, the 184 pristine source
    rows, and an exact coordinate descent/reconstruction certificate.  The
    last gate is essential because the pristine source Jacobian currently
    lives on 190 coordinates whereas the banked assembled presentation has
    184.  This is the reducer-free presentation relevant to direct Hensel
    work.  ``seal_presentation_equivalence`` additionally needs all 509
    reducer-to-parked identities and all 184 source-to-NF identities; it is
    the stronger comparison with the already banked modular NF model.
    """

    SOURCE_COUNTS = {"parked": 34, "pristine": 184}
    EQUIVALENCE_COUNTS = {"reducers": 509, "graph_nf": 184}
    PARKED_KINDS = {"d21_core": 26, "d23_compat": 3, "d25_schur": 5}
    SOURCE_GATE_NAMES = (
        "common_coordinate_registry_and_source_descent",
        "d21_core_chart_equivalence",
        "d23_rank2_forward_and_solveback",
        "d25_rank4_forward_and_solveback",
        "specialization_matches_both_primes",
    )

    def __init__(self):
        self._entries = {name: {} for name in
                         tuple(self.SOURCE_COUNTS) + tuple(self.EQUIVALENCE_COUNTS)}
        self._source_gates = {}

    @staticmethod
    def _sha256(value: str) -> str:
        if len(value) != 64 or any(ch not in "0123456789abcdef" for ch in value):
            raise ValueError("expected lowercase SHA-256, got %r" % value)
        return value

    def add(self, block: str, label: str, payload_sha256: str,
            provenance_sha256: str, identity_sha256: str | None = None,
            kind: str | None = None,
            solveback_sha256: str | None = None) -> None:
        if block not in self._entries:
            raise KeyError(block)
        if label in self._entries[block]:
            raise ValueError("duplicate %s label %s" % (block, label))
        if block in ("parked", "reducers", "graph_nf") and identity_sha256 is None:
            raise ValueError("%s entry requires an exact identity digest" % block)
        if block == "parked":
            if kind not in self.PARKED_KINDS:
                raise ValueError("parked row requires kind in %s" %
                                 sorted(self.PARKED_KINDS))
            if kind in ("d23_compat", "d25_schur") and solveback_sha256 is None:
                raise ValueError("%s row requires a solve-back digest" % kind)
        elif kind is not None or solveback_sha256 is not None:
            raise ValueError("kind/solveback are reserved for parked rows")
        self._entries[block][label] = {
            "payload_sha256": self._sha256(payload_sha256),
            "provenance_sha256": self._sha256(provenance_sha256),
            "identity_sha256": (self._sha256(identity_sha256)
                                if identity_sha256 is not None else None),
            "kind": kind,
            "solveback_sha256": (self._sha256(solveback_sha256)
                                 if solveback_sha256 is not None else None),
        }

    def add_source_gate(self, name: str, certificate_sha256: str) -> None:
        if name not in self.SOURCE_GATE_NAMES:
            raise KeyError(name)
        if name in self._source_gates:
            raise ValueError("duplicate source gate %s" % name)
        self._source_gates[name] = self._sha256(certificate_sha256)

    def source_readiness_errors(self):
        errors = []
        for block, expected in self.SOURCE_COUNTS.items():
            found = len(self._entries[block])
            if found != expected:
                errors.append("%s count %d != %d" % (block, found, expected))
        kind_counts = {kind: 0 for kind in self.PARKED_KINDS}
        for entry in self._entries["parked"].values():
            if entry["kind"] in kind_counts:
                kind_counts[entry["kind"]] += 1
        for kind, expected in self.PARKED_KINDS.items():
            if kind_counts[kind] != expected:
                errors.append("parked kind %s count %d != %d" %
                              (kind, kind_counts[kind], expected))
        for name in self.SOURCE_GATE_NAMES:
            if name not in self._source_gates:
                errors.append("missing source gate %s" % name)
        return errors

    def equivalence_readiness_errors(self):
        errors = self.source_readiness_errors()
        for block, expected in self.EQUIVALENCE_COUNTS.items():
            found = len(self._entries[block])
            if found != expected:
                errors.append("%s count %d != %d" % (block, found, expected))
        return errors

    def _seal(self, tier: str, errors) -> dict:
        if errors:
            raise BundleNotReady("; ".join(errors))
        payload = {
            "schema": "d43-common-integral-certification-v1",
            "tier": tier,
            "basis_shape": BASIS_SHAPE,
            "basis_rank": BASIS_RANK,
            "source_counts": dict(self.SOURCE_COUNTS),
            "parked_kinds": dict(self.PARKED_KINDS),
            "source_gates": self._source_gates,
            "entries": self._entries,
        }
        if tier == "presentation-equivalence":
            payload["equivalence_counts"] = dict(self.EQUIVALENCE_COUNTS)
        encoded = json.dumps(payload, sort_keys=True,
                             separators=(",", ":")).encode()
        payload["aggregate_sha256"] = hashlib.sha256(encoded).hexdigest()
        return payload

    def seal_source(self) -> dict:
        return self._seal("source-existence", self.source_readiness_errors())

    def seal_presentation_equivalence(self) -> dict:
        return self._seal("presentation-equivalence",
                          self.equivalence_readiness_errors())


def selftest() -> dict:
    z = RadicalCoefficient.generator("zeta42")
    r = RadicalCoefficient.generator("r3")
    a1 = RadicalCoefficient.generator("A1")
    a2 = RadicalCoefficient.generator("A2")
    h = RadicalCoefficient.generator("h")
    phi = sum((coefficient * (z ** exponent)
               for exponent, coefficient in enumerate(PHI42)),
              RadicalCoefficient())
    assert not phi
    assert r ** 2 == 3
    assert a1 ** 3 == 3 + r
    assert a2 ** 3 == 3 - r
    assert 2 * (h ** 2) == 3
    assert BASIS_RANK == 432
    gates = {str(p): validate_registered_prime(p)
             for p in sorted(REGISTERED_FRAMES)}
    modulus = 105337 ** 2
    gates[str(modulus)] = validate_specialization(
        modulus, REGISTERED_P2_FRAME_105337, SOURCE_NEWTON_DENOMINATORS)
    bundle = CertificationBundle()
    try:
        bundle.seal_source()
    except BundleNotReady:
        pass
    else:
        raise AssertionError("empty certification bundle sealed")
    return {"basis_rank": BASIS_RANK, "specialization_gates": gates,
            "empty_bundle": "FAIL-CLOSED"}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--selftest", action="store_true", required=True)
    args = parser.parse_args()
    if args.selftest:
        print(json.dumps(selftest(), indent=1, sort_keys=True))


if __name__ == "__main__":
    main()
