#!/usr/bin/env python3
"""Orchestrate the (99,66) outer Theorem-1.2 / T2-T3 add-on.

Does not modify box/g9966-20260903/.  Frozen-input hashes are checked against
the lane receipt via inputs.sha256 (generated by awk from charged_input_*).
"""
from __future__ import annotations

import hashlib
import json
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
RECEIPT = ROOT / "xmodel/g9966-outer-bridge-grok46-20260903.run.v2"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def verify_frozen() -> dict:
    fields: dict[str, str] = {}
    for line in RECEIPT.read_text(encoding="utf-8").splitlines():
        if "=" in line:
            key, value = line.split("=", 1)
            fields[key] = value
    count = int(fields["charged_inputs"])
    frozen = Path(fields["lane_inputs_dir"])
    checked = []
    for index in range(1, count + 1):
        name = fields[f"charged_input_{index}_basename"]
        expected = fields[f"charged_input_{index}_sha256"]
        actual = sha256(frozen / name)
        if actual != expected:
            raise SystemExit(f"hash mismatch: {name}")
        checked.append({"basename": name, "sha256": actual})
    manifest = HERE / "inputs.sha256"
    proc = subprocess.run(
        ["sha256sum", "-c", str(manifest)],
        capture_output=True,
        text=True,
        check=False,
    )
    ok_lines = [line for line in proc.stdout.splitlines() if line.endswith(": OK")]
    return {
        "receipt": str(RECEIPT),
        "lane_inputs_dir": str(frozen),
        "charged_inputs": count,
        "all_hashes_match": True,
        "manifest_ok_count": len(ok_lines),
        "files": checked,
    }


def load_module_run(name: str):
    sys.path.insert(0, str(HERE))
    mod = __import__(name)
    return mod.run()


def main() -> None:
    started = time.perf_counter()
    custody = verify_frozen()
    assert custody["charged_inputs"] == 21
    assert custody["manifest_ok_count"] == 21

    def load_json(name: str) -> dict:
        path = HERE / f"{name}.json"
        if path.exists():
            return json.loads(path.read_text(encoding="utf-8"))
        t0 = time.perf_counter()
        data = load_module_run(name)
        path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")
        data["_elapsed"] = time.perf_counter() - t0
        return data

    t0 = time.perf_counter()
    bands = load_json("outer_order_bands")
    t_bands = time.perf_counter() - t0

    t0 = time.perf_counter()
    bridge = load_json("t2t3_bridge")
    t_bridge = time.perf_counter() - t0

    t0 = time.perf_counter()
    controls = load_json("controls")
    t_controls = time.perf_counter() - t0

    assert bands["controls"]["h2_D1_replay_matches_charged_7"]
    assert bands["controls"]["prefix_15_subset_of_D2"]
    assert bands["totals"]["D1_Qstar_rank"] == 176
    assert bands["totals"]["D2_unit_rows"] == 5598
    assert bridge["controls"]["mu2_55"]
    assert bridge["controls"]["face_p5_not_in_Tschirnhausen_span"]
    assert controls["controls_pass"]

    output = {
        "type": (
            "COUNTING-BOUND[OUTER-THM12-D2-D1 + PREFIX] / "
            "OPEN[EFFECTIVE-T2-T3-BRIDGE] / "
            "SATURATED-EMPTY[P208 / GF(32003)] / "
            "SURVIVES[AUTOMORPHISM]"
        ),
        "frozen_input_verification": custody,
        "elapsed_seconds": {
            "order_bands": round(t_bands, 4),
            "t2t3_bridge": round(t_bridge, 4),
            "controls": round(t_controls, 4),
            "total": round(time.perf_counter() - started, 4),
        },
        "order_bands": bands,
        "t2t3_bridge": bridge,
        "controls": controls,
        "row_inventory_summary": {
            "PRINTED": [
                "chart (2.1) 7161 coordinates",
                "major h3-inside-h2 516 -> 120 (charged, not recomputed)",
                "minor leaders (2.4)(2.6) and reduced T3 ODE (charged)",
                "Jacobian IJ, first 10 deg-162 rows rank 15 (charged)",
                "Moh Thm 1.2 (p.149), T_r^psi (p.152), Xu §7.3 (p.10)",
            ],
            "DERIVED": [
                f"D2 unit vanishings A2+A3+B1+B2 = {bands['totals']['D2_unit_rows']}",
                f"D1 gap Q* rank = {bands['totals']['D1_Qstar_rank']}",
                "h3-adic F_j,G_j D2 bounds after chart expansion (0 new outer pivots)",
                "T2 = G^3 - F^2 + 5 unknown k-coefficients (Moh-literal)",
                "T3 = G^9 - F^6 + 35 unknown k-coefficients (Moh-literal)",
            ],
            "OPEN": [
                "OPEN[EFFECTIVE-T2-T3-BRIDGE]: identification of T2(sigma), T3(sigma) "
                "with p^5 and R / p^{10} q1 from subleading F,G jets",
                "unranked remainder of IJ",
                "Moh unprinted 11-variable minor elimination",
            ],
        },
        "new_dimensions": bands["joint_dimensions"],
        "next_system": (
            "On the D2-reduced outer space (1002 remaining A,B coordinates), "
            "impose the D1 gap rows (already ranked here) and continue the "
            "degree-162 Jacobian at [x^135 y^27] together with pole rows "
            "F_(95,*)/G_(62,*).  The T2/T3 jet identification remains "
            "OPEN[EFFECTIVE-T2-T3-BRIDGE] and is not a linear add-on of this prefix."
        ),
    }
    path = HERE / "results.json"
    path.write_text(json.dumps(output, indent=2, sort_keys=True) + "\n")
    print(json.dumps(output, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
