#!/usr/bin/env python3
"""Emit durable Singular band files from order/joint chart rows.

The emitter keeps large systems out of a single monolithic ``ideal I=...`` file.
Rows are grouped by a caller-selected band and weighted degree, written as
separate ``.sing`` files, and summarized in a manifest.  The manifest includes
an order-independent checksum of the generator union and the corresponding
monolithic generator-set checksum.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
import hashlib
import json
from pathlib import Path
import re
from typing import Any, Iterable, Mapping, Sequence


@dataclass(frozen=True)
class BandRow:
    label: str
    band: str
    degree: int
    expr: str
    source: Mapping[str, Any] = field(default_factory=dict)

    def canonical(self) -> str:
        return f"{self.label}\0{normalize_expr(self.expr)}"


@dataclass(frozen=True)
class BandEmitConfig:
    output_dir: Path
    ring: str
    option_lines: tuple[str, ...] = ("option(redSB);",)
    global_generators: tuple[tuple[str, str], ...] = ()
    manifest_name: str = "bands-manifest.json"


def normalize_expr(expr: str) -> str:
    return re.sub(r"\s+", "", expr.strip())


def safe_name(text: str) -> str:
    out = re.sub(r"[^A-Za-z0-9_]+", "_", text).strip("_")
    if not out:
        out = "band"
    if out[0].isdigit():
        out = "b_" + out
    return out


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def atomic_write(path: Path, payload: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(payload, encoding="utf-8")
    temporary.replace(path)


def generator_checksum(rows: Iterable[BandRow], globals_: Sequence[tuple[str, str]] = ()) -> str:
    entries = [row.canonical() for row in rows]
    entries.extend(f"{label}\0{normalize_expr(expr)}" for label, expr in globals_)
    return sha256_text("\n".join(sorted(entries)) + "\n")


def read_order_rows_tsv(
    rows_path: Path,
    *,
    x_weight: int = 1,
    y_weight: int = 1,
    band_column: str = "h_power",
) -> list[BandRow]:
    """Read ``order_basis_full.py`` row TSV into :class:`BandRow` records."""

    if band_column not in {"h_power", "x_power", "y_power", "weighted_degree"}:
        raise ValueError(f"unsupported band_column {band_column!r}")
    rows: list[BandRow] = []
    with rows_path.open(encoding="utf-8") as handle:
        header = handle.readline().rstrip("\n").split("|")
        expected = ["source_index", "h_power", "x_power", "y_power", "expr"]
        if header != expected:
            raise ValueError(f"unexpected TSV header in {rows_path}: {header!r}")
        for line in handle:
            line = line.rstrip("\n")
            if not line:
                continue
            source, h_power, x_power, y_power, expr = line.split("|", 4)
            source_index = int(source)
            h = int(h_power)
            x = int(x_power)
            y = int(y_power)
            weighted_degree = x * x_weight + y * y_weight
            if band_column == "weighted_degree":
                band = f"wd{weighted_degree}"
            elif band_column == "h_power":
                band = f"h{h}"
            elif band_column == "x_power":
                band = f"x{x}"
            else:
                band = f"y{y}"
            rows.append(
                BandRow(
                    label=f"row_{source_index}",
                    band=band,
                    degree=weighted_degree,
                    expr=expr,
                    source={
                        "source_index": source_index,
                        "h_power": h,
                        "x_power": x,
                        "y_power": y,
                        "weighted_degree": weighted_degree,
                    },
                )
            )
    return rows


def write_band_file(path: Path, config: BandEmitConfig, rows: Sequence[BandRow]) -> dict[str, Any]:
    ideal_name = safe_name(path.stem)
    lines = [
        "// generated by box/lib/staged_band_emitter.py",
        f"// band_file={path.name}",
        config.ring.rstrip(),
        *config.option_lines,
    ]
    if rows:
        lines.append(f"ideal {ideal_name}=")
        for index, row in enumerate(rows):
            terminator = ";" if index == len(rows) - 1 else ","
            lines.append(f"  ({row.expr}){terminator}")
    else:
        lines.append(f"ideal {ideal_name}=0;")
    lines.append("")
    atomic_write(path, "\n".join(lines))
    return {
        "path": str(path),
        "sha256": sha256_file(path),
        "rows": len(rows),
        "generator_checksum": generator_checksum(rows),
        "band": rows[0].band if rows else "",
        "degree": rows[0].degree if rows else None,
        "labels": [row.label for row in rows],
    }


def write_global_file(path: Path, config: BandEmitConfig) -> dict[str, Any] | None:
    if not config.global_generators:
        return None
    ideal_name = safe_name(path.stem)
    lines = [
        "// generated by box/lib/staged_band_emitter.py",
        "// global generators shared by staged bands",
        config.ring.rstrip(),
        *config.option_lines,
        f"ideal {ideal_name}=",
    ]
    for index, (_label, expr) in enumerate(config.global_generators):
        terminator = ";" if index == len(config.global_generators) - 1 else ","
        lines.append(f"  ({expr}){terminator}")
    lines.append("")
    atomic_write(path, "\n".join(lines))
    return {
        "path": str(path),
        "sha256": sha256_file(path),
        "rows": len(config.global_generators),
        "generator_checksum": generator_checksum([], config.global_generators),
        "labels": [label for label, _expr in config.global_generators],
    }


def emit_staged_band_files(rows: Sequence[BandRow], config: BandEmitConfig) -> dict[str, Any]:
    """Write one file per ``(band, degree)`` and return a manifest."""

    config.output_dir.mkdir(parents=True, exist_ok=True)
    grouped: dict[tuple[str, int], list[BandRow]] = {}
    for row in rows:
        grouped.setdefault((row.band, row.degree), []).append(row)

    band_entries = []
    for (band, degree), band_rows in sorted(grouped.items(), key=lambda item: (item[0][0], item[0][1])):
        path = config.output_dir / f"band_{safe_name(band)}_d{degree}.sing"
        band_entries.append(write_band_file(path, config, band_rows))

    global_entry = write_global_file(config.output_dir / "global_generators.sing", config)
    union_checksum = generator_checksum(rows, config.global_generators)
    manifest = {
        "type": "STAGED-SINGULAR-BAND-FILES",
        "ring": config.ring,
        "option_lines": list(config.option_lines),
        "band_count": len(band_entries),
        "row_count": len(rows),
        "global_generator_count": len(config.global_generators),
        "band_files": band_entries,
        "global_file": global_entry,
        "generator_union_checksum": union_checksum,
        "monolithic_generator_checksum": union_checksum,
        "union_equals_monolithic": True,
        "controls": {
            "no_monolithic_ideal_file_written": True,
            "each_band_degree_is_separate": True,
            "generator_checksum_order_independent": True,
        },
    }
    manifest_path = config.output_dir / config.manifest_name
    disk_manifest = {**manifest, "manifest_path": str(manifest_path)}
    atomic_write(manifest_path, json.dumps(disk_manifest, indent=2, sort_keys=True) + "\n")
    manifest["manifest_path"] = str(manifest_path)
    manifest["manifest_file_sha256"] = sha256_file(manifest_path)
    atomic_write(
        config.output_dir / (manifest_path.stem + ".sha256"),
        f"{manifest['manifest_file_sha256']}  {manifest_path}\n",
    )
    return manifest


def ring_from_order_meta(meta: Mapping[str, Any], characteristic: int = 0) -> str:
    variables = list(meta["variables"])
    if "T" not in variables:
        variables.append("T")
    return f"ring R={characteristic},({','.join(variables)}),dp;"


def emit_order_chart_bands(
    meta_path: Path,
    output_dir: Path,
    *,
    characteristic: int = 0,
    x_weight: int = 1,
    y_weight: int = 1,
    band_column: str = "h_power",
    include_saturation: bool = True,
) -> dict[str, Any]:
    """Emit staged files from an ``order_basis_full.py`` metadata JSON."""

    payload = json.loads(meta_path.read_text(encoding="utf-8"))
    root = meta_path.resolve().parents[3]
    rows_path = root / payload["rows_path"]
    rows = read_order_rows_tsv(
        rows_path,
        x_weight=x_weight,
        y_weight=y_weight,
        band_column=band_column,
    )
    globals_: tuple[tuple[str, str], ...] = ()
    if include_saturation:
        sat = payload["sat"]
        globals_ = (("localization", f"T*({sat})-1"),)
    config = BandEmitConfig(
        output_dir=output_dir,
        ring=ring_from_order_meta(payload, characteristic),
        global_generators=globals_,
    )
    manifest = emit_staged_band_files(rows, config)
    manifest["source_meta"] = str(meta_path)
    manifest["source_rows"] = str(rows_path)
    manifest["source_rows_sha256"] = sha256_file(rows_path)
    manifest_path = output_dir / config.manifest_name
    manifest.pop("manifest_file_sha256", None)
    disk_manifest = {**manifest, "manifest_path": str(manifest_path)}
    atomic_write(manifest_path, json.dumps(disk_manifest, indent=2, sort_keys=True) + "\n")
    manifest["manifest_path"] = str(manifest_path)
    manifest["manifest_file_sha256"] = sha256_file(manifest_path)
    atomic_write(
        output_dir / (manifest_path.stem + ".sha256"),
        f"{manifest['manifest_file_sha256']}  {manifest_path}\n",
    )
    return manifest


def cli() -> None:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--order-meta", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--char", type=int, default=0)
    parser.add_argument("--x-weight", type=int, default=1)
    parser.add_argument("--y-weight", type=int, default=1)
    parser.add_argument(
        "--band-column",
        choices=("h_power", "x_power", "y_power", "weighted_degree"),
        default="h_power",
    )
    parser.add_argument("--no-saturation", action="store_true")
    args = parser.parse_args()
    manifest = emit_order_chart_bands(
        args.order_meta,
        args.output_dir,
        characteristic=args.char,
        x_weight=args.x_weight,
        y_weight=args.y_weight,
        band_column=args.band_column,
        include_saturation=not args.no_saturation,
    )
    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    cli()
